#!/bin/bash
set -e

version=$(cpld-fw-handler version -i i2c -b 8 -a 0x44 | awk '{print $NF}')

busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/Minerva_CMM_cmm_cpld \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"
