#!/bin/bash

# ARGUMENTS:
# 1: RPU Number
# 2: Config file

if [ $# -lt 2 ]; then
    echo "Usage: $0 <rpu_number> <config>
      rpu_number: The RPU number
      config: Configuration file that include mapping of rpu number to unique device address"
    exit 1
fi

set -eu

RPU_NUM="$1"
CONFIG_FILE="$2"

jq -er ".uniqueDeviceAddressMappings.\"$RPU_NUM\"" "$CONFIG_FILE"
