#!/bin/bash

# ARGUMENTS:
# 1: Optional override config

OVERRIDE_CONFIG_FILE=${1:-/run/mnt-persist/var-data/lib/rpu-controller/override-config.json}
CONFIG_FILE="/var/lib/rpu-controller/default-config.json"

if [ -f "$OVERRIDE_CONFIG_FILE" ]; then
    CONFIG_FILE="$OVERRIDE_CONFIG_FILE"
fi

script_dir=$( dirname "${BASH_SOURCE[0]}" )
jq -r '
  .uniqueDeviceAddressMappings
  | to_entries
  | map({ key: (.value|tostring), value: { location: .key } })
  | from_entries
' "$CONFIG_FILE" | jq -c "to_entries[]" | while read -r element; do
  uda=$(echo "$element" | jq -r .key)
  location=$(echo "$element" | jq -r .value.location)
  manufacturer=$("$script_dir/get-rpu-manufacturer" "$uda" "$CONFIG_FILE")
  jq -n --arg key "$uda" --arg location "$location" --arg manufacturer "$manufacturer" \
    '{($key): {location: $location, manufacturer: $manufacturer}}'
done | jq -s 'add'
