#!/bin/bash

# ARGUMENTS:
# 1: RPU unique device address
# 2: Optional override config

if [ $# -lt 1 ]; then
    echo "Usage: $0 <rpu_uda> [override_config]
      rpu_uda: The RPU unique device address
      override_config: Optional configuration file to override default settings"
    exit 1
fi

set -u

OVERRIDE_CONFIG_FILE=${2:-/run/mnt-persist/var-data/lib/rpu-controller/override-config.json}
CONFIG_FILE="/var/lib/rpu-controller/default-config.json"

if [ -f "$OVERRIDE_CONFIG_FILE" ]; then
    CONFIG_FILE="$OVERRIDE_CONFIG_FILE"
fi

# unique device address
UDA="$1"

aalcStatusAlarmRegister=37377

if ! output=$(rackmoncli read "$UDA" "$aalcStatusAlarmRegister") ; then
  echo "{\"message\": \"Rackmon output: $output\", \"status\": \"error\"}"
  exit 1
fi

case $output in
  0x*)
    if (( (output & 0x0200) == 0 )); then
      echo '{"status": "success", "ready": true}'
    else
      echo '{"status": "success", "ready": false}'
    fi
    ;;
  *)
    echo "{\"message\": \"Rackmon output: $output\", \"status\": \"error\"}"
    exit 1
    ;;
esac
