swagger: '2.0'
info:
  description: Swagger doc for /api/server/sensors
  title: Swagger doc for /api/server/sensors
  version: 1.0.0
paths:
  /api/server/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  BS_INLET_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_P12V_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_P3V3_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_P1V05_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_P3V_BAT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_PVNN_PCH_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_HSC_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_HSC_IN_VOL:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_HSC_IN_PWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_HSC_OUT_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_BOOT_DRV_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_PCH_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMA_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMB_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMD_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMME_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_CPU_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_THERM_MARGIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_CPU_TJMAX:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_CPU_PKG_PWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_HSC_IN_AVGPWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCIN_VR_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCIN_VR_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCIN_VR_VOL:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCIN_VR_PWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCSA_VR_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCSA_VR_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCSA_VR_VOL:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCSA_VR_PWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCIO_VR_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCIO_VR_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCIO_VR_VOL:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_VCCIO_VR_PWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMAB_VR_TMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMAB_VR_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMAB_VR_VOL:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMAB_VR_PWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMDE_VR_TEM:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMDE_VR_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMDE_VR_VOL:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  BS_DIMMDE_VR_PWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
