FILESEXTRAPATHS:prepend := "${THISDIR}/6.18:"

#
# Patches to be upstreamed soon.
#
SRC_URI:append = " \
    file://0001-ARM-dts-aspeed-Add-Facebook-fblite-r1-BMC.patch \
    file://0002-ARM-dts-aspeed-Add-device-tree-for-Facebook-meru-AST.patch \
"

#
# JTAG patches.
# Used by multiple OpenBMC platforms for firmware upgrade.
#
SRC_URI:append = " \
    file://0100-drivers-jtag-Add-JTAG-core-driver.patch \
    file://0101-dt-binding-jtag-Aspeed-2400-and-2500-series.patch \
    file://0102-Add-Aspeed-SoC-24xx-and-25xx-families-JTAG-master-dr.patch \
    file://0103-jtag-aspeed-support-sysfs-interface.patch \
    file://0104-jtag-support-driver-specific-ioctl-commands.patch \
    file://0105-jtag-aspeed-support-JTAG_RUN_CYCLE-ioctl-command.patch \
    file://0106-jtag-aspeed-add-AST2600-support.patch \
    file://0107-Documentation-jtag-Add-ABI-documentation.patch \
    file://0108-Documentation-jtag-Add-JTAG-core-driver-ioctl-number.patch \
    file://0109-drivers-jtag-Add-JTAG-core-driver-Maintainers.patch \
    file://0110-fixup-jtag-patch-series.patch \
    file://0111-ARM-dts-aspeed-g6-add-jtag-controllers.patch \
    file://0112-ARM-dts-aspeed-g5-add-jtag-controller.patch \
"

#
# ASPEED controller related patches.
#
SRC_URI:append = " \
    file://0200-spi-aspeed-add-shutdown-path-for-AST25XX-SPI-control.patch \
    file://0201-spi-add-user-mode-aspeed-spi-driver.patch \
    file://0202-aspeed-i2c-add-clock-duty-cycle-property.patch \
    file://0203-dt-bindings-aspeed-i2c-add-properties-for-setting-i2.patch \
    file://0204-i2c-aspeed-update-ast2400-timing-settings.patch \
    file://0205-i2c-add-a-slave-backend-to-receive-and-queue-message.patch \
    file://0206-i2c-aspeed-add-i2c-slave-inactive-timeout-support.patch \
    file://0207-Add-ASPEED-AST2600-I2Cv2-controller-driver.patch \
    file://0208-ARM-dts-aspeed-g6-Add-AST2600-I3Cs.patch \
    file://0209-dt-bindings-i3c-hub-Add-Renesas-RG3MxxB12A1-I3C-HUB.patch \
    file://0210-i3c-i3c-hub-Add-Renesas-RG3MxxB12A1-I3C-HUB-driver.patch \
    file://0211-ARM-dts-aspeed-g6-add-pcc-config-in-aspeed-g6.dtsi.patch \
    file://0212-dmaengine-aspeed-Add-AST2600-UART-DMA-driver.patch \
    file://0213-serial-8250-Add-AST2600-UART-driver.patch \
    file://0214-drivers-misc-Add-Aspeed-OTP-control-register.patch \
    file://0215-soc-aspeed-lpc-pcc-Add-PCC-controller-support.patch \
    file://0216-i2c-ast2600-support-ssif.patch \
    file://0217-ARM-dts-aspeed-g6-Add-UDMA-node.patch \
    file://0218-net-ftgmac100-reset-MAC-by-SCU-on-RMII.patch \
    file://0219-net-ncsi-check-for-netlink-driven-responses-before-r.patch \
    file://0220-i3c-ast2600-Validate-AST2600-I3C-for-MCTP-over-I3C.patch \
    file://0221-i3c-dw-Add-err-messages-for-ibi_fifo_clear-handling.patch \
    file://0222-i3c-dw-handle-transfer-abort-errors-distinctly.patch \
    file://0223-i3c-dw-Handle-unexpected-responses-caused-by-SDA-noi.patch \
    file://0224-i3c-handle-null-transfers-during-response-processing.patch \
    file://0225-i3c-master-ast2600-Fix-missing-of_node-for-virtual-I.patch \
    file://0226-i3c-dw-Improve-IBI-queue-handling-when-encountering-.patch \
    file://0227-i3c-master-dw-i3c-master-Fix-race-condition-in-halt-.patch \
    file://0228-watchdog-aspeed-Support-variable-number-of-reset-mas.patch \
    file://0229-watchdog-aspeed-Add-support-for-AST2700-platform.patch \
    file://0230-spi-aspeed-Use-phys_addr_t-for-bus-addresses-to-supp.patch \
    file://0231-spi-aspeed-Add-support-for-the-AST2700-SPI-controlle.patch \
    file://0232-gpio-aspeed-sgpio-Create-llops-to-handle-hardware-ac.patch \
    file://0233-gpio-aspeed-sgpio-Convert-IRQ-functions-to-use-llops.patch \
    file://0234-gpio-aspeed-sgpio-Support-G7-Aspeed-sgpiom-controlle.patch \
    file://0235-iio-adc-aspeed-Add-AST2700-ADC-support.patch \
    file://0236-iio-adc-aspeed-Disable-the-last-channel-by-default.patch \
    file://0237-net-ftgmac100-add-support-for-AST2700.patch \
    file://0238-aspeed-i2c-add-i2c-clk-high-min-percent-property.patch \
    file://0239-iio-adc-aspeed-Support-deglitch-feature.patch \
"

#
# NCSI patches used by multiple OpenBMC platforms.
#
SRC_URI:append = " \
    file://0500-NCSI-Add-propety-no-channel-monitor-and-start-redo-p.patch \
    file://0501-net-ncsi-specify-maximum-package-to-probe.patch \
"

#
# hwmon/sensor drivers
#
SRC_URI:append = " \
    file://0600-hwmon-max31790-support-to-config-PWM-as-TACH.patch \
    file://0601-hwmon-max31790-add-fanN_enable-for-all-fans.patch \
    file://0602-hwmon-pmbus-Add-xdpe132g5c-driver.patch \
    file://0603-hwmon-Add-net_brcm-driver.patch \
    file://0604-Kernel6v5-Support-apml-driver.patch \
    file://0605-apml-Add-support-for-SP7-platform.patch \
    file://0606-hwmon-pmbus-tda38640-Add-identification-for-PMBUS_VO.patch \
    file://0607-iio-adc-ltc2309-explicitly-assign-hex-values-to-chan.patch \
    file://0608-iio-adc-ltc2309-add-support-for-ltc2305.patch \
    file://0609-amd-apml-sbrmi-update-SBRMI-revision-for-Venice.patch \
    file://0610-iio-adc-rtq6056-add-i2c_device_id-support.patch \
    file://0611-hwmon-pmbus-lm25066-Fix-PMBus-coefficients-for-LM506.patch \
    file://0612-dt-bindings-hwmon-pmbus-ti-lm25066-add-current-limit.patch \
    file://0613-hwmon-pmbus-lm25066-add-current-limit-configuration-.patch \
    file://0614-nfc-nxp-nci-Add-ISO15693-support.patch \
    file://0615-misc-amd-apml-Add-Venice-B0-I3C-device-IDs.patch \
    file://0616-dt-bindings-trivial-devices-Add-adi-max20912-and-max.patch \
    file://0617-hwmon-pmbus-Add-driver-for-Analog-Devices-MAX20912-a.patch \
"

#
# Hacks and workarounds
#
SRC_URI:append = " \
    file://0900-jffs2-kill-garbage-collect-thread-when-filesystem-is.patch \
    file://0901-jffs2-suppress-jffs2-messages-when-reading-inode.patch \
    file://0902-mmc-sdhci-of-aspeed-add-skip_probe-module-parameter.patch \
    file://0903-usb-gadget-f_ecm-disable-suspend-resume-feature.patch \
"

#
# AST2700 Patches at various stages of upstream. Since they are waiting
# for basic SOC to be merged they dont yet have LORE Links
#
SRC_URI:append = " \
    file://2700-clk-aspeed-add-AST2700-clock-driver.patch \
    file://2701-arm64-Kconfig-Add-ASPEED-SoC-family-Kconfig-support.patch \
    file://2702-arm64-dts-aspeed-Add-initial-AST27xx-SoC-device-tree.patch \
    file://2703-irqchip-ast2700-intc-Add-AST2700-A2-support.patch \
    file://2704-pinctrl-aspeed-Add-AST2700-SoC1-support.patch \
    file://2705-pinctrl-aspeed-Add-AST2700-SoC0-support.patch \
    file://2706-arm64-dts-aspeed-add-pinctrl-definitions-for-G7-plat.patch \
    file://2707-arm64-dts-aspeed-add-peripheral-nodes-for-G7-platfor.patch \
    file://2708-pinctrl-aspeed-Fix-GPIO-mux-value-for-ADC-capable-ba.patch \
    file://2709-usb-host-ehci-platform-add-ASPEED-AST2700-support.patch \
    file://2710-arm64-dts-aspeed-add-EHCI-and-MDIO-nodes-for-G7-plat.patch \
"
