swagger: '2.0'
info:
  description: Swagger doc for /api/sys/ntp
  title: Swagger doc for /api/sys/ntp
  version: 1.0.0
paths:
  /api/sys/ntp:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  stratum:
                    type: number
                  when:
                    type: number
                  poll:
                    type: number
                  reach:
                    type: number
                  delay:
                    type: number
                  offset:
                    type: number
                  jitter:
                    type: number
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
        404:
          description: No system peers
          schema:
            type: object
            additionalProperties: false
            properties:
              Resources:
                type: array
                items:
                  type: string
              Actions:
                type: array
                items:
                  type: string
              Information:
                type: object
                additionalProperties: false
                properties:
                  reason:
                    type: string
        500:
          description: Internal Server error
          schema:
            type: object
            additionalProperties: false
            properties:
              Resources:
                type: array
                items:
                  type: string
              Actions:
                type: array
                items:
                  type: string
              Information:
                type: object
                additionalProperties: false
                properties:
                  reason:
                    type: string
