chip "iio_hwmon-isa-0000"
    label in4 "P3V3_ALW"
    label in5 "P1V1"
    label in6 "P1V1_DDR"
    label in8 "P1V2"
    label in11 "P0V8"
    label in12 "P1V8"
    label in14 "P3V3"
    ignore in1
    ignore in2
    ignore in3
    ignore in7
    ignore in9
    ignore in10
    ignore in13
    ignore in15
    ignore in16
    compute in4 @ * 2, @ / 2
    compute in14 @ * 2, @ / 2
