# Until the device tree is merged into the upstream kernel, we need to
# override what is in the upstream ventura2.conf with the patched DTS reference.
KERNEL_DEVICETREE = "aspeed/${KMACHINE}-bmc-facebook-${MACHINE}.dtb"
