#!/bin/bash

source /usr/libexec/phosphor-state-manager/drive-power-control-util

# parse the input argument to extract the SSD number
if [[ "$1" =~ ^ssd([0-9]+)$ ]]; then
    ssd_num="${BASH_REMATCH[1]}"
else
    error "Invalid input format: $1. Expected format: ssd<num>"
    exit 1
fi

case "$ssd_num" in
  ''|*[!0-9]*)
    invalid_input "$ssd_num"
    ;;

  *)
    if (( ssd_num >= 0 && ssd_num < MAX_SSD_NUM )); then
        single_drive_power_control "$ssd_num" "off"
    else
        invalid_input "$ssd_num"
    fi
    ;;
esac

exit 0
