#!/bin/bash

jq --raw-output '
  def roundit: if . then (.*10000.0|round/10000.0) else "N/A" end;
  [["sensor", "status", "value", "units", "LNR", "LCR", "LNC", "UNC", "UCR", "UNR"]] +
  (to_entries | map([
    .key,
    .value.status,
    (.value.value | roundit),
    .value.unit,
    (.value."hard-shutdown".low | roundit),
    (.value.critical.low | roundit),
    (.value.warning.low | roundit),
    (.value.warning.high | roundit),
    (.value.critical.high | roundit),
    (.value."hard-shutdown".high | roundit)
  ])) | transpose |
  map(
    map(tostring) | (map(length) | max) as $max |
    map(. + (" " * ($max - length)))
  ) | transpose |
  .[0],
  (.[0] | map(length * "-")),
  .[1:][] |
  @tsv
'
