swagger: "2.0"
info: 
  description: Swagger doc for /api/attestation/system_information  
  title: Swagger doc for /api/attestation/system_information  
  version: 1.0.0
paths: 
  /api/attestation/system_information: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  system_hashes: 
                    type: object
                    additionalProperties: false
                    properties: 
                      spl: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      key-store: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      u-boot: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      rec-u-boot: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      u-boot-env: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      vbs: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      blank-u-boot-env: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                          measure: 
                            type: string
                      kernel: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      ramdisk: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      fdt: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      rec-kernel: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      rec-ramdisk: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                      rec-fdt: 
                        type: object
                        additionalProperties: false
                        properties: 
                          component: 
                            type: string
                          pcr_id: 
                            type: number
                            format: int32
                          algo: 
                            type: string
                          expect: 
                            type: string
                  tpm_info: 
                    type: object
                    additionalProperties: false
                    properties: 
                      tpm_version: 
                        type: string
                      tpm_fw_version: 
                        type: string
                      tpm_vendor: 
                        type: string
                      tpm_model: 
                        type: string
                      tpm_present: 
                        type: boolean
                      tpm_owned: 
                        type: boolean
                  system_info: 
                    type: object
                    additionalProperties: false
                    properties: 
                      agent_version: 
                        type: string
                      uname: 
                        type: string
                      tpm_tool_rpm_version: 
                        type: string
                      host_model: 
                        type: string
                      image_version:
                        type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string

