#!/bin/bash
#
# Copyright 2014-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#

LOGFILE="/var/log/mTerm_$1.log"
LOGFILE_B="/var/log/mTerm_$1_backup.log"

usage() {
  echo "Usage: sol-util [ mb, swb ]"
  echo "       sol-util [ mb, swb ] --history"
  exit 1
}

if [[ "$1" != "mb" ]] && [[ "$1" != "swb" ]]
then
  usage
fi

if [[ $# -lt 1 || $# -gt 2 ]]
then
  usage
else
  if [[ "$2" -eq "--history" ]]; then
    cat "$LOGFILE_B" "$LOGFILE" 2>/dev/null
    exit 0
  fi
fi


if [[ "$1" == "mb" ]]
then
  exec /usr/local/bin/mTerm_client mb
elif [[ "$1" == "swb" ]]
then
  exec /usr/local/bin/mTerm_client swb
fi
