swagger: "2.0"
info: 
  description: Swagger doc for /api/spb/sensors  
  title: Swagger doc for /api/spb/sensors  
  version: 1.0.0
paths: 
  /api/spb/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  BB_FAN0_TACH_RPM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_FAN1_TACH_RPM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_FAN2_TACH_RPM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_FAN3_TACH_RPM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_FAN4_TACH_RPM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_FAN5_TACH_RPM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_FAN6_TACH_RPM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_FAN7_TACH_RPM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_PWM0_TACH_PCT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_PWM1_TACH_PCT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_PWM2_TACH_PCT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_PWM3_TACH_PCT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_OUTLET_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_INLET_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_P5V_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_P12V_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_P3V3_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_P1V8_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_P1V2_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_P2V5_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_ADC_P1V0_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_ADC_P0V6_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_ADC_P3V3_RGM_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_ADC_P5V_USB_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_ADC_P3V3_NIC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_HSC_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_HSC_INPUT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_HSC_INPUT_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_HSC_OUTPUT_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_HSC_PEAK_OUTPUT_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_HSC_PEAK_INPUT_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_MEDUSA_OUTPUT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_MEDUSA_INPUT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_MEDUSA_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_MEDUSA_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_MEDUSA_VDELTA_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_CPU_CL_VDELTA_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_CPU_PDB_VDELTA_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_PMON_CURRENT_LEAKAGE_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_ADC_FAN_OUTPUT_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_FAN_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_ADC_NIC_P12V_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_ADC_NIC_OUTPUT_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BB_NIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PDB_VPDB_DELTA1_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PDB_48V_DELTA1_INPUT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PDB_12V_DELTA1_OUTPUT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PDB_DELTA1_OUTPUT_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            