python_library(
    # libraries can be declared, which allows them to be imported by other targets
    name = "rest_config",
    srcs = [
        "rest_config.py",
    ]
)

python_test(
    name = "restapiconfig",
    srcs = [
        "tests/test_rest_config.py",
    ],
    platform = 'py3',
    deps = [
        ":rest_config",
    ]
)
