#!/bin/bash

# ARGUMENTS:
# 1: Unique Dev Address
# 2: Config file

if [ $# -lt 2 ]; then
    echo "Usage: $0 <unique_device_address> <config>
      unique_device_address: The address of the modbus device to interact with
      config: Configuration file that include mapping of rpu number to unique device address"
    exit 1
fi

set -u

# unique device address
UDA="$1"
CONFIG_FILE="$2"

registerName=$(jq -er .rpu.manufacturerDiscriminator "$CONFIG_FILE")

registerValue=$(rackmoncli data --json --latest --dev-addr "$UDA" --reg-name "$registerName" |
    jq -er ".[0].regList[] | select(.name == \"$registerName\") | .history.[0].value.strValue")

if [ $? -ne 0 ]; then
    echo "unknown"
    exit 0
fi

jq \
    -er \
    --arg value "$registerValue" \
    '.rpu.manufacturers | to_entries[] | select(.value.registerValues | any(. == $value)) | .key' \
    "$CONFIG_FILE"

if [ $? -ne 0 ]; then
    echo "unknown"
    exit 0
fi
