#!/bin/bash

# ARGUMENTS:
# 1: Optional override config

OVERRIDE_CONFIG_FILE=${1:-/run/mnt-persist/var-data/lib/modbus-device-util/override-config.json}
CONFIG_FILE="/var/lib/modbus-device-util/default-config.json"

if [ -f "$OVERRIDE_CONFIG_FILE" ]; then
    CONFIG_FILE="$OVERRIDE_CONFIG_FILE"
fi

script_dir=$( dirname "${BASH_SOURCE[0]}" )
rackmoncli list --json | jq -er '.[] | "\(.deviceType) \(.uniqueDevAddress)"' | while read -r deviceType uda; do
  case $deviceType in
    "ORV3_BBU")
      device=bbu
      manufacturer=$("$script_dir/get-manufacturer" "$device" "$uda" "$CONFIG_FILE")
      ;;
    "ORV3_PSU")
      device=psu
      manufacturer=$("$script_dir/get-manufacturer" "$device" "$uda" "$CONFIG_FILE")
      ;;
    "ORV3_RPU")
      device=rpu
      manufacturer=$("$script_dir/get-manufacturer" "$device" "$uda" "$CONFIG_FILE")
      ;;
    *)
      device=unknown
      manufacturer=unknown
      ;;
  esac

  jq -n --arg key "$uda" --arg manufacturer "$manufacturer" --arg device "$device" \
    '{($key): {manufacturer: $manufacturer, device: $device}}'
done | jq -s 'add'
