#!/bin/bash

# ARGUMENTS:
# 1: Unique Dev Address
# 2: Command
# 3: Optional override config

if [ $# -lt 2 ]; then
    echo "Usage: $0 <unique_device_address> <command> [override_config]
      unique_device_address: The address of the modbus device to interact with
      command: The command to execute on the device: start, stop, restart, clear-sticky-registers
      override_config: Optional configuration file to override default settings"
    exit 1
fi

OVERRIDE_CONFIG_FILE=${3:-/run/mnt-persist/var-data/lib/modbus-device-util/override-config.json}

set -eux

# unique device address
UDA="$1"

COMMAND="$2"

CONFIG_FILE="/var/lib/modbus-device-util/default-config.json"

if [ -f "$OVERRIDE_CONFIG_FILE" ]; then
    CONFIG_FILE="$OVERRIDE_CONFIG_FILE"
fi

echo "Running $COMMAND command on RPU at unique device address $UDA"

function clear_sticky_registers {
    # Clear Sticky_IT_RPU_Stop_Pump_0
    rackmoncli write "$UDA" 6561 0

    # Clear Sticky_IT_RPU_Stop_Pump_1
    rackmoncli write "$UDA" 6562 0

    # Clear Sticky_IT_RPU_Stop_Pump_2
    rackmoncli write "$UDA" 6563 0

    # Clear Sticky_IT_RPU_Stop_Pump_3
    rackmoncli write "$UDA" 6564 0

    # Clear Sticky_RPU_Internal_Leakage_Abnormal
    rackmoncli write "$UDA" 6565 0

    # Clear Sticky_RPU_External_Leakage_Abnormal
    rackmoncli write "$UDA" 6566 0

    # Clear Sticky_RPU_Opt_External_Leakage1_Abnormal
    rackmoncli write "$UDA" 6567 0

    # Clear Sticky_RPU_Opt_External_Leakage2_Abnormal
    rackmoncli write "$UDA" 6568 0

    # Clear Sticky_HEX_Rack_Pan_Leakage
    rackmoncli write "$UDA" 6569 0

    # Clear Sticky_HEX_Rack_Floor_Leakage
    rackmoncli write "$UDA" 6570 0

    # Clear Sticky_HEX_Rack_Pan_Leakage_Relay
    rackmoncli write "$UDA" 6571 0

    # Clear Sticky_HEX_Rack_Floor_Leakage_Relay
    rackmoncli write "$UDA" 6572 0
}


function start_rpu {
    echo "Using $CONFIG_FILE config file"
    script_dir=$( dirname "${BASH_SOURCE[0]}" )
    manufacturer=$("$script_dir/get-manufacturer" rpu "$UDA" "$CONFIG_FILE")

    if [ -z "$manufacturer" ] || [ "$manufacturer" == "unknown" ]; then
        echo "Could not identify manufacturer. Exiting!"
        exit 1
    fi

    pumpDuty=$(jq -er ".rpu.manufacturers.${manufacturer}.pumpDutyPercentage" "$CONFIG_FILE")
    targetCoolantOutletTemp=$(jq -er ".rpu.manufacturers.${manufacturer}.targetCoolantOutletTempTimesTen" "$CONFIG_FILE")

    if [ "$manufacturer" == "delta" ]; then
        # Set RPU_Control to enable pump 1 and 2
        rackmoncli write "$UDA" 37904  128

        # Set pump duty
        rackmoncli write "$UDA" 37887  "$pumpDuty"

        # Set Auto_Tune_Coolant_Outlet_Temperature_Target_Set (scale is .1)
        rackmoncli write "$UDA" 37889  "$targetCoolantOutletTemp"

        # Set RPU_Control to start pump
        rackmoncli write "$UDA" 37904  32768
    elif [ "$manufacturer" == "quanta" ]; then
        # First 2 commands are for setting semi auto mode

        # Set Manual_Control_RPU_Fan_OnOff to 0
        rackmoncli write "$UDA" 42112  0

        # Set RPU_Control for semi auto mode
        rackmoncli write "$UDA" 37904  9

        # Set Manual_Control_Pump_Duty_Set
        rackmoncli write "$UDA" 37891  "$pumpDuty"

        # Set Auto_Tune_Coolant_Outlet_Temperature_Target_Set (scale is .1)
        rackmoncli write "$UDA" 37889  "$targetCoolantOutletTemp"

        # Set manual mode on pump
        rackmoncli write "$UDA" 42113  1

        # Set manual mode on fans
        rackmoncli write "$UDA" 42115  1
    else
        echo "Error: unknown start sequence for $manufacturer RPU!"
        exit 1
    fi
}

function start_rpu2 {
    echo "Using $CONFIG_FILE config file"
    script_dir=$( dirname "${BASH_SOURCE[0]}" )
    manufacturer=$("$script_dir/get-manufacturer" rpu2 "$UDA" "$CONFIG_FILE")

    if [ -z "$manufacturer" ] || [ "$manufacturer" == "unknown" ]; then
        echo "Could not identify manufacturer. Exiting!"
        exit 1
    fi

    pumpDuty=$(jq -er ".rpu2.manufacturers.${manufacturer}.pumpDutyPercentage" "$CONFIG_FILE")
    targetFlowRate=$(jq -er ".rpu2.manufacturers.${manufacturer}.targetFlowRateTimesTen" "$CONFIG_FILE")

    if [ "$manufacturer" == "coolermaster" ]; then
        # Clear sticky registers
        rackmoncli write "$UDA" 0x940B 0x03
        rackmoncli write "$UDA" 0x940B 0x00

        # HMI_Remote_Mode
        rackmoncli write "$UDA" 0x9400 0x0001

        # Set Auto1 On mode
        rackmoncli write "$UDA" 0x9410 0x07c2

        # Set coolant flow rate target (scale is 0.1)
        rackmoncli write "$UDA" 0x941A "$targetFlowRate"

        # Set Fan rack1 all fans duty
        rackmoncli write "$UDA" 0x941B "$pumpDuty"

        # Set Fan rack2 all fans duty
        rackmoncli write "$UDA" 0x941C "$pumpDuty"
    else
        echo "Error: unknown start sequence for $manufacturer RPU!"
        exit 1
    fi
}

deviceType=$(rackmoncli list --json | jq -r ".[] | select(.uniqueDevAddress == $UDA) | .deviceType")

if [ "$deviceType" == "ORV3_RPU" ]; then
    if [ "$COMMAND" == "restart" ]; then
        # Set RPU_Control flag to restart
        rackmoncli write "$UDA" 37904 64
    elif [ "$COMMAND" == "stop" ]; then
        # Set RPU_Control flag to stop
        rackmoncli write "$UDA" 37904 32
    elif [ "$COMMAND" == "clear-sticky-registers" ]; then
        clear_sticky_registers
    elif [ "$COMMAND" == "start" ]; then
        # clear_sticky_registers #TODO add this when tooling is updated
        start_rpu
    else
        echo "Error! '$COMMAND' is unknown!"
        exit 1
    fi
elif [ "$deviceType" == "ORV3_RPU2" ]; then
    if [ "$COMMAND" == "restart" ]; then
        echo "Unsupported: AALCv2 does not implement a restart"
        exit 1
    elif [ "$COMMAND" == "stop" ]; then
        rackmoncli write "$UDA" 0x9410 0x8000
    elif [ "$COMMAND" == "clear-sticky-registers" ]; then
        rackmoncli write "$UDA" 0x940B 0x03
        rackmoncli write "$UDA" 0x940B 0x00
    elif [ "$COMMAND" == "start" ]; then
        start_rpu2
    else
        echo "Error! '$COMMAND' is unknown!"
        exit 1
    fi
else
    echo "Error! $deviceType is not an RPU"
    exit 1
fi

echo "$COMMAND command on RPU at unique device address $UDA COMPLETE!"
