#!/bin/bash

# ARGUMENTS:
# 1: RPU unique device address

if [ $# -lt 1 ]; then
    echo "Usage: $0 <rpu_uda>
      rpu_uda: The RPU unique device address"
    exit 1
fi

set -u

FLOCK="flock /tmp/modbus_dynamo_solitonbeam.lock"

# unique device address
UDA="$1"
deviceType=$(rackmoncli list --json | jq -r ".[] | select(.uniqueDevAddress == $UDA) | .deviceType")

if [ "$deviceType" == "ORV3_RPU" ]; then
    aalcStatusAlarmRegister=37377
    aalcStatusAlarmRegisterMask=0x0200
elif [ "$deviceType" == "ORV3_RPU2" ]; then
    aalcStatusAlarmRegister=242
    aalcStatusAlarmRegisterMask=0x0001
else
    echo "Unsupported device type: $deviceType"
    exit 1
fi

if ! output=$($FLOCK rackmoncli read "$UDA" "$aalcStatusAlarmRegister") ; then
  echo "{\"message\": \"Rackmon output: $output\", \"status\": \"error\"}"
  exit 1
fi

case $output in
  0x*)
    if (( (output & aalcStatusAlarmRegisterMask) == 0 )); then
      echo '{"status": "success", "ready": true}'
    else
      echo '{"status": "success", "ready": false}'
    fi
    ;;
  *)
    echo "{\"message\": \"Rackmon output: $output\", \"status\": \"error\"}"
    exit 1
    ;;
esac
