#!/bin/bash

# ARGUMENTS:
# 1: RPU unique device address

if [ $# -lt 1 ]; then
    echo "Usage: $0 <rpu_uda>
      rpu_uda: The RPU unique device address"
    exit 1
fi

set -u

FLOCK="flock /tmp/modbus_dynamo_solitonbeam.lock"

# unique device address
UDA="$1"

aalcStatusAlarmRegister=37377

if ! output=$($FLOCK rackmoncli read "$UDA" "$aalcStatusAlarmRegister") ; then
  echo "{\"message\": \"Rackmon output: $output\", \"status\": \"error\"}"
  exit 1
fi

case $output in
  0x*)
    if (( (output & 0x0200) == 0 )); then
      echo '{"status": "success", "ready": true}'
    else
      echo '{"status": "success", "ready": false}'
    fi
    ;;
  *)
    echo "{\"message\": \"Rackmon output: $output\", \"status\": \"error\"}"
    exit 1
    ;;
esac
