#!/bin/bash

# ARGUMENTS:
# 1: RPU unique device address
# 2: Command

if [ $# -lt 2 ]; then
    echo "Usage: $0 <rpu_uda> <command>
      rpu_uda: The RPU unique device address
      command: The command to execute on the device: start, stop, restart, clear-sticky-registers"
    exit 1
fi

# unique device address
UDA="$1"

COMMAND="$2"

systemctl start "rpu@$UDA:$COMMAND.service"
code=$?
journalctl -I -o short -u "rpu@$UDA:$COMMAND.service"
exit $code
