#!/bin/bash

# Check the presence of NIC to determine wether to wait for MAC address ready.
if [[ "$(i2cdetect -y 8 | grep 32 2>/dev/null)" == "" ]]; then
    exit
fi

MAC_ASSIGN_FILE="/sys/class/net/$1/addr_assign_type"
for _ in {1..30}; do
    MAC_ASSIGN_TYPE=$(cat "$MAC_ASSIGN_FILE")
    if [ "$MAC_ASSIGN_TYPE" = "3" ]; then
        break;
    fi
    sleep 1
done
