// Expander error codes are defined in document "OpenBMC_GrandCanyon_Spec_v0.3 3.3.14.2"
char *exp_error_code_description[] = {
	// Error Code 0 is no error
	"Expander I2C bus 0 crash", // Error Code 1
	"Expander I2C bus 1 crash",
	"Expander I2C bus 2 crash",
	"Expander I2C bus 3 crash",
	"Expander I2C bus 4 crash",
	"Expander I2C bus 5 crash",
	"Expander I2C bus 6 crash",
	"Expander I2C bus 7 crash",
	"Expander I2C bus 8 crash",
	"Expander I2C bus 9 crash",  // Error Code 10
	"Expander I2C bus 10 crash",
	"Expander I2C bus 11 crash",
	"Fan 1 front fault",
	"Fan 1 rear fault",
	"Fan 2 front fault",
	"Fan 2 rear fault",
	"Fan 3 front fault",
	"Fan 3 rear fault",
	"Fan 4 front fault",
	"Fan 4 rear fault",  // Error Code 20
	"SCC voltage warning",
	"DPB voltage warning",
	"Expander Reserved",
	"Expander Reserved",
	"SCC current warning",
	"DPB current warning",
	"SCC_I2C_device_loss",
	"DPB_I2C_device_loss",
	"DPB_Temp1",
	"DPB_Temp2",  // Error Code 30
	"SCC_Expander_Temp",
	"SCC_IOC_Temp",
	"HDD X SMART temp. warning",
	"Front_Panel_I2C_device_loss",
	"Reserved",
	"HDD0 fault",
	"HDD1 fault",
	"HDD2 fault",
	"HDD3 fault",
	"HDD4 fault",  // Error Code 40
	"HDD5 fault",
	"HDD6 fault",
	"HDD7 fault",
	"HDD8 fault",
	"HDD9 fault",
	"HDD10 fault",
	"HDD11 fault",
	"HDD12 fault",
	"HDD13 fault",
	"HDD14 fault",  // Error Code 50
	"HDD15 fault",
	"HDD16 fault",
	"HDD17 fault",
	"HDD18 fault",
	"HDD19 fault",
	"HDD20 fault",
	"HDD21 fault",
	"HDD22 fault",
	"HDD23 fault",
	"HDD24 fault",  // Error Code 60
	"HDD25 fault",
	"HDD26 fault",
	"HDD27 fault",
	"HDD28 fault",
	"HDD29 fault",
	"HDD30 fault",
	"HDD31 fault",
	"HDD32 fault",
	"HDD33 fault",
	"HDD34 fault",  // Error Code 70
	"HDD35 fault",
	"HDD X fault sensed",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",  // Error Code 80
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"Fan1 Plug Out",
	"Fan2 Plug Out",
	"Fan3 Plug Out",
	"Fan4 Plug Out",
	"Internal Mini-SAS link error",  // Error Code 90
	"Internal Mini-SAS link error",
	"Drawer be pulled out",
	"Peer SCC be plug out",
	"UICA be plug out",
	"UICB be plug out",
	"Expander Reserved",
	"Expander Reserved",
	"Expander Reserved",
	"H/W Configuration/Type Not Match",  // Error Code 99
};

// BMC error codes are defined in document "GrandCanyon_BMC_Feature_List_v0.6 - Events"
char *bmc_error_code_description[] = {
	"BMC CPU Utilization exceeded",  // Error Code 0xCE
	"BMC Memory Utilization exceeded",
	"BMC Reserved", // Error Code 0xD0
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved", // Error Code 0xDA
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"BMC Reserved",
	"ECC Recoverable Error",  // Error Code 0xE0
	"ECC Un-recoverable Error",
	"Barton Springs Missing",
	"SCC Missing",
	"NIC Missing",
	"E1.S Missing",
	"IOC Module Missing",
	"BMC I2C bus 0 hang",
	"BMC I2C bus 1 hang",
	"BMC I2C bus 2 hang",
	"BMC I2C bus 3 hang",  // Error Code 0xEA
	"BMC I2C bus 4 hang",
	"BMC I2C bus 5 hang",
	"BMC I2C bus 6 hang",
	"BMC I2C bus 7 hang",
	"BMC I2C bus 8 hang",
	"BMC I2C bus 9 hang",  // Error Code 0xF0
	"BMC I2C bus 10 hang",
	"BMC I2C bus 11 hang",
	"BMC I2C bus 12 hang",
	"BMC I2C bus 13 hang",
	"BMC I2C bus 14 hang",
	"BMC I2C bus 15 hang",
	"Server health is bad",
	"UIC health is bad",
	"DPB health is bad",
	"SCC health is bad",  // Error Code 0xFA
	"NIC health is bad",
	"BMC remote heartbeat is abnormal",
	"SCC local heartbeat is abnormal",
	"SCC remote heartbeat is abnormal",
	"BMC Reserved", // Error Code 0xFF
};
