#!/bin/bash

jq --raw-output '["address","type","mode","baudrate","crcErrors","timeouts","miscErrors"],
  (.[] |
    [.devAddress, .deviceType, .mode, .baudrate, .crcErrors, .timeouts, .miscErrors]) | @tsv'
