#!/bin/sh
#
# Copyright 2014-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#

RESTART_NTPD=0
for ntp in $new_ntp_servers $new_dhcp6_sntp_servers; do
  if [ ! -z "$ntp" ]; then
    echo NTP Server: $ntp
    if ! grep "^server.*$ntp" /etc/ntp.conf > /dev/null; then
      echo "server $ntp" >> /etc/ntp.conf
      RESTART_NTPD=1
    fi
  fi
done

[ $RESTART_NTPD -eq 1 ] && /etc/init.d/ntpd restart
