# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "netlakenext"
BBFILE_PATTERN_netlakenext = "^${LAYERDIR}/"
BBFILE_PRIORITY_netlakenext = "20"

LAYERSERIES_COMPAT_netlakenext = "kirkstone honister dunfell"
