#!/bin/bash
set -e

slot=$1
eid=$((10 * slot))

versions=$(
    pldmtool fw_update GetFwParams -m $eid |
    jq --raw-output '
        .ComponentParameterEntries |
        map({ (.ComponentIdentifier|tostring): .ActiveComponentVersionString}) |
        add
    '
)

version_pvddcr_cpu1=$(jq --raw-output ".\"1\"" <<< "$versions")
version_pvdd11_s3=$(jq --raw-output ".\"2\"" <<< "$versions")
version_pvddcr_cpu0=$(jq --raw-output ".\"3\"" <<< "$versions")
version_retimer_x16=$(jq --raw-output ".\"4\"" <<< "$versions")
version_retimer_x8=$(jq --raw-output ".\"5\"" <<< "$versions")

busctl set-property \
    xyz.openbmc_project.Settings \
    "/xyz/openbmc_project/software/host$slot/Sentinel_Dome_vr_pvddcr_cpu0" \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version_pvddcr_cpu0"

busctl set-property \
    xyz.openbmc_project.Settings \
    "/xyz/openbmc_project/software/host$slot/Sentinel_Dome_vr_pvddcr_cpu1" \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version_pvddcr_cpu1"

busctl set-property \
    xyz.openbmc_project.Settings \
    "/xyz/openbmc_project/software/host$slot/Sentinel_Dome_vr_pvdd11_s3" \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version_pvdd11_s3"

busctl set-property \
    xyz.openbmc_project.Settings \
    "/xyz/openbmc_project/software/host$slot/Sentinel_Dome_retimer_x8" \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version_retimer_x8"

busctl set-property \
    xyz.openbmc_project.Settings \
    "/xyz/openbmc_project/software/host$slot/Sentinel_Dome_retimer_x16" \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version_retimer_x16"
