#!/bin/bash
set -e

slot=$1
eid=$((10 * slot + 2))

if ! busctl get-property \
        au.com.codeconstruct.MCTP1 "/au/com/codeconstruct/mctp1/networks/1/endpoints/$eid" \
        xyz.openbmc_project.MCTP.Endpoint EID --timeout=120 2>&1; then
    echo "WF not active"
    exit
fi
wf_fru=$(
    busctl get-property \
        xyz.openbmc_project.EntityManager "/xyz/openbmc_project/inventory/system/board/Yosemite_4_Wailua_Falls_Slot_$slot" \
        xyz.openbmc_project.Inventory.Decorator.Asset Model --timeout=120 2>&1
)
if [[ "$wf_fru" == *"without ASIC"* ]]; then
    echo "Slot $slot does not have ASIC"
    exit
fi

MAX_RETRIES=3
RETRY_COUNT=0
version_pvddq_ab_asic1=""
version_pvddq_cd_asic1=""
version_pvddq_ab_asic2=""
version_pvddq_cd_asic2=""
# The MUX will be switch to WF BIC when CXL ready.
sleep 60

while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
    versions=$(
        pldmtool fw_update GetFwParams -m $eid |
        jq --raw-output '
            .ComponentParameterEntries |
            map({ (.ComponentIdentifier|tostring): .ActiveComponentVersionString}) |
            add
        '
    )

    version_pvddq_ab_asic1=$(jq --raw-output ".\"1\"" <<< "$versions")
    version_pvddq_cd_asic1=$(jq --raw-output ".\"2\"" <<< "$versions")
    version_pvddq_ab_asic2=$(jq --raw-output ".\"3\"" <<< "$versions")
    version_pvddq_cd_asic2=$(jq --raw-output ".\"4\"" <<< "$versions")

    if [ -n "$version_pvddq_ab_asic1" ] && [ -n "$version_pvddq_cd_asic1" ] && [ -n "$version_pvddq_ab_asic2" ] && [ -n "$version_pvddq_cd_asic2" ]; then
        if [ "$version_pvddq_ab_asic1" != "ERROR:0" ]; then
            busctl set-property \
                xyz.openbmc_project.Settings \
                "/xyz/openbmc_project/software/host$slot/Wailua_Falls_vr_pvddq_ab_asic1" \
                xyz.openbmc_project.Software.Version \
                Version "s" "$version_pvddq_ab_asic1" --timeout=120 2>&1
        fi

        if [ "$version_pvddq_cd_asic1" != "ERROR:0" ]; then
            busctl set-property \
                xyz.openbmc_project.Settings \
                "/xyz/openbmc_project/software/host$slot/Wailua_Falls_vr_pvddq_cd_asic1" \
                xyz.openbmc_project.Software.Version \
                Version "s" "$version_pvddq_cd_asic1" --timeout=120 2>&1
        fi

        if [ "$version_pvddq_ab_asic2" != "ERROR:0" ]; then
            busctl set-property \
                xyz.openbmc_project.Settings \
                "/xyz/openbmc_project/software/host$slot/Wailua_Falls_vr_pvddq_ab_asic2" \
                xyz.openbmc_project.Software.Version \
                Version "s" "$version_pvddq_ab_asic2" --timeout=120 2>&1
        fi

        if [ "$version_pvddq_cd_asic2" != "ERROR:0" ]; then
            busctl set-property \
                xyz.openbmc_project.Settings \
                "/xyz/openbmc_project/software/host$slot/Wailua_Falls_vr_pvddq_cd_asic2" \
                xyz.openbmc_project.Software.Version \
                Version "s" "$version_pvddq_cd_asic2" --timeout=120 2>&1
        fi

        if [ "$version_pvddq_ab_asic1" != "ERROR:0" ] && [ "$version_pvddq_cd_asic1" != "ERROR:0" ] && [ "$version_pvddq_ab_asic2" != "ERROR:0" ] && [ "$version_pvddq_cd_asic2" != "ERROR:0" ]; then
            break
        else
            echo "Version is ERROR, retrying... ($((RETRY_COUNT + 1))/$MAX_RETRIES)"
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep 5
        fi
    else
        echo "Version is empty, retrying... ($((RETRY_COUNT + 1))/$MAX_RETRIES)"
        RETRY_COUNT=$((RETRY_COUNT + 1))
        sleep 5
    fi
done
