#!/bin/bash

source /usr/libexec/fb-common-functions

rev_id_1=$(get_gpio "MB_REV_ID_1")
rev_id_2=$(get_gpio "MB_REV_ID_2")

if [ "$rev_id_1" -eq 0 ] && [ "$rev_id_2" -eq 0 ]; then
    hub_devices=$(i2cdetect -l | grep "hub0-" | grep "\.port2")
    target_device=$(echo "$hub_devices" | sed -n '2p')
else
    hub_devices=$(i2cdetect -l | grep "hub2-" | grep "\.port2")
    target_device=$(echo "$hub_devices" | head -n 1)
fi

if [[ -z "$target_device" ]]; then
    echo "Failed to find target device"
    exit 1
fi

i2c_num=$(echo "$target_device" | awk '{print $1}' | cut -d'-' -f2)
eid=$(mctp route | grep "mctpi2c$i2c_num" | grep -oE "eid min [0-9]+" | awk '{print $3}' | head -n1)

if [[ -z "$eid" ]]; then
    echo "Failed to find EID for i2c$i2c_num"
    exit 1
fi

dbus_path="swb_pcie_switch"

echo "Getting version (EID=$eid)"

MAX_RETRIES=10
RETRY_COUNT=0
version=""

while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
    version=$(pldmtool fw_update GetFwParams -m "$eid" 2>/dev/null | \
            jq -r '.ActiveComponentImageSetVersionString' 2>/dev/null)
    if [ -n "$version" ] && [ "$version" != "null" ]; then
        echo "Version: $version"
        
        busctl set-property xyz.openbmc_project.Settings \
            "/xyz/openbmc_project/software/chassis/$dbus_path" \
            xyz.openbmc_project.Software.Version Version "s" "$version"
        
        break
    else
        echo "Version is empty, retrying... ($((RETRY_COUNT + 1))/$MAX_RETRIES)"
        RETRY_COUNT=$((RETRY_COUNT + 1))
        sleep 5
    fi
done
