#!/bin/bash

declare -A RAINBOW_MMC_CONFIG=(
    [0]="10:rainbow0_mmc"
    [1]="20:rainbow1_mmc" 
    [2]="30:rainbow2_mmc"
    [3]="40:rainbow3_mmc"
)

rainbow_mmc_index=$1
config=${RAINBOW_MMC_CONFIG[$rainbow_mmc_index]}
eid=${config%:*}
dbus_path=${config#*:}

echo "Getting Rainbow-mmc$rainbow_mmc_index version (EID=$eid)"

MAX_RETRIES=3
RETRY_COUNT=0
version=""

while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
    version=$( pldmtool fw_update GetFwParams -m "$eid" 2>/dev/null | \
               jq -r '.ActiveComponentImageSetVersionString' 2>/dev/null )

    if [ -n "$version" ] && [ "$version" != "null" ]; then
        echo "Rainbow$rainbow_mmc_index version: $version"
        
        busctl set-property xyz.openbmc_project.Settings \
            "/xyz/openbmc_project/software/chassis/$dbus_path" \
            xyz.openbmc_project.Software.Version Version "s" "$version"
        
        break
    else
        echo "Version is empty, retrying... ($((RETRY_COUNT + 1))/$MAX_RETRIES)"
        RETRY_COUNT=$((RETRY_COUNT + 1))
        sleep 5
    fi
done