# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qemu-git"
BBFILE_PATTERN_qemu-git = "^${LAYERDIR}/"
BBFILE_PRIORITY_qemu-git = "20"

LAYERSERIES_COMPAT_qemu-git = "walnascar whinlatter styhead scarthgap nanbield kirkstone dunfell"
