# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "grandcanyon2"
BBFILE_PATTERN_grandcanyon2 = "^${LAYERDIR}/"
BBFILE_PRIORITY_grandcanyon2 = "25"

LAYERSERIES_COMPAT_grandcanyon2 = "whinlatter walnascar styhead scarthgap nanbield kirkstone dunfell"

# Mask conflicting configuration from parent layer
BBMASK += "meta-grandcanyon/recipes-grandcanyon/fscd/"
