#!/bin/bash
#
# Copyright 2018-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#

kv_type2flags() {
  local flags
  flags="0"
  if [[ "$type" == *persistent* ]]; then
    flags="$flags | kv.FPERSIST"
  fi
  if [[ "$type" == *create* ]]; then
    flags="$flags | kv.FCREATE"
  fi
  echo $flags
}

kv_get() {
  local key type flags
  key=$1
  type=$2
  flags=$(kv_type2flags $type)
  /usr/bin/python -c "import kv; print(kv.kv_get(\"$key\", flags=$flags), end=\"\")" 2> /dev/null
}

kv_set() {
  local key value type flags
  key=$1
  value=$2
  type=$3
  flags=$(kv_type2flags $type)
  /usr/bin/python -c "import kv; kv.kv_set(\"$key\", \"$value\", flags=$flags)" 2> /dev/null
  return $?
}

if [[ "$0" == "${BASH_SOURCE[0]}"  ]]; then
  if [[ "$1" == "get"  ]]; then
    val=$(kv_get "$2" "$3")
    echo -n "$val"
    exit 0
  elif [[ "$1" == "set"  ]]; then
    kv_set "$2" "$3" "$4"
    if [ "$?" != 0 ]; then
      echo "kv_set failed"
      exit -1
    fi
    exit 0
  fi
  exit -1
fi
