#!/bin/sh
#
# Copyright 2020-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#

usage() {
  echo "Usage: sol-util server"
  echo "       sol-util server bic"
  echo "       sol-util scc [ exp_smart | exp_sdb | ioc_smart | ioc_sdb]"
  echo "       sol-util iocm [ ioc_smart | ioc_sdb]"
  echo "       sol-util server --history"
  exit -1
}

OPTION_NAME=("bmc" "server" "bic" "scc_exp_smart" "scc_exp_sdb" "scc_ioc_smart" "scc_ioc_sdb" "iocm")

# if mTerm server is running use mTerm_client to connect to userver
# otherwise fallback to the old method

# The default ID is set to server
UART_SEL_ID=1

if [ "$1" == "server" ]; then
  if [ $# -gt 1 ]; then 
	if [ "$2" == "bic" ]; then 
	  UART_SEL_ID=2
	else
	  usage
	fi  
  else
	UART_SEL_ID=1
  fi
elif [ "$1" == "scc" ]; then
    case "$2" in
	  exp_smart) UART_SEL_ID=3
	             ;;
	  exp_sdb) UART_SEL_ID=4
	           ;;
	  ioc_smart) UART_SEL_ID=5
	             ;;
	  ioc_sdb) UART_SEL_ID=6
	           ;;
      *) usage
	esac
elif [ "$1" == "iocm" ]; then
    echo "For now, should manual send I2C command to UIC FPGA to select the UART MUX of IOC Module"
    UART_SEL_ID=7
    case "$2" in
	  ioc_smart) # TODO: add command to select MUX
                     ;;
	  ioc_sdb) # TODO: add command to select MUX
	           ;;
      *) usage
	esac
else
  usage
fi

exec /usr/local/bin/mTerm_client ${OPTION_NAME[$UART_SEL_ID]}

echo
echo
echo "-----------------------"
echo "Exit from SOL session."
