#!/bin/sh
#
# Copyright 2020-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#

usage() {
  echo "Usage: sol-util server"
  echo "       sol-util server bic"
  echo "       sol-util scc [ exp_smart | exp_sdb | ioc_smart | ioc_sdb] (baud rate)"
  echo "       sol-util iocm [ ioc_smart | ioc_sdb]"
  echo "       sol-util server --history"
  exit -1
}


#                   BMC   Server   BIC   SCC Expander Smart   SCC Expander SDB   SCC IOC T5 Smart   SCC IOC T5 SDB   IOC T7
#---------------------------------------------------------------------------------------------------------------------------------
#UART select ID     0     1        2     3                    4                  5                  6                7
#tty serial number  0     5        7     1                    2                  3                  6                8
#option name        bmc   server   bic   scc_exp_smart        scc_exp_sdb        scc_ioc_smart      scc_ioc_sdb      iocm_ioc_smart

TTY_LIST=(0 5 7 1 2 3 6 8)
OPTION_NAME=("bmc" "server" "bic" "scc_exp_smart" "scc_exp_sdb" "scc_ioc_smart" "scc_ioc_sdb" "iocm")

# if mTerm server is running use mTerm_client to connect to userver
# otherwise fallback to the old method

# The default ID is set to server
UART_SEL_ID=1

if [ "$1" == "server" ]; then
  if [ $# -gt 1 ]; then 
    if [ "$2" == "bic" ]; then 
      UART_SEL_ID=2
    else
      usage
    fi  
  else
    UART_SEL_ID=1
  fi
elif [ "$1" == "scc" ]; then
  case "$2" in
    exp_smart) UART_SEL_ID=3
    ;;
    exp_sdb) UART_SEL_ID=4
    ;;
    ioc_smart) UART_SEL_ID=5
    ;;
    ioc_sdb) UART_SEL_ID=6
    ;;
    *) usage
  esac

  # Set back to default baud rate 57600
  /bin/stty -F /dev/ttyS${TTY_LIST[$UART_SEL_ID]} 57600 >/dev/null 2>&1

  if [ $# -eq 3 ]; then
    baud=$3
      /bin/stty -F /dev/ttyS${TTY_LIST[$UART_SEL_ID]} $baud >/dev/null 2>&1
      if [ $? -ne 0 ]; then
        usage
      fi
  elif [ $# -gt 3 ]; then
    usage
  fi
elif [ "$1" == "iocm" ]; then
  echo "For now, should manual send I2C command to UIC FPGA to select the UART MUX of IOC Module"
  UART_SEL_ID=7
  case "$2" in
    ioc_smart) # TODO: add command to select MUX
    ;;
    ioc_sdb) # TODO: add command to select MUX
    ;;
    *) usage
  esac
else
  usage
fi

exec /usr/local/bin/mTerm_client ${OPTION_NAME[$UART_SEL_ID]}

echo
echo
echo "-----------------------"
echo "Exit from SOL session."
