#!/bin/sh
#
# Copyright 2015-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#
# THIS FILE MUST BE OVERRIDDEN BY THE PLATFORM WITH THE APPROPRIATE PARAMETERS.
# BELOW IS PROVIDED AS AN EXAMPLE ONLY.
# THE PLATFORM MAY CHOOSE TO HAVE MULTIPLE OF THESE FILES AND IF IT DOES,
# THE mTerm_0.1.bbappend must override MTERM_SERVICES to provide the appropriate
# directory names
# exec /usr/local/bin/mTerm_server mb /dev/ttyS1

