swagger: "2.0"
info: 
  description: Swagger doc for /api/server2/sensors  
  title: Swagger doc for /api/server2/sensors  
  version: 1.0.0
paths: 
  /api/server2/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  MB_INLET_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_OUTLET_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  FIO_FRONT_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_PCH_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_SOC_CPU_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_SOC_THERMAL_MARGIN_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_SOC_TJMAX_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA0_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA2_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA3_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA4_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA6_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA7_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_SSD0_M2A_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_VCCIN_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_FIVRA_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_EHV_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_VCCD_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_FAON_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P12V_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P3V_BAT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P3V3_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P1V8_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P1V05_PCH_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P5V_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P12V_DIMM_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P1V2_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P3V3_M2_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_INPUT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_VCCIN_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_FIVRA_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_EHV_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_VCCD_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_FAON_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_OUTPUT_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_VCCIN_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_FIVRA_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_EHV_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_VCCD_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_FAON_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_SOC_PACKAGE_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_INPUT_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_VCCIN_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_FIVRA_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_EHV_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_VCCD_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_FAON_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA0_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA2_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA3_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA4_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA6_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA7_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_OUTLET_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_P12V_AUX_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_P12V_EDGE_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_P3V3_AUX_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_P1V2_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD0_PWR_WATT_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD0_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD0_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD0_3V3_ADC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD0_12V_ADC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD1_PWR_WATT_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD1_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD1_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD1_3V3_ADC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD1_12V_ADC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD2_PWR_WATT_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD2_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD2_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD2_3V3_ADC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD2_12V_ADC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD3_PWR_WATT_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD3_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD3_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD3_3V3_ADC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VF_E1S_SSD3_12V_ADC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            