swagger: '2.0'
info:
  description: Swagger doc for /api/scc/sensors
  title: Swagger doc for /api/scc/sensors
  version: 1.0.0
paths:
  /api/scc/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  SCC_EXP_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_IOC_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_TEMP_1:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_TEMP_2:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_P3V3_E_SENSE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_P1V8_E_SENSE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_P1V5_E_SENSE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_P0V92_E_SENSE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_P1V8_C_SENSE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_P1V5_C_SENSE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_P0V865_C_SENSE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_HSC_P12V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_HSC_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCC_HSC_PWR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
