#!/usr/bin/env python2

#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under the BSD-style license found in the
#  LICENSE file in the root directory of this source tree. An additional grant
#  of patent rights can be found in the PATENTS file in the same directory.

import argparse
import jinja2
import os
import sys
import time
import tempfile

from Crypto.PublicKey import RSA
from Crypto.Util import number
from distutils import spawn

def genWords(bits, num):
    words = []
    b2_32 = 2 ** 32L
    for i in xrange(bits / 32):
        n = num % b2_32
        words.insert(0, "0x%x" % n)
        num = num >> 32
    return words

def genKey(name, filename):

    #print("Reading public key: %s" % filename)
    with open(filename, 'rU') as fh:
        pubkey_data = fh.read()
    pubkey = RSA.importKey(pubkey_data)

    # Only support 2048 or 4096 bit keys
    size = number.size(pubkey.n)
    if size < 2000:
        print("Error: Key size is: %d" % pubkey.size())
        sys.exit(1)

    key = {}
    key["name"] = name
    key["size"] = "%s" % size
    key["bits"] = "0x%x" % size

    # Here be dragons, this really doesn't handle a u64.
    key["exponent"] = "0x0 0x%x" % pubkey.e

    b2_32 = 2 ** 32L
    n0_invp = (number.inverse(pubkey.n, b2_32) - b2_32) * -1
    key["n0inverse"] = "0x%x" % n0_invp

    modulus = pubkey.n
    key["modulus"] = " ".join(genWords(size, modulus))

    r = 2 ** size
    r_squared = (r * r) % modulus
    key["rsquared"] = " ".join(genWords(size, r_squared))
    return key


def decompileSource(filename):
    with tempfile.NamedTemporaryFile() as tmp:
        spawn.spawn(
            [dtc, "-I", "dtb", "-O", "dts", "-o", tmp.name, filename])
        with open(tmp.name) as fh:
            source = fh.read()
    return source

def compileSource(source, output, s=1):
    with tempfile.NamedTemporaryFile() as tmp:
        tmp.write(source)
        tmp.flush()
        spawn.spawn(
            [dtc, "-I", "dts", "-O", "dtb", "-o", output, tmp.name])
    print("Wrote certificate store DTB (%d keys): %s" % (s, output))


def buildKeySource(td, keys, output=None):
    now = hex(int(time.time()))
    source = jinja2.Template(td).render(keys=keys,
        algorithm=args.algorithm, node=args.required_node,
        extendable=args.allow_extending, now=now)
    if output is None:
        return source
    compileSource(source, output, len(keys))
    return source


def main(args):
    with open(args.template, "rU") as fh:
        template_data = fh.read()

    keys = []
    for base, _, filenames in os.walk(args.keys):
        for filename in filenames:
            key_name, extension = os.path.splitext(filename)
            if extension != "." + args.ext:
                continue
            keys.append(genKey(os.path.basename(key_name),
                os.path.join(base, filename)))

    if args.subordinate:
        with open(args.subtemplate, "rU") as fh:
            sub_template_data = fh.read()

        with tempfile.NamedTemporaryFile(delete=False) as tmp:
            buildKeySource(template_data, keys, tmp.name)
            stores = [{"i": 1, "tempdata": tmp.name}]
            source = jinja2.Template(sub_template_data).render(stores=stores)
            with tempfile.NamedTemporaryFile() as tmp2:
                compileSource(source,
                    tmp2.name if args.no_out else args.output, len(stores))
                if args.no_out:
                    source = decompileSource(tmp2.name)
                    print(source)
        return 0

    source = buildKeySource(template_data,
        keys, None if args.no_out else args.output)
    if args.no_out:
        print(source)
    return 0

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Generate a FIT certificate store (a DTB).")
    parser.add_argument("keys", metavar="DIRECTORY",
        help="Path to directory containing public keys")
    parser.add_argument("output", nargs='?', metavar="OUTPUT_DTB", default='',
        help="Output path of compiled certificate store (dtb)")

    parser.add_argument("--ext", default="pub", metavar="pub",
        help="Search for public keys with this file extension")
    parser.add_argument("--template", default="store.dts.in", metavar="PATH",
        help="Certificate store template")
    parser.add_argument("--no-out", default=False, action="store_true",
        help="Print the resultant source instead of compiling")
    parser.add_argument("--algorithm", default="sha256", metavar="sha256",
        help="Override default hashing algorithm")
    parser.add_argument("--required-node", default="auto", metavar="conf",
        help="Set the required node (default=auto)")
    parser.add_argument("--allow-extending", default=False, action="store_true",
        help="Generate a cert store with keys=true")
    parser.add_argument("--subordinate", default=False, action="store_true",
        help="Generate a subordinate certificate store")
    parser.add_argument("--subtemplate", default="sub.dts.in", metavar="PATH",
        help="Subordinate certificate store template")
    args = parser.parse_args()

    if args.required_node == 'auto':
        if args.subordinate:
            args.required_node = 'conf'
        else:
            args.required_node = 'image'

    if not args.no_out and args.output == '':
        print("Either provide an OUTPUT_DTB or use --no-out")
        sys.exit(1)
    if not os.path.exists(args.template):
        print("Cannot find template input: %s" % args.template)
        sys.exit(1)
    if args.subordinate and not os.path.exists(args.subtemplate):
        print("Cannot find subordinate template input: %s" % args.subtemplate)
        sys.exit(1)
    if not os.path.exists(args.keys):
        print("Cannot find key directory: %s" % args.keys)
        sys.exit(1)

    dtc = spawn.find_executable('dtc')
    if dtc == '':
        print("Cannot find 'dtc' in your path")
        sys.exit(1)

    sys.exit(main(args))
