#ifndef __PAL_MEB_SENSORS_H__
#define __PAL_MEB_SENSORS_H__

#include "pal_sensors.h"
#include <libpldm/base.h>
#include <libpldm/platform.h>

#define JCN_CONFIG_STR_CXL "cxl"
#define JCN_CONFIG_STR_E1S "e1s"
#define JCN_CONFIG_STR_NIC "nic"

#define MEB_MP5990_DEVICE_NAME "mp5990"
#define MEB_MP5990_BIND_DIR    "/sys/bus/i2c/drivers/mp5990/70-0040"
#define MEB_MP5990_BUS         70
#define MEB_MP5990_ADDR        0x40

// MEB sensor table
enum {
  MEB_SENSOR_INLET_TEMP = 1,
  MEB_SENSOR_OUTLET_TEMP,
  MEB_SENSOR_PU4_TEMP,
  MEB_SENSOR_P12V_AUX_VOL,
  MEB_SENSOR_P3V3_AUX_VOL,
  MEB_SENSOR_P1V2_AUX_VOL,
  MEB_SENSOR_P3V3_VOL,
  MEB_SENSOR_P12V_AUX_CXL8_VOL,
  MEB_SENSOR_P12V_AUX_CXL7_VOL,
  MEB_SENSOR_P12V_AUX_CXL6_VOL,
  MEB_SENSOR_P12V_AUX_CXL5_VOL,
  MEB_SENSOR_P12V_AUX_SSD4_VOL,
  MEB_SENSOR_P12V_AUX_SSD3_VOL,
  MEB_SENSOR_P12V_AUX_SSD2_VOL,
  MEB_SENSOR_P12V_AUX_SSD1_VOL,
  MEB_SENSOR_P12V_AUX_CXL3_VOL,
  MEB_SENSOR_P12V_AUX_CXL4_VOL,
  MEB_SENSOR_P12V_AUX_CXL1_VOL,
  MEB_SENSOR_P12V_AUX_CXL2_VOL,
  MEB_SENSOR_P12V_AUX_SW_4C_2_VOL,
  MEB_SENSOR_P12V_AUX_SW_4C_1_VOL,
  MEB_SENSOR_P12V_AUX_CUR,
  MEB_SENSOR_P12V_AUX_CXL8_CUR,
  MEB_SENSOR_P12V_AUX_CXL7_CUR,
  MEB_SENSOR_P12V_AUX_CXL6_CUR,
  MEB_SENSOR_P12V_AUX_CXL5_CUR,
  MEB_SENSOR_P12V_AUX_SSD4_CUR,
  MEB_SENSOR_P12V_AUX_SSD3_CUR,
  MEB_SENSOR_P12V_AUX_SSD2_CUR,
  MEB_SENSOR_P12V_AUX_SSD1_CUR,
  MEB_SENSOR_P12V_AUX_CXL3_CUR,
  MEB_SENSOR_P12V_AUX_CXL4_CUR,
  MEB_SENSOR_P12V_AUX_CXL1_CUR,
  MEB_SENSOR_P12V_AUX_CXL2_CUR,
  MEB_SENSOR_P12V_AUX_SW_4C_2_CUR,
  MEB_SENSOR_P12V_AUX_SW_4C_1_CUR,
  MEB_SENSOR_P12V_AUX_PWR,
  MEB_SENSOR_P12V_AUX_CXL8_PWR,
  MEB_SENSOR_P12V_AUX_CXL7_PWR,
  MEB_SENSOR_P12V_AUX_CXL6_PWR,
  MEB_SENSOR_P12V_AUX_CXL5_PWR,
  MEB_SENSOR_P12V_AUX_SSD4_PWR,
  MEB_SENSOR_P12V_AUX_SSD3_PWR,
  MEB_SENSOR_P12V_AUX_SSD2_PWR,
  MEB_SENSOR_P12V_AUX_SSD1_PWR,
  MEB_SENSOR_P12V_AUX_CXL3_PWR,
  MEB_SENSOR_P12V_AUX_CXL4_PWR,
  MEB_SENSOR_P12V_AUX_CXL1_PWR,
  MEB_SENSOR_P12V_AUX_CXL2_PWR,
  MEB_SENSOR_P12V_AUX_SW_4C_2_PWR,
  MEB_SENSOR_P12V_AUX_SW_4C_1_PWR,
  MEB_SENSOR_E1S_0_TEMP,
  MEB_SENSOR_E1S_1_TEMP,
  MEB_SENSOR_E1S_2_TEMP,
  MEB_SENSOR_E1S_3_TEMP,
};

enum {
  CXL_SENSOR_Inlet_TEMP = 1,
  CXL_SENSOR_CTRL_TEMP,
  CXL_SENSOR_P12V_STBY_4CP_VOL,
  CXL_SENSOR_P3V3_STBY_4CP_VOL,
  CXL_SENSOR_P5V_STBY_VOL,
  CXL_SENSOR_P1V8_ASIC_VOL,
  CXL_SENSOR_P12V_STBY_VOL,
  CXL_SENSOR_P3V3_STBY_VOL,
  CXL_SENSOR_PVPP_AB_VOL,
  CXL_SENSOR_PVTT_AB_VOL,
  CXL_SENSOR_PVPP_CD_VOL,
  CXL_SENSOR_PVTT_CD_VOL,
  CXL_SENSOR_P0V8_ASICA_VOL,
  CXL_SENSOR_P0V9_ASICA_VOL,
  CXL_SENSOR_P0V8_ASICD_VOL,
  CXL_SENSOR_PVDDQ_AB_VOL,
  CXL_SENSOR_PVDDQ_CD_VOL,
  CXL_SENSOR_P12V_STBY_4CP_CUR,
  CXL_SENSOR_P3V3_STBY_4CP_CUR,
  CXL_SENSOR_P0V8_ASICA_CUR,
  CXL_SENSOR_P0V9_ASICA_CUR,
  CXL_SENSOR_P0V8_ASICD_CUR,
  CXL_SENSOR_PVDDQ_AB_CUR,
  CXL_SENSOR_PVDDQ_CD_CUR,
  CXL_SENSOR_P12V_STBY_4CP_PWR,
  CXL_SENSOR_P3V3_STBY_4CP_PWR,
  CXL_SENSOR_P0V8_ASICA_PWR,
  CXL_SENSOR_P0V9_ASICA_PWR,
  CXL_SENSOR_P0V8_ASICD_PWR,
  CXL_SENSOR_PVDDQ_AB_PWR,
  CXL_SENSOR_PVDDQ_CD_PWR,
  CXL_CTRL_TEMP,
  CXL_DIMM_A_TEMP,
  CXL_DIMM_B_TEMP,
  CXL_DIMM_C_TEMP,
  CXL_DIMM_D_TEMP,
};

enum {
  E1S_SENSOR_E1S_0_TEMP =1,
  E1S_SENSOR_E1S_1_TEMP,
};

#endif
