#ifndef __PAL_HMC_SENSORS_H__
#define __PAL_HMC_SENSORS_H__

enum {
  NONE =0,
  EVT = 1,
  DVT = 2
};

// HMC sensor table
enum {
  //Baseboard
  HMC_SNR_PWR_GB_HSC0 = 0x01,
  HMC_SNR_PWR_GB_HSC1,
  HMC_SNR_PWR_GB_HSC2,
  HMC_SNR_PWR_GB_HSC3,
  HMC_SNR_PWR_GB_HSC4,
  HMC_SNR_PWR_GB_HSC5,
  HMC_SNR_PWR_GB_HSC6,
  HMC_SNR_PWR_GB_HSC7,
  HMC_SNR_PWR_GB_HSC8,
  HMC_SNR_PWR_GB_HSC9,
  HMC_SNR_PWR_GB_HSC10,
  Total_Power,
  Total_GPU_Power,
  Altitude_Pressure0,

  TEMP_GB_FPGA = 0x10,
  TEMP_GB_HSC0,
  TEMP_GB_HSC1,
  TEMP_GB_HSC2,
  TEMP_GB_HSC3,
  TEMP_GB_HSC4,
  TEMP_GB_HSC5,
  TEMP_GB_HSC6,
  TEMP_GB_HSC7,
  TEMP_GB_HSC8,
  TEMP_GB_HSC9,
  TEMP_GB_HSC10,
  TEMP_GB_INLET0,
  TEMP_GB_INLET1,

  TEMP_GB_PCB0 = 0x20,
  TEMP_GB_PCB1,
  TEMP_GB_PCB2,
  TEMP_GB_PCB3,
  TEMP_GB_PCIERETIMER0,
  TEMP_GB_PCIERETIMER1,
  TEMP_GB_PCIERETIMER2,
  TEMP_GB_PCIERETIMER3,
  TEMP_GB_PCIERETIMER4,
  TEMP_GB_PCIERETIMER5,
  TEMP_GB_PCIERETIMER6,
  TEMP_GB_PCIERETIMER7,
  TEMP_GB_PCIESWITCH0,
 
  //GPU0 and GPU1
  EG_GB_GPU0 = 0x30,
  PWR_GB_GPU0,
  PWR_GB_HBM_GPU0,
  TEMP_GB_GPU0,
  TEMP_GB_GPU0_M,
  VOLT_GB_GPU0,
  EG_GB_GPU1,
  PWR_GB_GPU1,
  PWR_GB_HBM_GPU1,
  TEMP_GB_GPU1,
  TEMP_GB_GPU1_M,
  VOLT_GB_GPU1,

  //GPU2 and GPU3
  EG_GB_GPU2 =0x40,
  PWR_GB_GPU2,
  PWR_GB_HBM_GPU2,
  TEMP_GB_GPU2,
  TEMP_GB_GPU2_M,
  VOLT_GB_GPU2,
  EG_GB_GPU3,
  PWR_GB_GPU3,
  PWR_GB_HBM_GPU3,
  TEMP_GB_GPU3,
  TEMP_GB_GPU3_M,
  VOLT_GB_GPU3,

  //GPU4 and GPU5
  EG_GB_GPU4 = 0x50,
  PWR_GB_GPU4,
  PWR_GB_HBM_GPU4,
  TEMP_GB_GPU4,
  TEMP_GB_GPU4_M,
  VOLT_GB_GPU4,
  EG_GB_GPU5,
  PWR_GB_GPU5,
  PWR_GB_HBM_GPU5,
  TEMP_GB_GPU5,
  TEMP_GB_GPU5_M,
  VOLT_GB_GPU5,

 //GPU6 and GPU7
  EG_GB_GPU6 = 0x60,
  PWR_GB_GPU6,
  PWR_GB_HBM_GPU6,
  TEMP_GB_GPU6,
  TEMP_GB_GPU6_M,
  VOLT_GB_GPU6,
  EG_GB_GPU7,
  PWR_GB_GPU7,
  PWR_GB_HBM_GPU7,
  TEMP_GB_GPU7,
  TEMP_GB_GPU7_M,
  VOLT_GB_GPU7,

  //NV Switch
  TEMP_GB_NVS0 = 0x70,
  TEMP_GB_NVS1,
  TEMP_GB_NVS2,
  TEMP_GB_NVS3,
  HMC_SNR_CNT = 0x7f,
};

#endif
