#ifndef __HAL_PALDEF_COVER_H__
#define __HAL_PALDEF_COVER_H__

//BUS number
#define HSC_BUS_NUM              (2)

#define MAX_DIMM_NUM              (32)
#define MAX_DIMM_CHANNEL          (16)
#define PER_CPU_DIMM_NUMBER_MAX   (MAX_DIMM_NUM/MAX_CPU_CNT)
#define PER_CPU_DIMM_CHANNEL_MAX  (MAX_DIMM_CHANNEL/MAX_CPU_CNT)

//GPIO EVENT Cover
#define IRQ_UV_DETECT_N          "IRQ_UV_DETECT_N"
#define IRQ_OC_DETECT_N          "IRQ_OC_DETECT_N"
#define IRQ_HSC_FAULT_N          "IRQ_HSC_FAULT_N"
#define IRQ_HSC_ALERT_N          "IRQ_SML1_PMBUS_PLD_ALERT_N"
#define FM_CPU0_PROCHOT_N        "H_CPU0_PROCHOT_LVC1_N"
#define FM_CPU1_PROCHOT_N        "H_CPU1_PROCHOT_LVC1_N"
#define FM_CPU0_THERMTRIP_N      "H_CPU0_THERMTRIP_LVC1_N"
#define FM_CPU1_THERMTRIP_N      "H_CPU1_THERMTRIP_LVC1_N"
#define FM_CPU_ERR0_N            "H_CPU_ERR0_LVC2_N"
#define FM_CPU_ERR1_N            "H_CPU_ERR1_LVC2_N"
#define FM_CPU_ERR2_N            "H_CPU_ERR2_LVC2_N"
#define FM_CPU0_MEM_HOT_N        "H_CPU0_MEMHOT_OUT_LVC1_N"
#define FM_CPU1_MEM_HOT_N        "H_CPU1_MEMHOT_OUT_LVC1_N"
#define FM_CPU0_MEM_THERMTRIP_N  "H_CPU0_MEMTRIP_LVC1_N"
#define FM_CPU1_MEM_THERMTRIP_N  "H_CPU1_MEMTRIP_LVC1_N"
#define FM_PCH_HOT_N             "FM_PCHHOT_R_N"
#define FM_PCH_THERMTRIP_N       "FM_PCH_BMC_THERMTRIP_N"
#define FM_SYS_THROTTLE          "FM_SYS_THROTTLE_R_N"
#define FM_CPU0_VCCIN_VR_HOT     "IRQ_CPU0_VRHOT_N"
#define FM_CPU1_VCCIN_VR_HOT     "IRQ_CPU1_VRHOT_N"
#define FM_CPU0_VCCD_VR_HOT      "IRQ_PVCCD_CPU0_VRHOT_LVC3_N"
#define FM_CPU1_VCCD_VR_HOT      "IRQ_PVCCD_CPU1_VRHOT_LVC3_N"
#define FM_CPU0_SKTOCC           "FM_CPU0_SKTOCC_LVT3_PLD_N"
#define FM_CPU1_SKTOCC           "FM_CPU1_SKTOCC_LVT3_PLD_N"
#define FM_BIOS_POST_CMPLT       "FM_BIOS_POST_CMPLT_BMC_N"
#define FM_OCP0_PRSNT            "FM_OCP_SFF_PWR_GOOD_R"
#define FM_OCP1_PRSNT            "FM_OCP_V3_2_PWR_GOOD_R"

//GPIO Power Control Cover
#define FM_LAST_PWRGD            "PWRGD_CPUPWRGD_LVC2_R1"
#define RST_PLTRST_N             "RST_PLTRST_PLD_N"
#define PWRGD_SYS_PWROK          "PWRGD_SYS_PWROK_R"
#define CPLD_SHUT_DOWN_ALERT     "CPLD_SHUT_DOWN_ALERT"
#define BMC_DIMM_SEL_DONE        "BMC_DIMM_SEL_DONE"

//XDP Debug PIN
#define IRQ_BMC_PRDY_N           "FM_DBP_BMC_PRDY_N"
#define DBP_PRESENT_N            "FM_BMC_DBP_PRESENT_R_N"
#define FM_JTAG_TCK_MUX_SEL      "FM_JTAG_TCK_MUX_BMC_SEL" //Choice Jtag to CPU or PCH
#define FM_BMC_PREQ_N            "FM_DBP_CPU_PREQ_GF_N"
#define FM_JTAG_BMC_MUX_SEL      "FM_JTAG_BMC_MUX_SEL" //Choice BMC to CPLD or BMC to CPU/PCH
#define FM_BMC_CPU_PWR_DEBUG_N   "FM_BMC_CPU_FBRK_OUT_N"

#define PEX_FW_VER_UPDATE        "RST_PLTRST_PLD_N"

#endif
