swagger: '2.0'
info:
  description: Swagger doc for /api/sys/sensors/pim3
  title: Swagger doc for /api/sys/sensors/pim3
  version: 1.0.0
paths:
  /api/sys/sensors/pim3:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  name:
                    type: string
                  Adapter:
                    type: string
                  present:
                    type: boolean
                  PIM3_POS_3V3_U_VOUT:
                    type: string
                  PIM3_POS_3V3_U_TEMP:
                    type: string
                  PIM3_POS_3V3_U_CURR:
                    type: string
                  PIM3_POS_3V3_L_VOUT:
                    type: string
                  PIM3_POS_3V3_L_TEMP:
                    type: string
                  PIM3_POS_3V3_L_CURR:
                    type: string
                  PIM3_LM73_TEMP:
                    type: string
                  PIM3_POS_12V:
                    type: string
                  PIM3_POS_3V3_E:
                    type: string
                  PIM3_POS_1V2_E:
                    type: string
                  PIM3_POS_3V3_U:
                    type: string
                  PIM3_POS_3V3_L:
                    type: string
                  PIM3_POS_3V8_LEDS:
                    type: string
                  PIM3_DPM_TEMP:
                    type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
