swagger: '2.0'
info:
  description: Swagger doc for /api/sys/sensors/psu3
  title: Swagger doc for /api/sys/sensors/psu3
  version: 1.0.0
paths:
  /api/sys/sensors/psu3:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  name:
                    type: string
                  Adapter:
                    type: string
                  present:
                    type: boolean
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
