swagger: '2.0'
info:
  description: Swagger doc for /api/sys/sensors/smb
  title: Swagger doc for /api/sys/sensors/smb
  version: 1.0.0
paths:
  /api/sys/sensors/smb:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  name:
                    type: string
                  Adapter:
                    type: string
                  present:
                    type: boolean
                  SMB_POS_0V75_CORE:
                    type: string
                  SMB_POS_0V75_ANLG:
                    type: string
                  SMB_POS_1V2:
                    type: string
                  SMB_POS_1V2_ANLG_L:
                    type: string
                  SMB_POS_1V2_ANLG_R:
                    type: string
                  SMB_POS_1V8:
                    type: string
                  SMB_POS_1V8_ANLG:
                    type: string
                  SMB_POS_3V3:
                    type: string
                  SMB_POS_3V3_DPM:
                    type: string
                  SMB_POS_5V0:
                    type: string
                  SMB_POS_12V_B:
                    type: string
                  SMB_POS_12V_A:
                    type: string
                  SMB_POS_1V2B_E:
                    type: string
                  SMB_POS_2V5B_E:
                    type: string
                  SMB_POS_3V3B_E:
                    type: string
                  TH4_VRD1_VIN:
                    type: string
                  TH4_VRD1_VOUT_LOOP0:
                    type: string
                  TH4_VRD1_TEMP_LOOP0:
                    type: string
                  TH4_VRD1_PIN:
                    type: string
                  TH4_VRD1_POUT_LOOP0:
                    type: string
                  TH4_VRD1_IIN:
                    type: string
                  TH4_VRD1_IOUT_LOOP0:
                    type: string
                  TH4_VRD2_VIN:
                    type: string
                  TH4_VRD2_VOUT_LOOP0:
                    type: string
                  TH4_VRD2_VOUT_LOOP1:
                    type: string
                  TH4_VRD2_VOUT_LOOP2:
                    type: string
                  TH4_VRD2_TEMP_LOOP0:
                    type: string
                  TH4_VRD2_TEMP_LOOP1:
                    type: string
                  TH4_VRD2_TEMP_LOOP2:
                    type: string
                  TH4_VRD2_TEMP_INTERNAL:
                    type: string
                  TH4_VRD2_PIN_LOOP0:
                    type: string
                  TH4_VRD2_PIN_LOOP1:
                    type: string
                  TH4_VRD2_PIN_LOOP2:
                    type: string
                  TH4_VRD2_POUT_LOOP0:
                    type: string
                  TH4_VRD2_POUT_LOOP1:
                    type: string
                  TH4_VRD2_POUT_LOOP2:
                    type: string
                  TH4_VRD2_IIN_LOOP0:
                    type: string
                  TH4_VRD2_IIN_LOOP1:
                    type: string
                  TH4_VRD2_IIN_LOOP2:
                    type: string
                  TH4_VRD2_IOUT_LOOP0:
                    type: string
                  TH4_VRD2_IOUT_LOOP1:
                    type: string
                  TH4_VRD2_IOUT_LOOP2:
                    type: string
                  SMB_T:
                    type: string
                  TH4_DIE_TEMP_0:
                    type: string
                  TH4_DIE_TEMP_1:
                    type: string
                  SMB_R:
                    type: string
                  SMB_U:
                    type: string
                  SMB_L:
                    type: string
                  BLACKHAWK_CORE_0-5_TEMP:
                    type: string
                  BLACKHAWK_CORE_6-12_TEMP:
                    type: string
                  BLACKHAWK_CORE_13-18_TEMP:
                    type: string
                  BLACKHAWK_CORE_19-25_TEMP:
                    type: string
                  BLACKHAWK_CORE_26-31_TEMP:
                    type: string
                  BLACKHAWK_CORE_32-37_TEMP:
                    type: string
                  BLACKHAWK_CORE_38-44_TEMP:
                    type: string
                  BLACKHAWK_CORE_45-50_TEMP:
                    type: string
                  BLACKHAWK_CORE_51-57_TEMP:
                    type: string
                  BLACKHAWK_CORE_58-63_TEMP:
                    type: string
                  CORE_0_TEMP:
                    type: string
                  CORE_1_TEMP:
                    type: string
                  CORE_2_TEMP:
                    type: string
                  CORE_3_TEMP:
                    type: string
                  PIM_QSFP200:
                    type: string
                  PIM_QSFP400:
                    type: string
                  PIM_F104:
                    type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
