#!/bin/bash
#
# Copyright 2018-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

. /usr/local/bin/openbmc-utils.sh

usage() {
    echo "Usage $0 [1..8]"
}

dump_eeprom() {
    local i2c_path=$(i2c_device_sysfs_abspath ${1}-00${2:2:3})
    weutil ${i2c_path}/eeprom
    return $?
}

is_i2cdev_exist() {
    local i2c_path=$(i2c_device_sysfs_abspath ${1}-00${2:2:3})
    weutil ${i2c_path}/eeprom &> /dev/null
    echo $?
}

show_pim_fruid() {
    pim_no=$1
    bus=$(((pim_no-1)*8 + 81))
    addr_16Q=0x56
    addr_4DD=0x53
    if [ $(is_i2cdev_exist $bus $addr_16Q) -eq 0 ]; then
        dump_eeprom $bus $addr_16Q
        exit $?
    elif [ $(is_i2cdev_exist $bus $addr_4DD) -eq 0 ]; then
        dump_eeprom $bus $addr_4DD
        exit $?
    else
        echo "PIM${pim_no} not inserted or could not detect eeprom"
        exit 1
    fi
}

if [ "$#" -ne 1 ]; then
    usage
    exit 1
fi

num=$1
if [ $num -ge 1 -a $num -le 8 ];then
    show_pim_fruid $num
else
    usage
    exit 1
fi
