#!/bin/sh
#
# Copyright 2014-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#

. /usr/local/fbpackages/utils/ast-functions
LOGFILE="/var/log/mTerm_$1.log"

function show_usage() {
  echo "Usage: sol-util [ slot1 | slot2 | slot3 | slot4 ]"
  echo "       sol-util [ slot1 | slot2 | slot3 | slot4 ] [ device0 | device1 | ... device11 ] (baud rate)"
  echo "       sol-util [ slot1 | slot2 | slot3 | slot4 ] --history"
}

if [ "$1" == "slot1" ] || [ "$1" == "slot2" ] || [ "$1" == "slot3" ] || [ "$1" == "slot4" ]
then
  SLOT=$1
else
  show_usage
  exit -1
fi

case $SLOT in
    slot1)
      SLOT_NUM=1
      ;;
    slot2)
      SLOT_NUM=2
      ;;
    slot3)
      SLOT_NUM=3
      ;;
    slot4)
      SLOT_NUM=4
      ;;
esac

if [ $(get_slot_type $SLOT_NUM) == "1" ] || [ $(get_slot_type $SLOT_NUM) == "2" ]; then
  echo "Should not execute sol-util since CF/GP is on $SLOT"
  exit 1
elif [ $(get_slot_type $SLOT_NUM) == "3" ]; then
  echo "Should not execute sol-util since $SLOT is empty"
  exit 1
fi

if [ $# -gt 1 ]; then
  if [[ "$2" == "--history" ]]; then
    cat $LOGFILE 2>/dev/null
    exit 0
  fi

  if [ "${2:0:6}" == "device" ]; then
    dev_num=${2:6}
    if [ "$(echo $dev_num | awk '{print($1<0 || $1>11)?"1":"0"}')" != "0" ]; then
      show_usage
      exit -1
    fi

    if [ $# -gt 2 ]; then
      baud=$3
    else
      baud=57600
    fi

    /bin/stty -F /dev/ttyS$SLOT_NUM $baud >/dev/null 2>&1
    if [ $? -ne 0 ]; then
      show_usage
      exit -1
    fi

    /usr/bin/bic-util $SLOT 0xe0 0x04 0x15 0xa0 0x00 0 0 0 0 0x78 0 0 0 0 0 0 0 $((dev_num<<3)) 0 0 0 >/dev/null 2>&1
    if [ $? -ne 0 ]; then
      /bin/stty -F /dev/ttyS$SLOT_NUM 57600 >/dev/null 2>&1
      show_usage
      exit -1
    fi
  else
    show_usage
    exit -1
  fi
fi

exec /usr/local/bin/mTerm_client $SLOT

echo
echo
echo "-----------------------"
echo "Exit from SOL session."
