swagger: "2.0"
info: 
  description: Swagger doc for /api/dpb/logs  
  title: Swagger doc for /api/dpb/logs  
  version: 1.0.0
paths: 
  /api/dpb/logs: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  Logs: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties:
                        APP_NAME:
                          type: string
                        FRU#:
                          type: string
                        FRU_NAME:
                          type: string
                        MESSAGE:
                          type: string
                        TIME_STAMP:
                          type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            