SUMMARY = "ASPEED BMC Prebuilt Binaries for AST27xx bring-up"
HOMEPAGE = "https://github.com/AspeedTech-BMC/bmc-pb"
PACKAGE_ARCH = "${MACHINE_ARCH}"

# ------------------------------------------------------------------------------
# Prebuilt Binary Description
#
# caliptra-fw*.bin:
#   Prebuilt and ASPEED-signed Caliptra firmware. The vendor key hash is fused in
#   OTP on MP parts, so locally built images cannot be authenticated or boot.
#
# ddr*.bin:
#   DDR4/DDR5 PHY PMU training firmware provided/generated by the DDR PHY IP
#   vendor toolchain and delivered as a binary-only artifact.
#
# dp_*.bin:
#   DisplayPort controller firmware containing proprietary IP, supplied as a
#   prebuilt binary due to licensing restrictions.
#
# uefi_*.bin:
#   AST2700 UEFI/vBIOS firmware that must undergo a vendor-controlled EV signing
#   process to satisfy host secure boot requirements; built and signed externally.
#
# For full details, see:
#   https://gerrit.openbmc.org/c/openbmc/docs/+/85917
# ------------------------------------------------------------------------------

require bmc-pb.inc
PREBUILT_DIR ?= "ast2700a2"
CALIPTRA_FW_BINARY ?= "caliptra-fw.bin"

do_patch[noexec] = "1"
do_configure[noexec] = "1"
do_compile[noexec] = "1"
do_install[noexec] = "1"

inherit deploy

do_deploy () {
  install -d ${DEPLOYDIR}

  install -m 644 ${S}/${PREBUILT_DIR}/${CALIPTRA_FW_BINARY} ${DEPLOYDIR}
  install -m 644 ${S}/${PREBUILT_DIR}/ddr4_*.bin ${DEPLOYDIR}
  install -m 644 ${S}/${PREBUILT_DIR}/ddr5_*.bin ${DEPLOYDIR}
  install -m 644 ${S}/${PREBUILT_DIR}/dp_*.bin ${DEPLOYDIR}
  install -m 644 ${S}/${PREBUILT_DIR}/uefi_*.bin ${DEPLOYDIR}
}

addtask deploy before do_build after do_compile
