PREFERRED_VERSION_aiohttp = "2.1.0"
PREFERRED_VERSION_aiohttp-native = "2.1.0"

PREFERRED_VERSION_async-timeout = "1.2.1"
PREFERRED_VERSION_async-timeout-native = "1.2.1"

PREFERRED_VERSION_chardet = "3.0.4"
PREFERRED_VERSION_chardet-native = "3.0.4"

PREFERRED_VERSION_yarl = "0.10.3"
PREFERRED_VERSION_yarl-native = "0.10.3"

PREFERRED_VERSION_multidict = "2.1.6"
PREFERRED_VERSION_multidict-native = "2.1.6"
