#!/bin/sh

# We're often in the situation where ipmid is leaking. If we're low on memory
# we report the memory usage to disk attempt to clean up known troublemakers
# and request a managed reboot via SEL.

memdump() {
	echo "# free"
	free

	echo "Top"
	top -m -n 1

	echo "# /proc/meminfo"
	cat /proc/meminfo

	echo "# /proc/*/stuff"
	for cmdline_p in /proc/*/cmdline; do
		proc_p=$(dirname "$cmdline_p")
		comm_p=$proc_p/comm
		cmdline=$(tr -d '\0' <"$cmdline_p")
		comm=$(tr -d '\0' <"$comm_p")
		echo "PROC=$proc_p CMDLINE=$cmdline COMM=$comm"
		echo "smaps_rollup"
		cat "$proc_p/smaps_rollup"
		echo "status bits"
		grep "Vm\|Rss" "$proc_p/status"
	done
}
memdump >/home/root/mem-out.txt

# If we're still above 85%, let's ask for help
PCT_FREE=$(free | awk '/^Mem/{printf "%2i\n", $4/$2 * 100.0}')
if [ "$PCT_FREE" -le 15 ]; then
	# We weren't able to clean up enough on our own, and it looks like we're
	# headed for trouble. Ask for help
	systemctl start managed-reboot
fi
