DISTRO_CODENAME="rocko"
BB_SIGNATURE_HANDLER ?= "OEBasicHash"
UNPACKDIR ??= "${WORKDIR}"
TCLIBCAPPEND = ""
# Wrynose renamed DISTRO_FEATURES_BACKFILL_CONSIDERED
DISTRO_FEATURES_BACKFILL_CONSIDERED = "${DISTRO_FEATURES_OPTED_OUT}"
require conf/distro/include/fb-openbmc.inc
