# Currently upstream is setting the kernel DTS to the EVB one, since a 
# real DTS for Anacapa isn't merged.
# Remove once device tree is merged and enabled upstream.
KERNEL_DEVICETREE = "aspeed/${KMACHINE}-bmc-facebook-${MACHINE}.dtb"
