swagger: '2.0'
info:
  description: Swagger doc for /api/bmc
  title: Swagger doc for /api/bmc
  version: 1.0.0
paths:
  /api/bmc:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  Description:
                    type: string
                  MAC Addr:
                    type: string
                  Reset Reason:
                    type: string
                  Uptime:
                    type: string
                  uptime:
                    type: string
                  Memory Usage:
                    type: string
                  memory:
                    type: object
                    additionalProperties: false
                    properties:
                      MemTotal:
                        type: integer
                      MemFree:
                        type: integer
                      MemAvailable:
                        type: integer
                      Buffers:
                        type: integer
                      Cached:
                        type: integer
                      Shmem:
                        type: integer
                  CPU Usage:
                    type: string
                  OpenBMC Version:
                    type: string
                  u-boot version:
                    type: string
                  kernel version:
                    type: string
                  TPM TCG version:
                    type: string
                  TPM FW version:
                    type: string
                  SPI0 Vendor:
                    type: string
                  SPI1 Vendor:
                    type: string
                  At-Scale-Debug Running:
                    type: boolean
                  Secondary Boot Triggered:
                    type: boolean
                  vboot:
                    type: object
                    additionalProperties: false
                    properties:
                      status:
                        type: string
                      status_text:
                        type: string
                      status_crc:
                        type: string
                      tpm_status:
                        type: string
                      cert_fallback_time:
                        type: string
                      cert_time:
                        type: string
                      uboot_fallback_time:
                        type: string
                      uboot_time:
                        type: string
                      force_recovery:
                        type: string
                      hardware_enforce:
                        type: string
                      software_enforce:
                        type: string
                      recovery_boot:
                        type: string
                      recovery_retried:
                        type: string
                      rom_version:
                        type: string
                      rom_uboot_version:
                        type: string
                      flash0_signed:
                        type: string
                      flash0_locked:
                        type: string
                  load-1:
                    type: string
                  load-5:
                    type: string
                  load-15:
                    type: string
                  open-fds:
                    type: string
                  MTD Parts:
                    type: array
                    items:
                      type: string
                  mmc-info:
                    type: object
                    format: nullable
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
