swagger: '2.0'
info:
  description: Swagger doc for /api/uic
  title: Swagger doc for /api/uic
  version: 1.0.0
paths:
  /api/uic:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  Description:
                    type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
