swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/sensors/pim1  
  title: Swagger doc for /api/sys/sensors/pim1  
  version: 1.0.0
paths: 
  /api/sys/sensors/pim1: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  name: 
                    type: string
                  Adapter: 
                    type: string
                  present: 
                    type: boolean
                  PIM1_LM75_U37_TEMP_BASE: 
                    type: string
                  PIM1_LM75_U26_TEMP: 
                    type: string
                  PIM1_LM75_U37_TEMP_MEZZ: 
                    type: string
                  PIM1_QSFP_TEMP: 
                    type: string
                  PIM1_INPUT_VOLTAGE: 
                    type: string
                  PIM1_POWER_VOLTAGE: 
                    type: string
                  PIM1_CURRENT: 
                    type: string
                  PIM1_POWER: 
                    type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            