swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/pimserial  
  title: Swagger doc for /api/sys/pimserial  
  version: 1.0.0
paths: 
  /api/sys/pimserial: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  PIM2: 
                    type: string
                  PIM3: 
                    type: string
                  PIM4: 
                    type: string
                  PIM5: 
                    type: string
                  PIM6: 
                    type: string
                  PIM7: 
                    type: string
                  PIM8: 
                    type: string
                  PIM9: 
                    type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            