swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/presence  
  title: Swagger doc for /api/sys/presence  
  version: 1.0.0
paths: 
  /api/sys/presence: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: array
                items: 
                  type: object
                  additionalProperties: false
                  properties: 
                    scm : 
                      type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            