swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/presence  
  title: Swagger doc for /api/sys/presence  
  version: 1.0.0
paths: 
  /api/sys/presence: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: array
                items: 
                  type: object
                  additionalProperties: false
                  properties: 
                    "scm":  
                      type: string
                      pattern: "^[0-9]+$"
                    "fan1": 
                      type: string
                      pattern: "^[0-9]+$"
                    "fan2": 
                      type: string
                      pattern: "^[0-9]+$"
                    "fan3": 
                      type: string
                      pattern: "^[0-9]+$"
                    "fan4": 
                      type: string
                      pattern: "^[0-9]+$"
                    "fan5": 
                      type: string
                      pattern: "^[0-9]+$"
                    "fan6": 
                      type: string
                      pattern: "^[0-9]+$"
                    "fan7": 
                      type: string
                      pattern: "^[0-9]+$"
                    "fan8": 
                      type: string
                      pattern: "^[0-9]+$"
                    "psu1": 
                      type: string
                      pattern: "^[0-9]+$"
                    "psu2": 
                      type: string
                      pattern: "^[0-9]+$"
                    "psu3": 
                      type: string
                      pattern: "^[0-9]+$"
                    "psu4": 
                      type: string
                      pattern: "^[0-9]+$"
                    "pim1": 
                      type: string
                      pattern: "^[0-9]+$"
                    "pim2": 
                      type: string
                      pattern: "^[0-9]+$"
                    "pim3": 
                      type: string
                      pattern: "^[0-9]+$"
                    "pim4": 
                      type: string
                      pattern: "^[0-9]+$"
                    "pim5": 
                      type: string
                      pattern: "^[0-9]+$"
                    "pim6": 
                      type: string
                      pattern: "^[0-9]+$"
                    "pim7": 
                      type: string
                      pattern: "^[0-9]+$"
                    "pim8": 
                      type: string
                      pattern: "^[0-9]+$"
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
