#!/bin/bash
set -e

if [ -z "$1" ]; then
    echo "Error: No instances parameter provided."
    exit 1
fi

instances=$1
version=$(fw-util "hdd${instances}" --version cpld | awk '{print $NF}')
echo "version: $version"

busctl set-property \
    xyz.openbmc_project.Settings \
    "/xyz/openbmc_project/software/chassis/Clemente_HDD_cpld_${instances}" \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"