swagger: '2.0'
info:
  description: Swagger doc for /api/dpb/hdd-status
  title: Swagger doc for /api/dpb/hdd-status
  version: 1.0.0
paths:
  /api/dpb/hdd-status:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  Normal HDD ID:
                    type: string
                  Abnormal HDD ID:
                    type: string
                  Missing HDD ID:
                    type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
