swagger: '2.0'
info:
  description: Swagger doc for /api/uic/sensors
  title: Swagger doc for /api/uic/sensors
  version: 1.0.0
paths:
  /api/uic/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  UIC_ADC_P12V_DPB:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_ADC_P12V_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_ADC_P5V_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_ADC_P3V3_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_ADC_P3V3_RGM:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_ADC_P2V5_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_ADC_P1V8_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_ADC_P1V2_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_ADC_P1V0_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_P12V_ISENSE_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  UIC_INLET_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
