#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
from __future__ import absolute_import, division, print_function, unicode_literals

from openbmc_gpio_table import BoardGPIO


# The fallowing table is generated using:
# python lightning_gpio_parse.py data/lightning-BMC-GPIO-DVT.csv
# DO NOT MODIFY THE TABLE!!!
# Manual modification will be overridden!!!

board_gpio_table = [
    BoardGPIO("ADC0", "ADC_12V"),
    BoardGPIO("ADC1", "ADC_P5V_STBY"),
    BoardGPIO("ADC2", "ADC_P3V3_STBY"),
    BoardGPIO("ADC3", "ADC_P1V8_STBY"),
    BoardGPIO("ADC4", "ADC_P1V53V"),
    BoardGPIO("ADC5", "ADC_P0V9"),
    BoardGPIO("ADC6", "ADC_P0V9_E"),
    BoardGPIO("ADC7", "ADC_P1V26"),
    BoardGPIO("EXTRST#", "RST_BMC_EXTRST_N"),
    BoardGPIO("GPIOA0", "PEER_TRAY_R"),
    BoardGPIO("GPIOA1", "BMC_JTAG_L_EN", "low"),
    BoardGPIO("GPIOA2", "BMC_USB_EN_1", "low"),
    BoardGPIO("GPIOB0", "PE1_PERST_N", "high"),
    BoardGPIO("GPIOB1", "BMC_RESET_N_DDR3", "high"),
    BoardGPIO("GPIOB3", "LAN_SMB_ALERT_N", "high"),
    BoardGPIO("GPIOB4", "FM_PCH_LAN1_DISABLE_N", "high"),
    BoardGPIO("GPIOD6", "PMC_PLX_BOARD"),
    BoardGPIO("GPIOE4", "BMC_ADD1"),
    BoardGPIO("GPIOE5", "BMC_ADD2"),
    BoardGPIO("GPIOF0", "BMC_SSD_RST_N_7", "high"),
    BoardGPIO("GPIOF1", "BMC_SSD_RST_N_8", "high"),
    BoardGPIO("GPIOF2", "BMC_SSD_RST_N_9", "high"),
    BoardGPIO("GPIOF3", "BMC_SSD_RST_N_10", "high"),
    BoardGPIO("GPIOF4", "BMC_SSD_RST_N_11", "high"),
    BoardGPIO("GPIOF5", "BMC_SSD_RST_N_12", "high"),
    BoardGPIO("GPIOF6", "BMC_SSD_RST_N_13", "high"),
    BoardGPIO("GPIOF7", "BMC_SSD_RST_N_14", "high"),
    BoardGPIO("GPIOG4", "FM_TPM_PRES_N"),
    BoardGPIO("GPIOG5", "BMC_SELF_HW_RST", "low"),
    BoardGPIO("GPIOG6", "DP_RST_N"),
    BoardGPIO("GPIOG7", "EXP_TRAY_ID"),
    BoardGPIO("GPIOI3", "P0V9_E_PG"),
    BoardGPIO("GPIOL0", "CBL_PRSNT_N_1"),
    BoardGPIO("GPIOL1", "CBL_PRSNT_N_2"),
    BoardGPIO("GPIOL2", "CBL_PRSNT_N_3"),
    BoardGPIO("GPIOL3", "CBL_PRSNT_N_4"),
    BoardGPIO("GPIOL4", "CBL_PRSNT_N_5"),
    BoardGPIO("GPIOL5", "CBL_PRSNT_N_6"),
    BoardGPIO("GPIOL6", "CBL_PRSNT_N_7"),
    BoardGPIO("GPIOL7", "CBL_PRSNT_N_8"),
    BoardGPIO("GPIOM0", "BMC_I210_PERST_N", "high"),
    BoardGPIO("GPIOM1", "BMC_SSD_RST_N_0", "high"),
    BoardGPIO("GPIOM2", "BMC_SSD_RST_N_1", "high"),
    BoardGPIO("GPIOM3", "BMC_SSD_RST_N_2", "high"),
    BoardGPIO("GPIOM4", "BMC_SSD_RST_N_3", "high"),
    BoardGPIO("GPIOM5", "BMC_SSD_RST_N_4", "high"),
    BoardGPIO("GPIOM6", "BMC_SSD_RST_N_5", "high"),
    BoardGPIO("GPIOM7", "BMC_SSD_RST_N_6", "high"),
    BoardGPIO("GPION1", "BMC_FW_DET_BOARD_VER_0"),
    BoardGPIO("GPION2", "LED_DR_LED1", "high"),
    BoardGPIO("GPION4", "BMC_SELF_TRAY"),
    BoardGPIO("GPION6", "BMC_FW_DET_BOARD_VER_1"),
    BoardGPIO("GPION7", "BMC_FW_DET_BOARD_VER_2"),
    BoardGPIO("GPIOO3", "HB_OUT_BMC", "low"),
    BoardGPIO("GPIOO5", "PEER_BMC_HB"),
    BoardGPIO("GPIOP5", "UART_COUNT"),
    BoardGPIO("GPIOP7", "BMC_ENCLOSURE_LED", "high"),
    BoardGPIO("GPIOQ6", "I2C_MUX_RESET_PEB", "high"),
    BoardGPIO("GPIOQ7", "TCA9554_INT_N"),
    BoardGPIO("GPIOR1", "TRAY_ID1"),
    BoardGPIO("GPIOR2", "TRAY_ID2"),
    BoardGPIO("GPIOR3", "BP_PRSNT_N"),
    BoardGPIO("GPIOR4", "BMC_INT_N", "high"),
    BoardGPIO("GPIOR5", "TRAY_POWER_CRIT_N"),
    BoardGPIO("GPIOS5", "TRAY_ID0"),
    BoardGPIO("GPIOY0", "SPI_FLASH_SELECT", "high"),
    BoardGPIO("GPIOY1", "FCB_HW_REVISION"),
    BoardGPIO("GPIOY2", "DPB_HW_REVISION"),
    BoardGPIO("PWM0", "PWM_EXP_A"),
    BoardGPIO("RMII1CRSDV", "RMII_BMC_CRS_DV"),
    BoardGPIO("RMII1RCLK", "CLK_50M_BMC0"),
    BoardGPIO("RMII1RXD0", "RMII_PHY_BMC_RXD0"),
    BoardGPIO("RMII1RXD1", "RMII_PHY_BMC_RXD1"),
    BoardGPIO("RMII1RXER", "RMII_BMC_RX_ER"),
    BoardGPIO("RMII1TXD0", "RMII_BMC_PHY_TXD0"),
    BoardGPIO("RMII1TXD1", "RMII_BMC_PHY_TXD1"),
    BoardGPIO("RMII1TXEN", "RMII_BMC_TX_EN"),
    BoardGPIO("RMII2RCLK", "CLK_50M_BMC_NCSI"),
    BoardGPIO("ROMA10", "ROMA10"),
    BoardGPIO("ROMA11", "ROMA11"),
    BoardGPIO("ROMA12", "ROMA12"),
    BoardGPIO("ROMA13", "ROMA13"),
    BoardGPIO("ROMA14", "ROMA14"),
    BoardGPIO("ROMA15", "ROMA15"),
    BoardGPIO("ROMA16", "ROMA16"),
    BoardGPIO("ROMA17", "ROMA17"),
    BoardGPIO("ROMA18", "ROMA18"),
    BoardGPIO("ROMA19", "ROMA19"),
    BoardGPIO("ROMA2", "ROMA2"),
    BoardGPIO("ROMA20", "ROMA20"),
    BoardGPIO("ROMA21", "ROMA21"),
    BoardGPIO("ROMA22", "ROMA22"),
    BoardGPIO("ROMA23", "ROMA23"),
    BoardGPIO("ROMA3", "ROMA3"),
    BoardGPIO("ROMA4", "ROMA4"),
    BoardGPIO("ROMA5", "ROMA5"),
    BoardGPIO("ROMA6", "ROMA6"),
    BoardGPIO("ROMA7", "ROMA7"),
    BoardGPIO("ROMA8", "ROMA8"),
    BoardGPIO("ROMA9", "ROMA9"),
    BoardGPIO("ROMCS1#", "FLA_CS1_R"),
    BoardGPIO("ROMD4", "ROMD4"),
    BoardGPIO("ROMD5", "ROMD5"),
    BoardGPIO("ROMD6", "ROMD6"),
    BoardGPIO("ROMD7", "ROMD7"),
    BoardGPIO("SCL10", "BMC_I2C10_8536_SCL"),
    BoardGPIO("SCL11", "BMC_I2C11_MINI5_SCL_S"),
    BoardGPIO("SCL12", "BMC_I2C12_MINI6_SCL_S"),
    BoardGPIO("SCL13", "BMC_I2C13_MINI7_SCL_S"),
    BoardGPIO("SCL14", "BMC_I2C14_MINI8_SCL_S"),
    BoardGPIO("SCL3", "BMC_I2C3_MINI3_SCL_S"),
    BoardGPIO("SCL4", "BMC_I2C4_MIN4_SCL_S"),
    BoardGPIO("SCL5", "BMC_I2C5_D_PEB_DEVICE_SCL"),
    BoardGPIO("SCL6", "BMC_I2C6_C_FCB_SCL"),
    BoardGPIO("SCL7", "BMC_I2C7_B_DBP_SCL"),
    BoardGPIO("SCL8", "BMC_I2C8_CLKBUF1_SCL"),
    BoardGPIO("SCL9", "BMC_I2C9_CLKBUF2_SCL"),
    BoardGPIO("SDA10", "BMC_I2C10_8536_SDA"),
    BoardGPIO("SDA11", "BMC_I2C11_MINI5_SDA_S"),
    BoardGPIO("SDA12", "BMC_I2C12_MINI6_SDA_S"),
    BoardGPIO("SDA13", "BMC_I2C13_MINI7_SDA_S"),
    BoardGPIO("SDA14", "BMC_I2C14_MINI8_SDA_S"),
    BoardGPIO("SDA3", "BMC_I2C3_MINI3_SDA_S"),
    BoardGPIO("SDA4", "BMC_I2C4_MIN4_SDA_S"),
    BoardGPIO("SDA5", "BMC_I2C5_D_PEB_DEVICE_SDA"),
    BoardGPIO("SDA6", "BMC_I2C6_C_FCB_SDA"),
    BoardGPIO("SDA7", "BMC_I2C7_B_DPB_SDA"),
    BoardGPIO("SDA8", "BMC_I2C8_CLKBUF1_SDA"),
    BoardGPIO("SDA9", "BMC_I2C9_CLKBUF2_SDA"),
]
