#!/bin/sh
#
# Copyright 2014-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#

usage() {
  echo "Usage:   mac-util --set <MAC address>"
  echo "         mac-util --get"
  echo "Example: mac-util --set 0x02 0x00 0x00 0x00 0x00 0x01"
  exit -1
}

if [[ "$1" == "--set" ]]; then
  if [[ $# != 7 ]]; then
    usage
    exit -1
  fi
  # Store MAC address in MB's FRU at offset 1k
  ipmitool i2c bus=6 0xA8 0x0 0x4 0x0 $2 $3 $4 $5 $6 $7 > /dev/null
elif [[ "$1" = "--get" ]]; then
  mac=$(ipmitool i2c bus=6 0xA8 0x6 0x4 0x0)
  addr="$(echo $mac | cut -d " " -f 1)"
  addr+=":$(echo $mac | cut -d " " -f 2)"
  addr+=":$(echo $mac | cut -d " " -f 3)"
  addr+=":$(echo $mac | cut -d " " -f 4)"
  addr+=":$(echo $mac | cut -d " " -f 5)"
  addr+=":$(echo $mac | cut -d " " -f 6)"
  echo $addr
else
  usage
  exit -1
fi
