swagger: '2.0'
info:
  description: Swagger doc for /api/server/bios/plat-info
  title: Swagger doc for /api/server/bios/plat-info
  version: 1.0.0
paths:
  /api/server/bios/plat-info:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  Platform Information:
                    type: array
                    items:
                      type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
