/*
 *
 * Copyright 2020-present Facebook. All Rights Reserved.
 *
 * This program file is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program in a file named COPYING; if not, write to the
 * Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301 USA
 */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <syslog.h>
#include <unistd.h>
#include <openbmc/libgpio.h>

typedef struct gpio_info {
	char *shadow_name;
	char *pin_name;
	gpio_direction_t direction;
	gpio_value_t value;
} gpio_cfg;

/* BMC gpio table */
gpio_cfg bmc_gpio_cfg[] = {
	/* shadow_name, pin_name, direction, value */

	// FPGA_CRCERROR, GPIOB0 (824)
	{"FPGA_CRCERROR", "GPIOB0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// FPGA_NCONFIG, GPIOB1 (825)
	{"FPGA_NCONFIG", "GPIOB1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_SCC_FAULT_IN_R, GPIOB2 (826)
	{"BMC_SCC_FAULT_IN_R", "GPIOB2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// HSC_P12V_DPB_FAULT_N_IN_R, GPIOB4 (828)
	{"HSC_P12V_DPB_FAULT_N_IN_R", "GPIOB4", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// HSC_COMP_FAULT_N_IN_R, GPIOB5 (829)
	{"HSC_COMP_FAULT_N_IN_R", "GPIOB5", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_NIC_PWRBRK_R, GPIOC1 (833)
	{"BMC_NIC_PWRBRK_R", "GPIOC1", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// BMC_NIC_SMRST_N_R, GPIOC2 (834)
	{"BMC_NIC_SMRST_N_R", "GPIOC2", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// NIC_WAKE_BMC_N, GPIOC3 (835)
	{"NIC_WAKE_BMC_N", "GPIOC3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_NIC_FULL_PWR_EN_R, GPIOC4 (836)
	{"BMC_NIC_FULL_PWR_EN_R", "GPIOC4", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// NIC_FULL_PWR_PG, GPIOC5 (837)
	{"NIC_FULL_PWR_PG", "GPIOC5", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BOARD_REV_ID0, GPIOH0 (872)
	{"BOARD_REV_ID0", "GPIOH0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BOARD_REV_ID1, GPIOH1 (873)
	{"BOARD_REV_ID1", "GPIOH1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BOARD_REV_ID2, GPIOH2 (874)
	{"BOARD_REV_ID2", "GPIOH2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// EN_ASD_DEBUG, GPIOI5 (885)
	{"EN_ASD_DEBUG", "GPIOI5", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_RST_BTN_N, GPIOI7 (887)
	{"DEBUG_RST_BTN_N", "GPIOI7", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// E1S_1_P3V3_PG_R, GPIOL6 (910)
	{"E1S_1_P3V3_PG_R", "GPIOL6", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// E1S_2_P3V3_PG_R, GPIOL7 (911)
	{"E1S_2_P3V3_PG_R", "GPIOL7", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// BMC_FPGA_UART_SEL0_R, GPIOM0 (912)
	{"BMC_FPGA_UART_SEL0_R", "GPIOM0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_FPGA_UART_SEL1_R, GPIOM1 (913)
	{"BMC_FPGA_UART_SEL1_R", "GPIOM1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_FPGA_UART_SEL2_R, GPIOM2 (914)
	{"BMC_FPGA_UART_SEL2_R", "GPIOM2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_FPGA_UART_SEL3_R, GPIOM3 (915)
	{"BMC_FPGA_UART_SEL3_R", "GPIOM3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_BMC_UART_SEL_R, GPIOM4 (916)
	{"DEBUG_BMC_UART_SEL_R", "GPIOM4", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_GPIO_BMC_1, GPION0 (920)
	{"DEBUG_GPIO_BMC_1", "GPION0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_GPIO_BMC_2, GPION1 (921)
	{"DEBUG_GPIO_BMC_2", "GPION1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_GPIO_BMC_3, GPION2 (922)
	{"DEBUG_GPIO_BMC_3", "GPION2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_GPIO_BMC_4, GPION3 (923)
	{"DEBUG_GPIO_BMC_4", "GPION3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_GPIO_BMC_5, GPION4 (924)
	{"DEBUG_GPIO_BMC_5", "GPION4", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_GPIO_BMC_6, GPION5 (925)
	{"DEBUG_GPIO_BMC_6", "GPION5", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// USB_OC_N1, GPIOO3 (931)
	{"USB_OC_N1", "GPIOO3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// SCC_I2C_EN_R, GPIOO4 (932)
	{"SCC_I2C_EN_R", "GPIOO4", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// BMC_READY_R, GPIOO5 (933)
	{"BMC_READY_R", "GPIOO5", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LED_POSTCODE_0, GPIOO7 (935)
	{"LED_POSTCODE_0", "GPIOO7", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LED_POSTCODE_1, GPIOP0 (936)
	{"LED_POSTCODE_1", "GPIOP0", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LED_POSTCODE_2, GPIOP1 (937)
	{"LED_POSTCODE_2", "GPIOP1", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LED_POSTCODE_3, GPIOP2 (938)
	{"LED_POSTCODE_3", "GPIOP2", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LED_POSTCODE_4, GPIOP3 (939)
	{"LED_POSTCODE_4", "GPIOP3", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LED_POSTCODE_5, GPIOP4 (940)
	{"LED_POSTCODE_5", "GPIOP4", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LED_POSTCODE_6, GPIOP5 (941)
	{"LED_POSTCODE_6", "GPIOP5", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LED_POSTCODE_7, GPIOP6 (942)
	{"LED_POSTCODE_7", "GPIOP6", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// BMC_LOC_HEARTBEAT_R, GPIOQ1 (945)
	{"BMC_LOC_HEARTBEAT_R", "GPIOQ1", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// BIC_READY_IN, GPIOQ6 (950)
	{"BIC_READY_IN", "GPIOQ6", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// COMP_STBY_PG_IN, GPIOQ7 (951)
	{"COMP_STBY_PG_IN", "GPIOQ7", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// UIC_LOC_TYPE_IN, GPIOR1 (953)
	{"UIC_LOC_TYPE_IN", "GPIOR1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// UIC_RMT_TYPE_IN, GPIOR2 (954)
	{"UIC_RMT_TYPE_IN", "GPIOR2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_COMP_PWR_EN_R, GPIOR4 (956)
	{"BMC_COMP_PWR_EN_R", "GPIOR4", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// EXT_MINISAS_INS_OR_N_IN, GPIOR6 (958)
	{"EXT_MINISAS_INS_OR_N_IN", "GPIOR6", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// NIC_PRSNTB3_N, GPIOS0 (960)
	{"NIC_PRSNTB3_N", "GPIOS0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// FM_BMC_TPM_PRSNT_N, GPIOS2 (962)
	{"FM_BMC_TPM_PRSNT_N", "GPIOS2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// DEBUG_CARD_PRSNT_N, GPIOS3 (963)
	{"DEBUG_CARD_PRSNT_N", "GPIOS3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_RST_BTN_N_R, GPIOV0 (984)
	{"BMC_RST_BTN_N_R", "GPIOV0", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// PCIE_COMP_UIC_RST_N, GPIOV1 (985)
	{"PCIE_COMP_UIC_RST_N", "GPIOV1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_COMP_SYS_RST_N_R, GPIOV2 (986)
	{"BMC_COMP_SYS_RST_N_R", "GPIOV2", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// BMC_PWRGD_NIC, GPIOV3 (987)
	{"BMC_PWRGD_NIC", "GPIOV3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
	// BMC_LED_STATUS_BLUE_EN_R, GPIOV4 (988)
	{"BMC_LED_STATUS_BLUE_EN_R", "GPIOV4", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// BMC_LED_STATUS_YELLOW_EN_R, GPIOV5 (989)
	{"BMC_LED_STATUS_YELLOW_EN_R", "GPIOV5", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// BMC_LED_PWR_BTN_EN_R, GPIOV6 (990)
	{"BMC_LED_PWR_BTN_EN_R", "GPIOV6", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// LAST
	{NULL, NULL, GPIO_DIRECTION_INVALID, GPIO_VALUE_INVALID}
};

/* expander gpio table */
gpio_cfg exp_gpio_cfg[] = {
	/* shadow_name, pin_name, direction, value */

	// COMP_PRSNT_N: P00 (748)
	{"COMP_PRSNT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// FAN_0_INS_N: P01 (749)
	{"FAN_0_INS_N",          NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// FAN_1_INS_N: P02 (750)
	{"FAN_1_INS_N",          NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// FAN_2_INS_N: P03 (751)
	{"FAN_2_INS_N",          NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// FAN_3_INS_N: P04 (752)
	{"FAN_3_INS_N",          NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// UIC_RMT_INS_N: P05 (753)
	{"UIC_RMT_INS_N",        NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// SCC_LOC_INS_N: P06 (754)
	{"SCC_LOC_INS_N",        NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// SCC_RMT_INS_N: P07 (755)
	{"SCC_RMT_INS_N",        NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// SCC_LOC_TYPE_0: P10 (756)
	{"SCC_LOC_TYPE_0",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// SCC_RMT_TYPE_0: P11 (757)
	{"SCC_RMT_TYPE_0",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// SCC_STBY_PGOOD: P12 (758)
	{"SCC_STBY_PGOOD",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// SCC_FULL_PGOOD: P13 (759)
	{"SCC_FULL_PGOOD",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// COMP_PGOOD: P14 (760)
	{"COMP_PGOOD",           NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// DRAWER_CLOSED_N: P15 (761)
	{"DRAWER_CLOSED_N",      NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// E1S_1_PRSNT_N: P16 (762)
	{"E1S_1_PRSNT_N",        NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// E1S_2_PRSNT_N: P17 (763)
	{"E1S_2_PRSNT_N",        NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// I2C_E1S_1_RST_N: P00 (764)
	{"I2C_E1S_1_RST_N",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// I2C_E1S_2_RST_N: P01 (765)
	{"I2C_E1S_2_RST_N",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// E1S_1_LED_ACT: P02 (766)
	{"E1S_1_LED_ACT",        NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// E1S_2_LED_ACT: P03 (767)
	{"E1S_2_LED_ACT",        NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// SCC_STBY_PWR_EN: P04 (768)
	{"SCC_STBY_PWR_EN",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// SCC_FULL_PWR_EN: P05 (769)
	{"SCC_FULL_PWR_EN",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// BMC_EXP_SOFT_RST_N: P06 (770)
	{"BMC_EXP_SOFT_RST_N",   NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// UIC_COMP_BIC_RST_N: P07 (771)
	{"UIC_COMP_BIC_RST_N",   NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// E1S_1_3V3EFUSE_PGOOD: P10 (772)
	{"E1S_1_3V3EFUSE_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// E1S_2_3V3EFUSE_PGOOD: P11 (773)
	{"E1S_2_3V3EFUSE_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// P12V_NIC_FAULT_N: P12 (774)
	{"P12V_NIC_FAULT_N",     NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// P3V3_NIC_FAULT_N: P13 (775)
	{"P3V3_NIC_FAULT_N",     NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// SCC_POR_RST_N: P14 (776)
	{"SCC_POR_RST_N",        NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
	// IOC_T7_SYS_PGOOD: P15 (777)
	{"IOC_T7_SYS_PGOOD",     NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
	// BMC_COMP_BLED: P16 (778)
	{"BMC_COMP_BLED",        NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// BMC_COMP_YLED: P17 (779)
	{"BMC_COMP_YLED",        NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
	// LAST
	{NULL, NULL, GPIO_DIRECTION_INVALID, GPIO_VALUE_INVALID}
};

int setup_gpio_with_value(const char *chip_name, const char *shadow_name, const char *pin_name, int offset, gpio_direction_t direction, gpio_value_t value)
{
	int ret = 0;
	if (gpio_is_exported(shadow_name) == false) {
		if (strncmp(chip_name, GPIO_CHIP_ASPEED, GPIO_CHIP_MAX) == 0) {
			ret = gpio_export_by_name(GPIO_CHIP_ASPEED, pin_name, shadow_name);
		}
		else if (strncmp(chip_name, GPIO_CHIP_I2C_IO_EXP, GPIO_CHIP_MAX) == 0) {
			ret = gpio_export_by_offset(GPIO_CHIP_I2C_IO_EXP, offset, shadow_name);
		}
		else {
			printf("failed to recognize chip name: %s\n", chip_name);
			syslog(LOG_ERR, "failed to recognize chip name: %s\n", chip_name);
			return -1;
		}

		if (ret != 0) {
			printf("failed to export %s\n", shadow_name);
			syslog(LOG_ERR, "failed to export %s\n", shadow_name);
			return ret;
		}

		if (direction == GPIO_DIRECTION_OUT) {
			ret = gpio_set_init_value_by_shadow(shadow_name, value);

			if (ret != 0) {
				printf("failed to set initial value to %s\n", shadow_name);
				syslog(LOG_ERR, "failed to set initial value to %s\n", shadow_name);
				return ret;
			}
		}
	}

	return ret;
}

void setup_gpios_by_table(const char *chip_name, gpio_cfg *gpio_config) {
	int ret = 0, offset = 0;

	while (gpio_config[offset].shadow_name != NULL) {
		ret = setup_gpio_with_value(chip_name,
			gpio_config[offset].shadow_name,
			gpio_config[offset].pin_name,
			offset,
			gpio_config[offset].direction,
			gpio_config[offset].value);

		if (ret != 0) {
			printf("failed to setup %s\n", gpio_config[offset].shadow_name);
			syslog(LOG_ERR, "failed to setup %s\n", gpio_config[offset].shadow_name);
		}
		offset += 1;
	}
}

int
main(int argc, char **argv) {
	printf("Set up GPIO pins...\n");
	setup_gpios_by_table(GPIO_CHIP_ASPEED, bmc_gpio_cfg);

	printf("Set up expander GPIO pins...\n");
	setup_gpios_by_table(GPIO_CHIP_I2C_IO_EXP, exp_gpio_cfg);

	printf("done.\n");

	return 0;
}
