#!/bin/bash

POSITIONAL=()
build_dir=""
shell=no
print_help=no
log_loc=""
while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
		-b|--build)
			build_dir="$2"
			shift 2
			;;
    -s|--shell)
      shell=yes
      shift 1
      ;;
    -h|--help)
      print_help=yes
      shift 1
      ;;
     -l|--log)
       log_loc="$2"
       shift 2
       ;;
    *)
    	POSITIONAL+=("$1")
    	shift
    	;;
	esac
done
set -- "${POSITIONAL[@]}"

if [ $print_help = "yes" ]; then
  echo "USAGE: $0 [OPTIONS] [RECIPES]"
  echo "       -b|--build BUILD_DIR"
  echo "                  Use an existing build directory instead of building one"
  echo "       -s|--shell"
  echo "                  Drops you into a CHROOTed shell of the image instead of running ptest-runner (Useful for debugging)"
  echo "       -l|--log LOCATION"
  echo "                  Print log file at LOCATION after execution"
  echo "       -h|--help"
  echo "                  Prints this message"
  echo "       RECIPES    Space separated list of recipes to run tests for. By default, will run all discovered. Ignored if -s|--shell"
  exit 0
fi

openbmc_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/../..)
cur=$(pwd)
if [ -z "$build_dir" ]; then
  env -i HOME="$HOME" bash -l -c "cd  $openbmc_dir; source ./openbmc-init-build-env qemux86 build-qemux86 > /dev/null; bitbake -q qemux86-image"
  if [ $? != 0 ]; then
    echo "Build failed"
    exit 1
  fi
  build_dir="${openbmc_dir}/build-qemux86"
fi
cd "$build_dir" || exit 1
deploy=./tmp/deploy/images/qemux86-64
rootfs_zip=$(realpath $deploy/qemux86-image-qemux86-64.tar.bz2)
rootfs=$deploy/rootfs
if [ -d $rootfs ]; then
  rm -rf $rootfs
fi
mkdir $rootfs
tar -xf "$rootfs_zip" -C "$rootfs" > /dev/null
if [ $shell = "yes" ]; then
  unshare --mount --map-root-user chroot "$rootfs"
else
  unshare --mount --map-root-user chroot "$rootfs" ptest-runner "$@"
  if [ "$log_loc" != "" ]; then
    cat "${rootfs}${log_loc}"
  fi
fi
cd "$cur" || exit 1
