/**
 *	@brief		Implements the TPM_OwnerReadInternalPub command
 *	@details	The module receives the input parameters marshals these parameters
 *				to a byte array sends the command to the TPM and unmarshals the response
 *				back to the out parameters
 *	@file		TPM_OwnerReadInternalPub.c
 *	@copyright	Copyright 2015 - 2018 Infineon Technologies AG ( www.infineon.com )
 *
 *	@copyright	All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *  1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *  3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "TPM_OwnerReadInternalPub.h"
#include "TPM_Marshal.h"
#include "TPM2_Marshal.h"
#include "DeviceManagement.h"
#include "Platform.h"
#include "Crypt.h"

/**
 *	@brief		This function handles the TPM_OwnerReadInternalPub command
 *	@details	The function receives the input parameters marshals these parameters
 *				to a byte array sends the command to the TPM and unmarshals the response
 *				back to the out parameters
 *
 *	@param		PunKeyHandle			Handle for either PUBEK or SRK
 *	@param		PunAuthHandle			The authorization session handle used for owner authentication.
 *	@param		PsNonceOdd				Nonce generated by system associated with authHandle
 *	@param		PpsNonceEven			In: Even nonce previously generated by TPM to cover inputs
 *										Out: Even nonce newly generated by TPM to cover outputs
 *	@param		PsOwnerAuth				The authorization session digest for inputs and owner authentication. HMAC key: ownerAuth.
 *	@param		PpsPublicPortion		The public portion of the requested key
 *	@param		PpsResAuth				The authorization session digest for the returned parameters. HMAC key: ownerAuth.
 *
 *	@retval		RC_SUCCESS				The operation completed successfully.
 *	@retval		RC_E_BAD_PARAMETER		An invalid parameter was passed to the function. E.g. NULL pointer
 *	@retval		RC_E_BUFFER_TOO_SMALL	In case of the HMAC buffer is too small
 *	@retval		RC_E_INTERNAL			In case of a not yet implemented capability request
 *	@retval		...						Error codes from called functions.
 */
_Check_return_
unsigned int
TSS_TPM_OwnerReadInternalPub(
	_In_	TSS_TPM_KEY_HANDLE	PunKeyHandle,
	_In_	TSS_TPM_AUTHHANDLE	PunAuthHandle,
	_In_	TSS_TPM_NONCE		PsNonceOdd,
	_Inout_ TSS_TPM_NONCE*		PpsNonceEven,
	_In_	TSS_TPM_AUTHDATA	PsOwnerAuth,
	_Out_	TSS_TPM_PUBKEY*		PpsPublicPortion,
	_Out_	TSS_TPM_AUTHDATA*	PpsResAuth)
{
	unsigned int unReturnValue = RC_SUCCESS;
	do
	{
		TSS_BYTE rgbRequest[TSS_MAX_COMMAND_SIZE] = {0};
		TSS_BYTE rgbResponse[TSS_MAX_RESPONSE_SIZE] = {0};
		TSS_BYTE* pbBuffer = NULL;
		TSS_BYTE* pbDigestBuffer = NULL;
		TSS_INT32 nSizeRemaining = sizeof(rgbRequest);
		TSS_INT32 nSizeResponse = sizeof(rgbResponse);

		// Request parameters
		TSS_TPM_TAG tag = TSS_TPM_TAG_RQU_AUTH1_COMMAND;
		TSS_UINT32 unCommandSize = 0;
		TSS_TPM_COMMAND_CODE commandCode = TSS_TPM_ORD_OwnerReadInternalPub;
		BOOL fContinueAuthSession = TRUE;
		TSS_BYTE rgbInParamDigest[TSS_SHA1_DIGEST_SIZE] = {0};

		// Response parameters
		TSS_UINT32 unResponseSize = 0;
		TSS_TPM_RESULT responseCode = TSS_TPM_RC_SUCCESS;

		// Initialize out parameters
		if (NULL != PpsPublicPortion)
			unReturnValue = Platform_MemorySet(PpsPublicPortion, 0, sizeof(TSS_TPM_PUBKEY));
		if (NULL != PpsPublicPortion)
			unReturnValue |= Platform_MemorySet(PpsResAuth, 0, sizeof(TSS_TPM_AUTHDATA));
		if (RC_SUCCESS != unReturnValue)
			break;

		// Check parameters
		if (NULL == PpsNonceEven || NULL == PpsPublicPortion || NULL == PpsResAuth)
		{
			unReturnValue = RC_E_BAD_PARAMETER;
			break;
		}

		// Marshal the request
		pbBuffer = rgbRequest;
		unReturnValue = TSS_TPM_TAG_Marshal(&tag, &pbBuffer, &nSizeRemaining);
		if (RC_SUCCESS != unReturnValue)
			break;
		unReturnValue = TSS_UINT32_Marshal(&unCommandSize, &pbBuffer, &nSizeRemaining);
		if (RC_SUCCESS != unReturnValue)
			break;

		// Store beginning for digest buffer
		pbDigestBuffer = pbBuffer;

		unReturnValue = TSS_TPM_COMMAND_CODE_Marshal(&commandCode, &pbBuffer, &nSizeRemaining);
		if (RC_SUCCESS != unReturnValue)
			break;
		unReturnValue = TSS_UINT32_Marshal(&PunKeyHandle, &pbBuffer, &nSizeRemaining);
		if (RC_SUCCESS != unReturnValue)
			break;

		// Calculate inParamDigest
		unReturnValue = Crypt_SHA1(pbDigestBuffer, (unsigned short)(pbBuffer - pbDigestBuffer), rgbInParamDigest);
		if (RC_SUCCESS != unReturnValue)
			break;

		unReturnValue = TSS_UINT32_Marshal(&PunAuthHandle, &pbBuffer, &nSizeRemaining);
		if (RC_SUCCESS != unReturnValue)
			break;
		unReturnValue = TSS_TPM_NONCE_Marshal(&PsNonceOdd, &pbBuffer, &nSizeRemaining);
		if (RC_SUCCESS != unReturnValue)
			break;
		unReturnValue = TSS_BOOL_Marshal(&fContinueAuthSession, &pbBuffer, &nSizeRemaining);
		if (RC_SUCCESS != unReturnValue)
			break;

		{
			// Create HMAC buffer
			TSS_BYTE rgbHmacBuffer[sizeof(rgbInParamDigest) + 2 * TPM_NONCE_SIZE + sizeof(TSS_BYTE)] = {0};
			int nHmacBufferSize = sizeof(rgbHmacBuffer);
			TSS_BYTE* pbHmacBuffer = rgbHmacBuffer;
			TSS_TPM_AUTHDATA sAuthData = {{0}};

			unReturnValue = Platform_MemoryCopy(pbHmacBuffer, nHmacBufferSize, rgbInParamDigest, sizeof(rgbInParamDigest));
			if (RC_SUCCESS != unReturnValue)
				break;
			pbHmacBuffer += sizeof(rgbInParamDigest);
			nHmacBufferSize -= sizeof(rgbInParamDigest);

			// Start of inAuthSetupParams
			unReturnValue = Platform_MemoryCopy(pbHmacBuffer, nHmacBufferSize, PpsNonceEven->nonce, TPM_NONCE_SIZE);
			if (RC_SUCCESS != unReturnValue)
				break;
			pbHmacBuffer += TPM_NONCE_SIZE;
			nHmacBufferSize -= TPM_NONCE_SIZE;

			unReturnValue = Platform_MemoryCopy(pbHmacBuffer, nHmacBufferSize, PsNonceOdd.nonce, TPM_NONCE_SIZE);
			if (RC_SUCCESS != unReturnValue)
				break;
			pbHmacBuffer += TPM_NONCE_SIZE;
			nHmacBufferSize -= TPM_NONCE_SIZE;

			// Do a size check
			if (nHmacBufferSize < 1)
			{
				unReturnValue = RC_E_BUFFER_TOO_SMALL;
				break;
			}
			*pbHmacBuffer = (TSS_BYTE)fContinueAuthSession;
			nHmacBufferSize--;

			// Check if buffer is filled correctly
			if (0 != nHmacBufferSize)
			{
				unReturnValue = RC_E_INTERNAL;
				break;
			}
			// End of inAuthSetupParams

			unReturnValue = Crypt_HMAC(rgbHmacBuffer, sizeof(rgbHmacBuffer), PsOwnerAuth.authdata, sAuthData.authdata);
			if (RC_SUCCESS != unReturnValue)
				break;

			unReturnValue = TSS_TPM_AUTHDATA_Marshal(&sAuthData, &pbBuffer, &nSizeRemaining);
			if (RC_SUCCESS != unReturnValue)
				break;
		}

		// Overwrite unCommandSize
		unCommandSize = sizeof(rgbRequest) - nSizeRemaining;
		pbBuffer = rgbRequest + 2;
		nSizeRemaining = 4;
		unReturnValue = TSS_UINT32_Marshal(&unCommandSize, &pbBuffer, &nSizeRemaining);
		if (RC_SUCCESS != unReturnValue)
			break;

		// Transmit the command over TDDL
		unReturnValue = DeviceManagement_Transmit(rgbRequest, unCommandSize, rgbResponse, (unsigned int*)&nSizeResponse);
		if (TSS_TPM_RC_SUCCESS != unReturnValue)
			break;

		// Unmarshal the response
		pbBuffer = rgbResponse;
		nSizeRemaining = nSizeResponse;
		unReturnValue = TSS_TPM_TAG_Unmarshal(&tag, &pbBuffer, &nSizeRemaining);
		if (TSS_TPM_RC_SUCCESS != unReturnValue)
			break;
		unReturnValue = TSS_UINT32_Unmarshal(&unResponseSize, &pbBuffer, &nSizeRemaining);
		if (TSS_TPM_RC_SUCCESS != unReturnValue)
			break;
		unReturnValue = TSS_TPM_RESULT_Unmarshal(&responseCode, &pbBuffer, &nSizeRemaining);
		if (TSS_TPM_RC_SUCCESS != unReturnValue)
			break;
		if (responseCode != TSS_TPM_RC_SUCCESS)
		{
			unReturnValue = RC_TPM_MASK | responseCode;
			break;
		}

		// Get response data
		{
			TSS_TPM_PUBKEY sTempPublicPortion = {{0}};
			TSS_TPM_NONCE sTempNonceEven = {{0}};
			BOOL fTempContinueAuthSession = FALSE;
			TSS_TPM_AUTHDATA sTempResAuth = {{0}};

			unReturnValue = TSS_TPM_PUBKEY_Unmarshal(&sTempPublicPortion, &pbBuffer, &nSizeRemaining);
			if (RC_SUCCESS != unReturnValue)
				break;
			unReturnValue = TSS_TPM_NONCE_Unmarshal(&sTempNonceEven, &pbBuffer, &nSizeRemaining);
			if (RC_SUCCESS != unReturnValue)
				break;
			unReturnValue = TSS_BOOL_Unmarshal(&fTempContinueAuthSession, &pbBuffer, &nSizeRemaining);
			if (RC_SUCCESS != unReturnValue)
				break;
			unReturnValue = TSS_TPM_AUTHDATA_Unmarshal(&sTempResAuth, &pbBuffer, &nSizeRemaining);
			if (RC_SUCCESS != unReturnValue)
				break;

			*PpsNonceEven = sTempNonceEven;
			*PpsResAuth = sTempResAuth;
			*PpsPublicPortion = sTempPublicPortion;
		}
	}
	WHILE_FALSE_END;

	return unReturnValue;
}
