swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/firmware_info/all  
  title: Swagger doc for /api/sys/firmware_info/all  
  version: 1.0.0
paths: 
  /api/sys/firmware_info/all: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              SYS_CPLD: 
                type: string
              FAN_CPLD: 
                type: string
