#define MAX_DESCRIPTION_NUM 100
char *Error_Code_Description[MAX_DESCRIPTION_NUM] = {
	"No error", //Error Code 0
	"PCIe internal switch fault",
	"I2C bus 1 crash (I2C bus index base 1)",
	"I2C bus 2 crash (I2C bus index base 1)",
	"I2C bus 3 crash (I2C bus index base 1)",
	"I2C bus 4 crash (I2C bus index base 1)",
	"I2C bus 5 crash (I2C bus index base 1)",
	"I2C bus 6 crash (I2C bus index base 1)",
	"I2C bus 7 crash (I2C bus index base 1)",
	"I2C bus 8 crash (I2C bus index base 1)",
	"I2C bus 9 crash (I2C bus index base 1)", //Error Code 10
	"I2C bus 10 crash (I2C bus index base 1)",
	"I2C bus 11 crash (I2C bus index base 1)",
	"I2C bus 12 crash (I2C bus index base 1)",
	"I2C bus 13 crash (I2C bus index base 1)",
	"I2C bus 14 crash (I2C bus index base 1)",
	"Reserved",
	"Reserved",
	"Reserved",
	"Fan 1 front fault",
	"Fan 1 rear fault", //Error Code 20
	"Fan 2 front fault",
	"Fan 2 rear fault",
	"Fan 3 front fault",
	"Fan 3 rear fault",
	"Fan 4 front fault",
	"Fan 4 rear fault",
	"Fan 5 front fault",
	"Fan 5 rear fault",
	"Fan 6 front fault",
	"Fan 6 rear fault", //Error Code 30
	"Drive board Temp Sensor 1 (left front) critical",
	"Drive board Temp Sensor 2 (left rear) critical",
	"Drive board Temp Sensor 3 (right front) critical",
	"Drive board Temp Sensor 4 (right rear) critical",
	"PEB HSC Temp Sensor critical",
	"BMC Temp Sensor critical",
	"Left ambient temp sensor critical",
	"Right ambient temp sensor critical",
	"PCIe switch front temp tensor critical",
	"PCIe switch temp sensor critical", //Error Code 40
	"Reserved",
	"Reserved",
	"Reserved",
	"Any PEB voltage sensor critical",
	"PEB current sensor critical",
	"Any Drive plane board voltage sensor critical",
	"Any Fan Control Board voltage sensor critical",
	"Fan Control Board current sensor critical",
	"Reserved",
	"SSDC0 SMART Temp critical", //Error Code 50
	"SSDC1 SMART Temp critical",
	"SSDC2 SMART Temp critical",
	"SSDC3 SMART Temp critical",
	"SSDC4 SMART Temp critical",
	"SSDC5 SMART Temp critical",
	"SSDC6 SMART Temp critical",
	"SSDC7 SMART Temp critical",
	"SSDC8 SMART Temp critical",
	"SSDC9 SMART Temp critical",
	"SSDC10 SMART Temp critical", //Error Code 60
	"SSDC11 SMART Temp critical",
	"SSDC12 SMART Temp critical",
	"SSDC13 SMART Temp critical",
	"SSDC14 SMART Temp critical",
	"Reserved",
	"Reserved",
	"Reserved",
	"Reserved",
	"Reserved",
	"SSDC0 fault", //Error Code 70
	"SSDC1 fault",
	"SSDC2 fault",
	"SSDC3 fault",
	"SSDC4 fault",
	"SSDC5 fault",
	"SSDC6 fault",
	"SSDC7 fault",
	"SSDC8 fault",
	"SSDC9 fault",
	"SSDC10 fault", //Error Code 80
	"SSDC11 fault",
	"SSDC12 fault",
	"SSDC13 fault",
	"SSDC14 fault",
	"Reserved",
	"Reserved",
	"Reserved",
	"Reserved",
	"Reserved",
	"PCIe Uplink Error (left side)", //Error Code 90
	"PCIe Uplink Error (right side)",
	"Reserved",
	"Self Tray Pulled-out",
	"Peer Tray Pulled-out",
	"BMC CPU Utilization too high",
	"BMC Memory Utilization too high",
	"Reserved",
	"Reserved",
	"Firmware and hardware mismatch" //Error Code 99
};
