#!/bin/bash

max_retry_count=5
retry_delay_sec=2
mmc_eid=""
service=xyz.openbmc_project.MCTPReactor
root=/au/com/codeconstruct/mctp1
DEFAULT_EID="10"

# retry 10 times to get eid
for attempt in $(seq 1 $max_retry_count); do
    ret=$(busctl call $service $root org.freedesktop.DBus.ObjectManager GetManagedObjects)

    eid=$(echo "$ret" | tr '"' '\n' | awk '
    /\/endpoints\// { ep=$0 }
    /\/MMC/ { if (ep != "") { n=split(ep,a,"/"); print a[n]; ep=""; exit } }')

    if [ -n "$eid" ]; then
        echo "Found MMC EID: $eid"
        mmc_eid=$eid
        break
    fi

    echo "Attempt $attempt: Failed to get MMC EID, retrying..."
    [ "$attempt" -lt "$max_retry_count" ] && sleep "$retry_delay_sec"

done

if [ -z "$mmc_eid" ]; then
    echo "Failed to retrieve MMC EID, using default EID: $DEFAULT_EID"
    mmc_eid=$DEFAULT_EID
fi

pwr_asci_good_gpio_chip="gpiochip2"
pwr_asci_good_line=92

declare -A component_names=(
    ["1"]="Minerva_Aegis_vr_osfp_p3v3"
    ["2"]="Minerva_Aegis_vr_cpu_p0v85_pvdd"
    ["3"]="Minerva_Aegis_vr_cpu_p0v75_pvdd_ch_n"
    ["4"]="Minerva_Aegis_vr_cpu_p0v75_pvdd_ch_s"
    ["5"]="Minerva_Aegis_vr_cpu_p0v75_trvdd_zonea"
    ["6"]="Minerva_Aegis_vr_cpu_p0v75_trvdd_zoneb"
    ["7"]="Minerva_Aegis_vr_cpu_p1v1_vddc_hbm0_2_4"
    ["8"]="Minerva_Aegis_vr_cpu_p0v9_trvdd_zonea"
    ["9"]="Minerva_Aegis_vr_cpu_p0v9_trvdd_zoneb"
    ["10"]="Minerva_Aegis_vr_cpu_p1v1_vddc_hbm1_3_5"
    ["11"]="Minerva_Aegis_vr_cpu_p0v8_vdda_pcie"
)

gpio_value=$(gpioget "$pwr_asci_good_gpio_chip" "$pwr_asci_good_line" 2>/dev/null)
gpioget_status=$?

if [ $gpioget_status -eq 0 ]; then
    echo "power-asci-good value: $gpio_value"

    if [ -n "$gpio_value" ] && [ "$gpio_value" -eq 0 ] 2>/dev/null; then
        echo "Failed to set version: the power-asci-good is not high"
        exit 1
    fi
else
    echo "gpioget failed, skipping check"
fi

get_pldm_object_path() {
    local eid=$1
    local compid=$2

    path=$(busctl tree xyz.openbmc_project.PLDM |
        grep "/xyz/openbmc_project/software/PLDM_Device_Firmware_Device_${eid}_Component_${compid}" |
        sed 's/^[^\/]*//')

    echo "$path"
}

version=""
declare -A found_ids

# Wait for the MMC to be ready
for ((i=1; i<=max_retry_count; i++)); do
    output=$(pldmtool fw_update GetFwParams -m "$mmc_eid" -n 5 |
                jq --raw-output '.ComponentParameterEntries[] |
                (.ComponentIdentifier | tostring) + "#" +
                .ActiveComponentVersionString')

    if [ -z "$output" ]; then
        echo "pldmtool returned empty output, retry after ${retry_delay_sec} seconds (count: ${i})"
        sleep "$retry_delay_sec"
    else
        while IFS="#" read -r compId version; do
            component_name=${component_names[$compId]:-"Unknown"}
            if [ "$component_name" == "Unknown" ]; then
                continue
            fi

            echo "$component_name version: $version"
            found_ids[$compId]=1

            busctl set-property \
                xyz.openbmc_project.Settings \
                "/xyz/openbmc_project/software/chassis/$component_name" \
                xyz.openbmc_project.Software.Version \
                Version "s" "$version"

            pldmObjPath=$(get_pldm_object_path "$mmc_eid" "$compId")
            if [ -n "$pldmObjPath" ]; then
                busctl set-property \
                    xyz.openbmc_project.PLDM \
                    "$pldmObjPath" \
                    xyz.openbmc_project.Software.Version \
                    Version "s" "$version"
            fi

        done <<< "$output"

        for compId in "${!component_names[@]}"; do
            if [ -z "${found_ids[$compId]}" ]; then
                component_name=${component_names[$compId]}
                echo "$component_name version: NA"

                busctl set-property \
                    xyz.openbmc_project.Settings \
                    "/xyz/openbmc_project/software/chassis/$component_name" \
                    xyz.openbmc_project.Software.Version \
                    Version "s" "NA"
            fi
        done

        break
    fi
done

