#!/bin/bash
set -e

version=$(fw-util bmc --version tpm | awk '{print $NF}')
echo "version: $version"

busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/Catalina_SCM_tpm \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"
