#!/bin/bash
set -e

max_retry_count=30
retry_delay_sec=10

for ((i=1; i<=max_retry_count; i++))
do
    if ! version=$(hmc-util --version HGX_FW_GPU_1); then
        if ! version=$(hmc-util --version HGX_FW_GPU_2); then
            echo "failed to get version, retry after ${retry_delay_sec} seconds (count: ${i})"
            sleep "$retry_delay_sec"
            continue
        fi
    fi

    version=$(echo "$version" | awk '{print $NF}')
    echo "version: $version"
    busctl set-property \
        xyz.openbmc_project.Settings \
        /xyz/openbmc_project/software/chassis/HGX_gpu_1 \
        xyz.openbmc_project.Software.Version \
        Version "s" "$version"
    exit 0
done

exit 1
