#!/bin/bash
set -e

PDB_VR_TYPE="raa"

# If any of address 0x63 - 0x67 exist, Delta brick is uesd on this PDB board
if [ "$(i2cdetect -y -q 19 0x63 0x67 | awk '/60:/ {print $2 $3 $4 $5 $6}')" != "----------" ]; then
    PDB_VR_TYPE="delta"
fi
kv set pdb_vr_type "${PDB_VR_TYPE}"

# Set VR version with empty string if VR not exist
if [ "$PDB_VR_TYPE" = "delta" ]; then
    busctl set-property \
        xyz.openbmc_project.Settings \
        /xyz/openbmc_project/software/chassis/Catalina_PDB_vr_aux \
        xyz.openbmc_project.Software.Version \
        Version "s" ""
    exit 0
fi

max_retry_count=30
retry_delay_sec=3

for ((i=1; i<=max_retry_count; i++))
do
    if ! version="$(fw-util pdb --version vr_aux)"; then
        echo "failed to get version, retry after ${retry_delay_sec} seconds (count: ${i})"
        sleep "$retry_delay_sec"
    else
        version="$(echo "$version" | awk -F ',' '{print $1}' | awk -F ' ' '{print $3, $4}')"
        echo "version: $version"

        busctl set-property \
            xyz.openbmc_project.Settings \
            /xyz/openbmc_project/software/chassis/Catalina_PDB_vr_aux \
            xyz.openbmc_project.Software.Version \
            Version "s" "$version"
        exit 0
    fi
done

exit 1
