#!/bin/sh
# Copyright 2017-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA

. bmc-lib $*

echo "Logging into $BMC_IP" >> ~/.bmc_history
if [ "$PROXY" == "" ]; then
  if [ $(wait_1hop $BMC_IP) != "done" ]; then
    echo "$BMC_IP is not reachable"
    exit -1
  fi
  cmd_1hop root@$BMC_IP $BMC_PASSWORD ${ARGUMENTS[@]}
else
  if [ $(wait_2hop $PROXY $PROXY_PASSWORD $BMC_IP) != "done" ]; then
    echo "$BMC_IP is not reachable"
    exit -1
  fi
  cmd_2hop $PROXY $PROXY_PASSWORD root@$BMC_IP $BMC_PASSWORD ${ARGUMENTS[@]}
fi
bmc_set_last $BMC_ALIAS $BMC_IP $BMC_PASSWORD $PROXY $PROXY_PASSWORD
