RAINIERA7_ASSUMED_PROVIDERS = ""
RAINIERA7_IMAGE_FSTYPES_REMOVE = ""

PREFERRED_PROVIDER_u-boot-fw-utils = "libubootenv"

PREFERRED_PROVIDER_virtual/kernel = "linux-aspeed"

PREFERRED_VERSION_u-boot-aspeed-sdk = "v2023.10%"

KERNEL_DEVICETREE = "aspeed/${KMACHINE}-bmc-facebook-${MACHINE}.dtb"
UBOOT_DEVICETREE = "ast2700-facebook"

PREFERRED_PROVIDER_virtual/bootmcu = "zephyr-aspeed-bootmcu"

ZEPHYR_TOOLCHAIN_VARIANT = "zephyr"
PREFERRED_VERSION_zephyr-sdk-native = "0.16.9"
PREFERRED_VERSION_zephyr-kernel ??= "3.7.0"
