FILESEXTRAPATHS:prepend := "${THISDIR}/linux-aspeed:"

SRC_URI:append = " file://1000-ARM-dts-aspeed-Harma-Revise-node-name.patch"
SRC_URI:append = " file://1001-ARM-dts-aspeed-Harma-Add-retimer-device.patch"
SRC_URI:append = " file://1002-ARM-dts-aspeed-Harma-Modify-GPIO-line-name.patch"
SRC_URI:append = " file://1003-ARM-dts-aspeed-Harma-add-lpc_pcc-device.patch"
SRC_URI:append = " file://1004-ARM-dts-aspeed-Harma-stop-NIC-run-time-polling.patch"
SRC_URI:append = " file://1005-ARM-dts-aspeed-Harma-read-cpu-temp-and-power.patch"
SRC_URI:append = " file://1006-ARM-dts-aspeed-Harma-set-ncsi-package-eq-1.patch"
SRC_URI:append = " file://1007-ARM-dts-aspeed-Harma-Setting-i3c-to-i2c-device.patch"
