/* Copyright 2020-present Facebook. All Rights Reserved.
 *
 * This file contains code to support IPMI2.0 Specificaton available @
 * http://www.intel.com/content/www/us/en/servers/ipmi/ipmi-specifications.html
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#include <stdio.h>
#include <stdlib.h>
#include <syslog.h>
#include <stdbool.h>
#ifdef CONFIG_GRANDCANYON2
#include <openbmc/obmc-i2c.h>
#endif
#include "fbgc_gpio.h"

#ifdef CONFIG_GRANDCANYON2
#define UIC_SIDEA 1
#define UIC_SIDEB 2
#endif

#define ARRAY_SIZE(x) (sizeof(x) / sizeof((x)[0]))

/* GPIO Expander gpio table */
#ifdef CONFIG_GRANDCANYON2
/* ---------------------------
 * hack stage table (common enum indices)
 * --------------------------- */
gpio_cfg gpio_expander_gpio_table_hack[MAX_GPIO_EXPANDER_GPIO_PINS + 1] = {
  /* shadow_name, pin_name, direction, value */

  // COMP_PRSNT_N: P00 (748)
  [GPIO_COMP_PRSNT_N] =
  {"COMP_PRSNT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // FAN_0_INS_N: P01 (749)
  [GPIO_FAN_0_INS_N] =
  {"FAN_0_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // FAN_1_INS_N: P02 (750)
  [GPIO_FAN_1_INS_N] =
  {"FAN_1_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // FAN_2_INS_N: P03 (751)
  [GPIO_FAN_2_INS_N] =
  {"FAN_2_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // FAN_3_INS_N: P04 (752)
  [GPIO_FAN_3_INS_N] =
  {"FAN_3_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // UIC_RMT_INS_N: P05 (753)
  [GPIO_UIC_RMT_INS_N] =
  {"UIC_RMT_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_LOC_INS_N: P06 (754)
  [GPIO_SCC_LOC_INS_N] =
  {"SCC_LOC_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_RMT_INS_N: P07 (755)
  [GPIO_SCC_RMT_INS_N] =
  {"SCC_RMT_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_LOC_TYPE_0: P10 (756)
  [GPIO_SCC_LOC_TYPE_0] =
  {"SCC_LOC_TYPE_0", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_RMT_TYPE_0: P11 (757)
  [GPIO_SCC_RMT_TYPE_0] =
  {"SCC_RMT_TYPE_0", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_STBY_PGOOD: P12 (758)
  [GPIO_SCC_STBY_PGOOD] =
  {"SCC_STBY_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_FULL_PGOOD: P13 (759)
  [GPIO_SCC_FULL_PGOOD] =
  {"SCC_FULL_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // COMP_PGOOD: P14 (760)
  [GPIO_COMP_PGOOD] =
  {"COMP_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // DRAWER_CLOSED_N: P15 (761)
  [GPIO_DRAWER_CLOSED_N] =
  {"DRAWER_CLOSED_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // E1S_1_PRSNT_N: P16 (762)
  [GPIO_E1S_1_PRSNT_N] =
  {"E1S_1_PRSNT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // E1S_2_PRSNT_N: P17 (763)
  [GPIO_E1S_2_PRSNT_N] =
  {"E1S_2_PRSNT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // I2C_E1S_1_RST_N: P00 (764)
  [GPIO_I2C_E1S_1_RST_N] =
  {"I2C_E1S_1_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // I2C_E1S_2_RST_N: P01 (765)
  [GPIO_I2C_E1S_2_RST_N] =
  {"I2C_E1S_2_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // E1S_1_LED_ACT: P02 (766)
  [GPIO_E1S_1_LED_ACT] =
  {"E1S_1_LED_ACT", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // E1S_2_LED_ACT: P03 (767)
  [GPIO_E1S_2_LED_ACT] =
  {"E1S_2_LED_ACT", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // SCC_STBY_PWR_EN: P04 (768)
  [GPIO_SCC_STBY_PWR_EN] =
  {"SCC_STBY_PWR_EN", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // SCC_FULL_PWR_EN: P05 (769)
  [GPIO_SCC_FULL_PWR_EN] =
  {"SCC_FULL_PWR_EN", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // BMC_EXP_SOFT_RST_N: P06 (770)
  [GPIO_BMC_EXP_SOFT_RST_N] =
  {"BMC_EXP_SOFT_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // UIC_COMP_BIC_RST_N: P07 (771)
  [GPIO_UIC_COMP_BIC_RST_N] =
  {"UIC_COMP_BIC_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // E1S_1_3V3EFUSE_PGOOD: P10 (772)
  [GPIO_E1S_1_3V3EFUSE_PGOOD] =
  {"E1S_1_3V3EFUSE_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // E1S_2_3V3EFUSE_PGOOD: P11 (773)
  [GPIO_E1S_2_3V3EFUSE_PGOOD] =
  {"E1S_2_3V3EFUSE_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // P12V_NIC_FAULT_N: P12 (774)
  [GPIO_P12V_NIC_STATUS_N] =
  {"P12V_NIC_FAULT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // P3V3_NIC_FAULT_N: P13 (775)
  [GPIO_P3V3_NIC_STATUS_N] =
  {"P3V3_NIC_FAULT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_POR_RST_N: P14 (776)
  [GPIO_SCC_POR_RST_N] =
  {"SCC_POR_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // IOC_T7_SYS_PGOOD: P15 (777)
  [GPIO_IOC_T7_SYS_PGOOD] =
  {"IOC_T7_SYS_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // BMC_COMP_BLED: P16 (778)
  [GPIO_BMC_COMP_BLED] =
  {"BMC_COMP_BLED", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // BMC_COMP_YLED: P17 (779)
  [GPIO_BMC_COMP_YLED] =
  {"BMC_COMP_YLED", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // LAST
  [MAX_GPIO_EXPANDER_GPIO_PINS] = 
  {NULL, NULL, GPIO_DIRECTION_INVALID, GPIO_VALUE_INVALID}
};

/* ---------------------------
 * DVT stage A side (common enum indices; A-side shadow names)
 * --------------------------- */
gpio_cfg gpio_expander_gpio_table_dvt_a[MAX_GPIO_EXPANDER_GPIO_PINS + 1] = {
  /* bus9 U14 (A) */
  [GPIO_COMP_PRSNT_N]         = {"COMP_A_PRSNT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FAN_0_INS_N]          = {"FAN_0_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FAN_1_INS_N]          = {"FAN_1_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FAN_2_INS_N]          = {"FAN_2_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FAN_3_INS_N]          = {"FAN_3_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_UIC_RMT_INS_N]        = {"UIC_RMT_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_LOC_INS_N]        = {"SCC_LOC_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_RMT_INS_N]        = {"SCC_RMT_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_LOC_TYPE_0]       = {"SCC_LOC_TYPE_0",           NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_RMT_TYPE_0]       = {"SCC_RMT_TYPE_0",           NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_STBY_PGOOD]       = {"SCC_A_STBY_PGOOD",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_FULL_PGOOD]       = {"SCC_A_FULL_PGOOD",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_COMP_PGOOD]           = {"COMP_A_PGOOD",           NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_DRAWER_CLOSED_N]      = {"DRAWER_CLOSED_N",        NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_1_PRSNT_N]        = {"E1SA_1_PRSNT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_PRSNT_N]        = {"E1SA_2_PRSNT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},

  /* bus9 U15 (A) */
  [GPIO_I2C_E1S_1_RST_N]      = {"I2C_E1SA_1_RST_N",       NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_I2C_E1S_2_RST_N]      = {"I2C_E1SA_2_RST_N",       NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_E1S_1_LED_ACT]        = {"E1SA_1_LED_ACT",         NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  [GPIO_E1S_2_LED_ACT]        = {"E1SA_2_LED_ACT",         NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  [GPIO_SCC_STBY_PWR_EN]      = {"SCC_A_STBY_PWR_EN",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_SCC_FULL_PWR_EN]      = {"SCC_A_FULL_PWR_EN",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_BMC_EXP_SOFT_RST_N]   = {"BMC_A_EXP_A_SOFT_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_UIC_COMP_BIC_RST_N]   = {"UIC_A_COMP_A_BIC_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_E1S_1_3V3EFUSE_PGOOD] = {"E1SA_1_3V3EFUSE_PGOOD",  NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_3V3EFUSE_PGOOD] = {"E1SA_2_3V3EFUSE_PGOOD",  NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  /* In DVT: NIC signals use PWRGD */
  [GPIO_P12V_NIC_STATUS_N] = {"PWRGD_P12V_NIC_A", NULL, GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  [GPIO_P3V3_NIC_STATUS_N] = {"PWRGD_P3V3_NIC_A", NULL, GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  [GPIO_SCC_POR_RST_N]        = {"SCC_A_POR_RST_N",        NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_IOC_T7_SYS_PGOOD]     = {"IOC_T7_SYS_PGOOD",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_BMC_COMP_BLED]        = {"BMC_A_COMP_A_BLED",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  [GPIO_BMC_COMP_YLED]        = {"BMC_A_COMP_A_YLED",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},

  /* bus11 U58 (A) */
  [GPIO_E1S_1_12VEFUSE_PGOOD] = {"E1SA_1_12VEFUSE_PGOOD",  NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FM_BMC_RST_R_RTCRST]  = {"FM_BMC_RST_A_R_RTCRST",  NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  [GPIO_SMB_NIC_INA233_ALRT_N]= {"SMB_NIC_A_INA233_ALRT_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_1_12VEFUSE_FLT_R_N]= {"E1SA_1_12VEFUSE_FLT_R_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_1_3V3EFUSE_FLT_R_N]= {"E1SA_1_3V3EFUSE_FLT_R_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_12VEFUSE_FLT_R_N]= {"E1SA_2_12VEFUSE_FLT_R_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_3V3EFUSE_FLT_R_N]= {"E1SA_2_3V3EFUSE_FLT_R_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_12VEFUSE_PGOOD] = {"E1SA_2_12VEFUSE_PGOOD",  NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},

  /* bus11 U126 (A) */
  [GPIO_ALRT_P12V_STBY_SCC_N] = {"ALRT_P12V_STBY_SCC_N",   NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P3V3_STBY_PG_R]       = {"P3V3_STBY_A_PG_R",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P5V_1_PG]             = {"P5V_A_1_PG",             NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P5V_2_PG]             = {"P5V_A_2_PG",             NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P5V_3_PG]             = {"P5V_A_3_PG",             NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P5V_4_PG]             = {"P5V_A_4_PG",             NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FM_HSC_FAULT_N]       = {"FM_HSC_FAULT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},

  [MAX_GPIO_EXPANDER_GPIO_PINS] = {NULL, NULL, GPIO_DIRECTION_INVALID, GPIO_VALUE_INVALID},
};

/* ---------------------------
 * DVT stage B side (common enum indices; B-side shadow names)
 * --------------------------- */
gpio_cfg gpio_expander_gpio_table_dvt_b[MAX_GPIO_EXPANDER_GPIO_PINS + 1] = {
  /* bus9 U17 (B) */
  [GPIO_COMP_PRSNT_N]         = {"COMP_B_PRSNT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FAN_0_INS_N]          = {"FAN_0_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FAN_1_INS_N]          = {"FAN_1_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FAN_2_INS_N]          = {"FAN_2_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FAN_3_INS_N]          = {"FAN_3_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_UIC_RMT_INS_N]        = {"UIC_RMT_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_LOC_INS_N]        = {"SCC_LOC_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_RMT_INS_N]        = {"SCC_RMT_INS_N",            NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_LOC_TYPE_0]       = {"SCC_LOC_TYPE_0",           NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_RMT_TYPE_0]       = {"SCC_RMT_TYPE_0",           NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_STBY_PGOOD]       = {"SCC_B_STBY_PGOOD",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_SCC_FULL_PGOOD]       = {"SCC_B_FULL_PGOOD",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_COMP_PGOOD]           = {"COMP_B_PGOOD",           NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_DRAWER_CLOSED_N]      = {"DRAWER_CLOSED_N",        NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_1_PRSNT_N]        = {"E1SB_1_PRSNT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_PRSNT_N]        = {"E1SB_2_PRSNT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},

  /* bus9 U18 */
  [GPIO_I2C_E1S_1_RST_N]      = {"I2C_E1SB_1_RST_N",       NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_I2C_E1S_2_RST_N]      = {"I2C_E1SB_2_RST_N",       NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_E1S_1_LED_ACT]        = {"E1SB_1_LED_ACT",         NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  [GPIO_E1S_2_LED_ACT]        = {"E1SB_2_LED_ACT",         NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  [GPIO_SCC_STBY_PWR_EN]      = {"SCC_B_STBY_PWR_EN",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_SCC_FULL_PWR_EN]      = {"SCC_B_FULL_PWR_EN",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_BMC_EXP_SOFT_RST_N]   = {"BMC_B_EXP_B_SOFT_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_UIC_COMP_BIC_RST_N]   = {"UIC_B_COMP_B_BIC_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  [GPIO_E1S_1_3V3EFUSE_PGOOD] = {"E1SB_1_3V3EFUSE_PGOOD",  NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_3V3EFUSE_PGOOD] = {"E1SB_2_3V3EFUSE_PGOOD",  NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  /* DVT: NIC uses PWRGD */
  [GPIO_P12V_NIC_STATUS_N] = {"PWRGD_P12V_NIC_B", NULL, GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  [GPIO_P3V3_NIC_STATUS_N] = {"PWRGD_P3V3_NIC_B", NULL, GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  [GPIO_SCC_POR_RST_N]        = {"SCC_B_POR_RST_N",        NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  
  /* B-side U18 P15 is empty → IOC_T7_SYS_PGOOD not present on B side */
  [GPIO_IOC_T7_SYS_PGOOD]     = {NULL, NULL, GPIO_DIRECTION_INVALID, GPIO_VALUE_INVALID},

  [GPIO_BMC_COMP_BLED]        = {"BMC_B_COMP_B_BLED",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  [GPIO_BMC_COMP_YLED]        = {"BMC_B_COMP_B_YLED",      NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},

  /* bus11 U59 (B) */
  [GPIO_E1S_1_12VEFUSE_PGOOD] = {"E1SB_1_12VEFUSE_PGOOD",  NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FM_BMC_RST_R_RTCRST]  = {"FM_BMC_RST_B_R_RTCRST",  NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  [GPIO_SMB_NIC_INA233_ALRT_N]= {"SMB_NIC_B_INA233_ALRT_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_1_12VEFUSE_FLT_R_N]= {"E1SB_1_12VEFUSE_FLT_R_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_1_3V3EFUSE_FLT_R_N]= {"E1SB_1_3V3EFUSE_FLT_R_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_12VEFUSE_FLT_R_N]= {"E1SB_2_12VEFUSE_FLT_R_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_3V3EFUSE_FLT_R_N]= {"E1SB_2_3V3EFUSE_FLT_R_N",NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_E1S_2_12VEFUSE_PGOOD] = {"E1SB_2_12VEFUSE_PGOOD",  NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},

  /* U126 (B) — on RDPB */
  [GPIO_ALRT_P12V_STBY_SCC_N] = {"ALRT_P12V_STBY_SCC_N",   NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P3V3_STBY_PG_R]       = {"P3V3_STBY_B_PG_R",       NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P5V_1_PG]             = {"P5V_B_1_PG",             NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P5V_2_PG]             = {"P5V_B_2_PG",             NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P5V_3_PG]             = {"P5V_B_3_PG",             NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_P5V_4_PG]             = {"P5V_B_4_PG",             NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  [GPIO_FM_HSC_FAULT_N]       = {"FM_HSC_FAULT_N",         NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},

  [MAX_GPIO_EXPANDER_GPIO_PINS] = {NULL, NULL, GPIO_DIRECTION_INVALID, GPIO_VALUE_INVALID},
};
#else
/* GPIO Expander gpio table */
gpio_cfg gpio_expander_gpio_table[] = {
  /* shadow_name, pin_name, direction, value */

  // COMP_PRSNT_N: P00 (748)
  [GPIO_COMP_PRSNT_N] =
  {"COMP_PRSNT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // FAN_0_INS_N: P01 (749)
  [GPIO_FAN_0_INS_N] =
  {"FAN_0_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // FAN_1_INS_N: P02 (750)
  [GPIO_FAN_1_INS_N] =
  {"FAN_1_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // FAN_2_INS_N: P03 (751)
  [GPIO_FAN_2_INS_N] =
  {"FAN_2_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // FAN_3_INS_N: P04 (752)
  [GPIO_FAN_3_INS_N] =
  {"FAN_3_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // UIC_RMT_INS_N: P05 (753)
  [GPIO_UIC_RMT_INS_N] =
  {"UIC_RMT_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_LOC_INS_N: P06 (754)
  [GPIO_SCC_LOC_INS_N] =
  {"SCC_LOC_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_RMT_INS_N: P07 (755)
  [GPIO_SCC_RMT_INS_N] =
  {"SCC_RMT_INS_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_LOC_TYPE_0: P10 (756)
  [GPIO_SCC_LOC_TYPE_0] =
  {"SCC_LOC_TYPE_0", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_RMT_TYPE_0: P11 (757)
  [GPIO_SCC_RMT_TYPE_0] =
  {"SCC_RMT_TYPE_0", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_STBY_PGOOD: P12 (758)
  [GPIO_SCC_STBY_PGOOD] =
  {"SCC_STBY_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_FULL_PGOOD: P13 (759)
  [GPIO_SCC_FULL_PGOOD] =
  {"SCC_FULL_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // COMP_PGOOD: P14 (760)
  [GPIO_COMP_PGOOD] =
  {"COMP_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // DRAWER_CLOSED_N: P15 (761)
  [GPIO_DRAWER_CLOSED_N] =
  {"DRAWER_CLOSED_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // E1S_1_PRSNT_N: P16 (762)
  [GPIO_E1S_1_PRSNT_N] =
  {"E1S_1_PRSNT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // E1S_2_PRSNT_N: P17 (763)
  [GPIO_E1S_2_PRSNT_N] =
  {"E1S_2_PRSNT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // I2C_E1S_1_RST_N: P00 (764)
  [GPIO_I2C_E1S_1_RST_N] =
  {"I2C_E1S_1_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // I2C_E1S_2_RST_N: P01 (765)
  [GPIO_I2C_E1S_2_RST_N] =
  {"I2C_E1S_2_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // E1S_1_LED_ACT: P02 (766)
  [GPIO_E1S_1_LED_ACT] =
  {"E1S_1_LED_ACT", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // E1S_2_LED_ACT: P03 (767)
  [GPIO_E1S_2_LED_ACT] =
  {"E1S_2_LED_ACT", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // SCC_STBY_PWR_EN: P04 (768)
  [GPIO_SCC_STBY_PWR_EN] =
  {"SCC_STBY_PWR_EN", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // SCC_FULL_PWR_EN: P05 (769)
  [GPIO_SCC_FULL_PWR_EN] =
  {"SCC_FULL_PWR_EN", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // BMC_EXP_SOFT_RST_N: P06 (770)
  [GPIO_BMC_EXP_SOFT_RST_N] =
  {"BMC_EXP_SOFT_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // UIC_COMP_BIC_RST_N: P07 (771)
  [GPIO_UIC_COMP_BIC_RST_N] =
  {"UIC_COMP_BIC_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // E1S_1_3V3EFUSE_PGOOD: P10 (772)
  [GPIO_E1S_1_3V3EFUSE_PGOOD] =
  {"E1S_1_3V3EFUSE_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // E1S_2_3V3EFUSE_PGOOD: P11 (773)
  [GPIO_E1S_2_3V3EFUSE_PGOOD] =
  {"E1S_2_3V3EFUSE_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // P12V_NIC_FAULT_N: P12 (774)
  [GPIO_P12V_NIC_FAULT_N] =
  {"P12V_NIC_FAULT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // P3V3_NIC_FAULT_N: P13 (775)
  [GPIO_P3V3_NIC_FAULT_N] =
  {"P3V3_NIC_FAULT_N", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // SCC_POR_RST_N: P14 (776)
  [GPIO_SCC_POR_RST_N] =
  {"SCC_POR_RST_N", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // IOC_T7_SYS_PGOOD: P15 (777)
  [GPIO_IOC_T7_SYS_PGOOD] =
  {"IOC_T7_SYS_PGOOD", NULL, GPIO_DIRECTION_IN,  GPIO_VALUE_INVALID},
  // BMC_COMP_BLED: P16 (778)
  [GPIO_BMC_COMP_BLED] =
  {"BMC_COMP_BLED", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // BMC_COMP_YLED: P17 (779)
  [GPIO_BMC_COMP_YLED] =
  {"BMC_COMP_YLED", NULL, GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // LAST
  {NULL, NULL, GPIO_DIRECTION_INVALID, GPIO_VALUE_INVALID}
};
#endif /* CONFIG_GRANDCANYON2 */

gpio_cfg bmc_gpio_table[] = {
  /* shadow_name, pin_name, direction, value */

  // FPGA_CRCERROR, GPIOB0 (824)
  [GPIO_FPGA_CRCERROR] =
  {"FPGA_CRCERROR", "GPIOB0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // FPGA_NCONFIG, GPIOB1 (825)
  [GPIO_FPGA_NCONFIG] =
  {"FPGA_NCONFIG", "GPIOB1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_SCC_FAULT_IN_R, GPIOB2 (826)
  [GPIO_BMC_SCC_FAULT_IN_R] =
  {"BMC_SCC_FAULT_IN_R", "GPIOB2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // HSC_P12V_DPB_FAULT_N_IN_R, GPIOB4 (828)
  [GPIO_HSC_P12V_DPB_FAULT_N_IN_R] =
  {"HSC_P12V_DPB_FAULT_N_IN_R", "GPIOB4", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // HSC_COMP_FAULT_N_IN_R, GPIOB5 (829)
  [GPIO_HSC_COMP_FAULT_N_IN_R] =
  {"HSC_COMP_FAULT_N_IN_R", "GPIOB5", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_NIC_PWRBRK_R, GPIOC1 (833)
  [GPIO_BMC_NIC_PWRBRK_R] =
  {"BMC_NIC_PWRBRK_R", "GPIOC1", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // BMC_NIC_SMRST_N_R, GPIOC2 (834)
  [GPIO_BMC_NIC_SMRST_N_R] =
  {"BMC_NIC_SMRST_N_R", "GPIOC2", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // NIC_WAKE_BMC_N, GPIOC3 (835)
  [GPIO_NIC_WAKE_BMC_N] =
  {"NIC_WAKE_BMC_N", "GPIOC3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_NIC_FULL_PWR_EN_R, GPIOC4 (836)
  [GPIO_BMC_NIC_FULL_PWR_EN_R] =
  {"BMC_NIC_FULL_PWR_EN_R", "GPIOC4", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // NIC_FULL_PWR_PG, GPIOC5 (837)
  [GPIO_NIC_FULL_PWR_PG] =
  {"NIC_FULL_PWR_PG", "GPIOC5", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BOARD_REV_ID0, GPIOH0 (872)
  [GPIO_BOARD_REV_ID0] =
  {"BOARD_REV_ID0", "GPIOH0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BOARD_REV_ID1, GPIOH1 (873)
  [GPIO_BOARD_REV_ID1] =
  {"BOARD_REV_ID1", "GPIOH1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BOARD_REV_ID2, GPIOH2 (874)
  [GPIO_BOARD_REV_ID2] =
  {"BOARD_REV_ID2", "GPIOH2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // EN_ASD_DEBUG, GPIOI5 (885)
  [GPIO_EN_ASD_DEBUG] =
  {"EN_ASD_DEBUG", "GPIOI5", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_RST_BTN_N, GPIOI7 (887)
  [GPIO_DEBUG_RST_BTN_N] =
  {"DEBUG_RST_BTN_N", "GPIOI7", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // E1S_1_P3V3_PG_R, GPIOL6 (910)
  [GPIO_E1S_1_P3V3_PG_R] =
  {"E1S_1_P3V3_PG_R", "GPIOL6", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // E1S_2_P3V3_PG_R, GPIOL7 (911)
  [GPIO_E1S_2_P3V3_PG_R] =
  {"E1S_2_P3V3_PG_R", "GPIOL7", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_FPGA_UART_SEL0_R, GPIOM0 (912)
  [GPIO_BMC_FPGA_UART_SEL0_R] =
  {"BMC_FPGA_UART_SEL0_R", "GPIOM0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_FPGA_UART_SEL1_R, GPIOM1 (913)
  [GPIO_BMC_FPGA_UART_SEL1_R] =
  {"BMC_FPGA_UART_SEL1_R", "GPIOM1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_FPGA_UART_SEL2_R, GPIOM2 (914)
  [GPIO_BMC_FPGA_UART_SEL2_R] =
  {"BMC_FPGA_UART_SEL2_R", "GPIOM2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_FPGA_UART_SEL3_R, GPIOM3 (915)
  [GPIO_BMC_FPGA_UART_SEL3_R] =
  {"BMC_FPGA_UART_SEL3_R", "GPIOM3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_BMC_UART_SEL_R, GPIOM4 (916)
  [GPIO_DEBUG_BMC_UART_SEL_R] =
  {"DEBUG_BMC_UART_SEL_R", "GPIOM4", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_GPIO_BMC_1, GPION0 (920)
  [GPIO_DEBUG_PWR_BTN_N] =
  {"DEBUG_PWR_BTN_N", "GPION0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_GPIO_BMC_2, GPION1 (921)
  [GPIO_DEBUG_GPIO_BMC_2] =
  {"DEBUG_GPIO_BMC_2", "GPION1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_GPIO_BMC_3, GPION2 (922)
  [GPIO_DEBUG_GPIO_BMC_3] =
  {"DEBUG_GPIO_BMC_3", "GPION2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_GPIO_BMC_4, GPION3 (923)
  [GPIO_DEBUG_GPIO_BMC_4] =
  {"DEBUG_GPIO_BMC_4", "GPION3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_GPIO_BMC_5, GPION4 (924)
  [GPIO_DEBUG_GPIO_BMC_5] =
  {"DEBUG_GPIO_BMC_5", "GPION4", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_GPIO_BMC_6, GPION5 (925)
  [GPIO_DEBUG_GPIO_BMC_6] =
  {"DEBUG_GPIO_BMC_6", "GPION5", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // USB_OC_N1, GPIOO3 (931)
  [GPIO_USB_OC_N1] =
  {"USB_OC_N1", "GPIOO3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // SCC_I2C_EN_R, GPIOO4 (932)
  [GPIO_SCC_I2C_EN_R] =
  {"SCC_I2C_EN_R", "GPIOO4", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // BMC_READY_R, GPIOO5 (933)
  [GPIO_BMC_READY_R] =
  {"BMC_READY_R", "GPIOO5", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // LED_POSTCODE_0, GPIOO7 (935)
  [GPIO_LED_POSTCODE_0] =
  {"LED_POSTCODE_0", "GPIOO7", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // LED_POSTCODE_1, GPIOP0 (936)
  [GPIO_LED_POSTCODE_1] =
  {"LED_POSTCODE_1", "GPIOP0", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // LED_POSTCODE_2, GPIOP1 (937)
  [GPIO_LED_POSTCODE_2] =
  {"LED_POSTCODE_2", "GPIOP1", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // LED_POSTCODE_3, GPIOP2 (938)
  [GPIO_LED_POSTCODE_3] =
  {"LED_POSTCODE_3", "GPIOP2", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // LED_POSTCODE_4, GPIOP3 (939)
  [GPIO_LED_POSTCODE_4] =
  {"LED_POSTCODE_4", "GPIOP3", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // LED_POSTCODE_5, GPIOP4 (940)
  [GPIO_LED_POSTCODE_5] =
  {"LED_POSTCODE_5", "GPIOP4", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // LED_POSTCODE_6, GPIOP5 (941)
  [GPIO_LED_POSTCODE_6] =
  {"LED_POSTCODE_6", "GPIOP5", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // LED_POSTCODE_7, GPIOP6 (942)
  [GPIO_LED_POSTCODE_7] =
  {"LED_POSTCODE_7", "GPIOP6", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // BMC_LOC_HEARTBEAT_R, GPIOQ1 (945)
  [GPIO_BMC_LOC_HEARTBEAT_R] =
  {"BMC_LOC_HEARTBEAT_R", "GPIOQ1", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // BIC_READY_IN, GPIOQ6 (950)
  [GPIO_BIC_READY_IN] =
  {"BIC_READY_IN", "GPIOQ6", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // COMP_STBY_PG_IN, GPIOQ7 (951)
  [GPIO_COMP_STBY_PG_IN] =
  {"COMP_STBY_PG_IN", "GPIOQ7", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // UIC_LOC_TYPE_IN, GPIOR1 (953)
  [GPIO_UIC_LOC_TYPE_IN] =
  {"UIC_LOC_TYPE_IN", "GPIOR1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // UIC_RMT_TYPE_IN, GPIOR2 (954)
  [GPIO_UIC_RMT_TYPE_IN] =
  {"UIC_RMT_TYPE_IN", "GPIOR2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_COMP_PWR_EN_R, GPIOR4 (956)
  [GPIO_BMC_COMP_PWR_EN_R] =
  {"BMC_COMP_PWR_EN_R", "GPIOR4", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // EXT_MINISAS_INS_OR_N_IN, GPIOR6 (958)
  [GPIO_EXT_MINISAS_INS_OR_N_IN] =
  {"EXT_MINISAS_INS_OR_N_IN", "GPIOR6", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // NIC_PRSNTB3_N, GPIOS0 (960)
  [GPIO_NIC_PRSNTB3_N] =
  {"NIC_PRSNTB3_N", "GPIOS0", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // FM_BMC_TPM_PRSNT_N, GPIOS2 (962)
  [GPIO_FM_BMC_TPM_PRSNT_N] =
  {"FM_BMC_TPM_PRSNT_N", "GPIOS2", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // DEBUG_CARD_PRSNT_N, GPIOS3 (963)
  [GPIO_DEBUG_CARD_PRSNT_N] =
  {"DEBUG_CARD_PRSNT_N", "GPIOS3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_RST_BTN_N_R, GPIOV0 (984)
  [GPIO_BMC_RST_BTN_N_R] =
  {"BMC_RST_BTN_N_R", "GPIOV0", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // PCIE_COMP_UIC_RST_N, GPIOV1 (985)
  [GPIO_PCIE_COMP_UIC_RST_N] =
  {"PCIE_COMP_UIC_RST_N", "GPIOV1", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_COMP_SYS_RST_N_R, GPIOV2 (986)
  [GPIO_BMC_COMP_SYS_RST_N_R] =
  {"BMC_COMP_SYS_RST_N_R", "GPIOV2", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // BMC_PWRGD_NIC, GPIOV3 (987)
  [GPIO_BMC_PWRGD_NIC] =
  {"BMC_PWRGD_NIC", "GPIOV3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // BMC_LED_STATUS_BLUE_EN_R, GPIOV4 (988)
  [GPIO_BMC_LED_STATUS_BLUE_EN_R] =
  {"BMC_LED_STATUS_BLUE_EN_R", "GPIOV4", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // BMC_LED_STATUS_YELLOW_EN_R, GPIOV5 (989)
  [GPIO_BMC_LED_STATUS_YELLOW_EN_R] =
  {"BMC_LED_STATUS_YELLOW_EN_R", "GPIOV5", GPIO_DIRECTION_OUT, GPIO_VALUE_LOW},
  // BMC_LED_PWR_BTN_EN_R, GPIOV6 (990)
  [GPIO_BMC_LED_PWR_BTN_EN_R] =
  {"BMC_LED_PWR_BTN_EN_R", "GPIOV6", GPIO_DIRECTION_OUT, GPIO_VALUE_HIGH},
  // BMC_UIC_LOCATION_IN, GPIOY3 (1011)
  [GPIO_BMC_UIC_LOCATION_IN] =
  {"BMC_UIC_LOCATION_IN", "GPIOY3", GPIO_DIRECTION_IN, GPIO_VALUE_INVALID},
  // LAST
  {NULL, NULL, GPIO_DIRECTION_INVALID, GPIO_VALUE_INVALID}
};


//BIC GPIO 
const char *bic_gpio_pin_name_es[] = {
     //GPIOA
    "FM_BMC_PCH_SCI_LPC_R_N",
    "FM_BIOS_POST_CMPLT_BMC_N",
    "FM_SLPS3_PLD_N",
    "IRQ_BMC_PCH_SMI_LPC_R_N",
    "IRQ_UV_DETECT_N",
    "FM_UV_ADR_TRIGGER_EN_R",
    "IRQ_SMI_ACTIVE_BMC_N",
    "SMB_E1S_0_RST_R_N",

    //GPIOB
    "SMB_E1S_0_INA233_ALRT_N",
    "TP_BIC_R3",
    "A_P3V_BAT_SCALED_EN_R",         //10
    "FM_SPI_PCH_MASTER_SEL_R",
    "FM_PCHHOT_N",
    "FM_SLPS4_PLD_N",
    "FM_S3M_CPU0_CD_INIT_ERROR",
    "PWRGD_SYS_PWROK",

    // GPIOC
    "FM_HSC_TIMER",
    "IRQ_SMB_IO_LVC3_STBY_ALRT_N",
    "IRQ_CPU0_VRHOT_N",
    "DBP_CPU_PREQ_BIC_N",
    "FM_CPU_THERMTRIP_LATCH_LVT3_N", //20
    "FM_CPU_SKTOCC_LVT3_PLD_N",
    "H_CPU_MEMHOT_OUT_LVC3_N",
    "RST_PLTRST_PLD_N",

    // GPIOD
    "PWRBTN_N",
    "RST_BMC_R_N",
    "H_BMC_PRDY_BUF_N",
    "BMC_READY",
    "BIC_READY",
    "FM_RMCA_LVT3_N",
    "HSC_MUX_SWITCH_R",
    "FM_FORCE_ADR_N_R",              //30

    // GPIOE
    "PWRGD_CPU_LVC3",
    "FM_PCH_BMC_THERMTRIP_N",
    "FM_THROTTLE_R_N",
    "IRQ_HSC_ALERT2_N",
    "SMB_SENSOR_LVC3_ALERT_N",
    "FM_CATERR_LVT3_N",
    "SYS_PWRBTN_N",
    "RST_PLTRST_BUF_N",

    "IRQ_BMC_PCH_NMI_R",             //40
    "IRQ_SML1_PMBUS_ALERT_N",
    "IRQ_PCH_CPU_NMI_EVENT_N",
    "FM_BMC_DEBUG_ENABLE_N",
    "FM_DBP_PRESENT_N",
    "FM_FAST_PROCHOT_EN_N_R",
    "FM_SPI_MUX_OE_CTL_PLD_N",
    "FBRK_N_R",

    // GPIOG
    "FM_PEHPCPU_INT",
    "FM_BIOS_MRC_DEBUG_MSG_DIS_R",
    "FAST_PROCHOT_N",                //50
    "FM_JTAG_TCK_MUX_SEL_R",
    "BMC_JTAG_SEL_R",
    "H_CPU_ERR0_LVC3_N",
    "H_CPU_ERR1_LVC3_N",
    "H_CPU_ERR2_LVC3_N",

    // GPIOH
    "RST_RSMRST_BMC_N",
    "FM_MP_PS_FAIL_N",
    "H_CPU_MEMTRIP_LVC3_N",
    "FM_CPU_BIC_PROCHOT_LVT3_N",

    // GPIOL
    "SSD0_PRSNT_N",                  //60
    "SSD1_PRSNT_N",
    "IRQ_PVCCD_CPU0_VRHOT_LVC3_N",
    "FM_PVCCIN_CPU0_PWR_IN_ALERT_N",
    "UART_BIC_EXP_TXD",
    "UART_BIC_EXP_R_RXD",

    // GPIOM
    "Reserve_GPIOM1",
    "FM_THROTTLE_IN_N",
    "UART_BIC_TXD",
    "UART_BIC_R_RXD",               //70

    // GPION
    "SGPIO_BMC_CLK_R",
    "SGPIO_BMC_LD_R_N",
    "SGPIO_BMC_DOUT_R",
    "SGPIO_BMC_DIN",
};

const char *bic_gpio_pin_name_ti[] = {
    "PWRGD_BMC_PS_PWROK_R",
    "FM_PCH_BMC_THERMTRIP_N",
    "IRQ_HSC_ALERT2_N",
    "RST_RSTBTN_OUT_N",
    "FM_JTAG_TCK_MUX_SEL",
    "FM_HSC_TIMER",
    "FM_CPU_MEMHOT_OUT_N",
    "FM_SPD_DDRCPU_LVLSHFT_EN",
    "RST_PLTRST_FROM_PCH_N",
    "IRQ_BMC_PRDY_NODE_OD_N",
    "FM_CPU_SKTOCC_LVT3_N",           //10
    "IRQ_NMI_EVENT_R_N",
    "IRQ_SMB_IO_LVC3_STBY_ALRT_N",
    "PWRBTN_N",
    "A_P3V_BAT_SCALED_EN",
    "RST_BMC_R_N",
    "FM_MP_PS_FAIL_N",
    "FM_CPU_THERMTRIP_LATCH_LVT3_N",
    "FM_SLPS4_R_N",
    "JTAG_BMC_NTRST_R_N",
    "FM_BMC_PCH_SCI_LPC_N",           //20
    "FM_BMC_DEBUG_ENABLE_N",
    "DBP_PRESENT_R2_N",
    "PVCCIO_CPU",
    "FM_FAST_PROCHOT_EN_N",
    "FM_CPU_FIVR_FAULT_LVT3_N",
    "CRC_ERROR_R",
    "FM_BOARD_REV_ID0",
    "FM_BOARD_REV_ID1",
    "FM_BOARD_REV_ID2",
    "FM_PWRBTN_OUT_N",                //30
    "FM_CPU_THERMTRIP_LVT3_N",
    "FM_CPU_MSMI_CATERR_LVT3_N",
    "IRQ_BMC_PCH_NMI_R",
    "FM_BIC_RST_RTCRST",
    "PWRGD_CPU_LVC3_R",
    "PWRGD_SYS_PWROK",
    "BIC_READY",
    "HSC_MUX_SWITCH",
    "FM_FORCE_ADR_N",
    "FM_PEHPCPU_INT",                 //40
    "FM_MRC_DEBUG_EN",
    "BMC_READY",
    "FM_THERMTRIP_DLY_TO_PCH",
    "FM_BMC_CPU_PWR_DEBUG_N",
    "IRQ_PVCCIO_CPU_VRHOT_LVC3_N",
    "IRQ_PVDDQ_ABC_VRHOT_LVT3_N",
    "IRQ_PVCCIN_CPU_VRHOT_LVC3_N",
    "IRQ_SML1_PMBUS_ALERT_N",
    "FM_BMC_PREQ_N_NODE_R1",
    "FM_MEM_THERM_EVENT_LVT3_N",      //50
    "IRQ_PVDDQ_DEF_VRHOT_LVT3_N",
    "FM_CPU_ERR0_LVT3_N",
    "FM_CPU_ERR1_LVT3_N",
    "FAST_PROCHOT_N",
    "BMC_JTAG_SEL",
    "FM_CPU_ERR2_LVT3_N",
    "IRQ_SML0_ALERT_MUX_R_N",
    "RST_PLTRST_BMC_N",
    "FM_SLPS3_R_N",
    "DBP_SYSPWROK_R",                 //60
    "IRQ_UV_DETECT_N",
    "FM_UV_ADR_TRIGGER_EN",
    "IRQ_SMI_ACTIVE_BMC_N",
    "RST_RSMRST_BMC_N",
    "BMC_HEARTBEAT_LED_R",
    "IRQ_BMC_PCH_SMI_LPC_R_N",
    "FM_BIOS_POST_CMPLT_BMC_N",
};
static const uint8_t bic_gpio_pin_size_es =
    ARRAY_SIZE(bic_gpio_pin_name_es);
static const uint8_t bic_gpio_pin_size_ti =
    ARRAY_SIZE(bic_gpio_pin_name_ti);

#ifdef CONFIG_GRANDCANYON2
gpio_cfg *gpio_expander_gpio_table      = NULL;
size_t    gpio_expander_gpio_table_size = 0;

static const bool board_id_invert[BOARD_ID_PIN_NUM] = { false, false, false };

/* GPIOH2/H1/H0 raw value: MP=6, others=DVT */
#define STAGE_MP 6

/* Returns 0 on success, sets *is_mp = true if MP stage */
int fbgc_local_get_system_stage(bool *is_mp) {
  static int cached = -1;
  const char *pins[BOARD_ID_PIN_NUM] = { "GPIOH2", "GPIOH1", "GPIOH0" };
  uint8_t s = 0;
  int bits[BOARD_ID_PIN_NUM] = { 0 };

  if (!is_mp) {
    syslog(LOG_WARNING, "%s(): is_mp is NULL", __func__);
    return -1;
  }

  if (cached >= 0) {
    *is_mp = (cached == STAGE_MP);
    return 0;
  }

  for (int i = 0; i < BOARD_ID_PIN_NUM; i++) {
    gpio_desc_t *g = gpio_open_by_name(GPIO_CHIP_ASPEED, pins[i]);
    if (!g) {
      syslog(LOG_WARNING, "%s(): open %s failed: %m", __func__, pins[i]);
      return -1;
    }

    gpio_value_t v;
    if (gpio_get_value(g, &v) != 0) {
      syslog(LOG_WARNING, "%s(): get %s value failed: %m", __func__, pins[i]);
      gpio_close(g);
      return -1;
    }
    gpio_close(g);

    bits[i] = (v == GPIO_VALUE_HIGH) ? 1 : 0;
    if (board_id_invert[i]) bits[i] ^= 1;
    s = (s << 1) | (uint8_t)bits[i];  /* H2=MSB, H0=LSB */
  }

  cached = (int)s;
  *is_mp = (s == STAGE_MP);
  return 0;
}

static int fbgc_fallback_read_uic_location(uint8_t *loc) {
  if (!loc) return -1;

  int retry = 0;
  while (retry < 5) {
    gpio_desc_t *g = gpio_open_by_name(GPIO_CHIP_ASPEED, "GPIOY3");
    if (!g) {
      syslog(LOG_WARNING, "%s(): open GPIOY3 failed, retry %d/5: %m",
             __func__, retry + 1);
      retry++;
      sleep(1);
      continue;
    }

    gpio_value_t v;
    if (gpio_get_value(g, &v) != 0) {
      syslog(LOG_WARNING, "%s(): get GPIOY3 value failed, retry %d/5: %m",
             __func__, retry + 1);
      gpio_close(g);
      retry++;
      sleep(1);
      continue;
    }
    gpio_close(g);

    /* LOW (0) → A side, HIGH (1) → B side */
    *loc = (v == GPIO_VALUE_HIGH) ? UIC_SIDEB : UIC_SIDEA;
    syslog(LOG_INFO, "%s(): GPIOY3=%d → %s",
           __func__, v, (*loc == UIC_SIDEB) ? "SIDE-B" : "SIDE-A");
    return 0;
  }

  syslog(LOG_WARNING, "%s(): failed after 5 retries", __func__);
  return -1;
}

static const char *fbgc_detect_active_table(void) {
  if (gpio_is_exported("COMP_A_PRSNT_N")) return "dvt_a";
  if (gpio_is_exported("COMP_B_PRSNT_N")) return "dvt_b";
  if (gpio_is_exported("COMP_PRSNT_N"))   return "hack";
  return NULL;
}

int fbgc_gpio_init(void) {
  uint8_t uic_loc = UIC_SIDEA;
  bool    is_mp   = false;
  int     got_stage;

  /* Step 0: shadow has been exported → use directly */
  const char *detected = fbgc_detect_active_table();
  if (detected != NULL) {
    if (strcmp(detected, "dvt_a") == 0) {
      gpio_expander_gpio_table      = gpio_expander_gpio_table_dvt_a;
      gpio_expander_gpio_table_size = MAX_GPIO_EXPANDER_GPIO_PINS;
      return 0;
    } else if (strcmp(detected, "dvt_b") == 0) {
      gpio_expander_gpio_table      = gpio_expander_gpio_table_dvt_b;
      gpio_expander_gpio_table_size = MAX_GPIO_EXPANDER_GPIO_PINS;
      return 0;
    } else if (strcmp(detected, "hack") == 0) {
      gpio_expander_gpio_table      = gpio_expander_gpio_table_hack;
      gpio_expander_gpio_table_size = MAX_GPIO_EXPANDER_GPIO_PINS;
      return 0;
    }
  }

  /* Step 1: Read GPIOH2/H1/H0, retry 3 times */
  got_stage = -1;
  for (int retry = 0; retry < 3; retry++) {
    got_stage = fbgc_local_get_system_stage(&is_mp);
    if (got_stage == 0) {
      break;
    }
    syslog(LOG_WARNING, "%s(): GPIO stage read failed, retry %d/3", __func__, retry + 1);
    usleep(10000);
  }

  /* Step 2: Read GPIOY3 to determine the A/B side */
  uint8_t uic_loc_for_log = UIC_SIDEA;
  if (fbgc_fallback_read_uic_location(&uic_loc_for_log) < 0) {
    syslog(LOG_WARNING, "%s(): GPIOY3 read failed, side unknown", __func__);
  }

  if (got_stage < 0) {
    gpio_expander_gpio_table      = gpio_expander_gpio_table_hack;
    gpio_expander_gpio_table_size = MAX_GPIO_EXPANDER_GPIO_PINS;
    syslog(LOG_WARNING,
           "%s(): GPIO stage read failed → HACK (side=%s)", __func__,
           (uic_loc_for_log == UIC_SIDEB) ? "B" : "A");
    return 0;
  }

  /* Step 3: MP → HACK, Others → DVT A/B */
  uic_loc = uic_loc_for_log;

  if (is_mp) {
    gpio_expander_gpio_table      = gpio_expander_gpio_table_hack;
    gpio_expander_gpio_table_size = MAX_GPIO_EXPANDER_GPIO_PINS;
  } else {
    if (uic_loc == UIC_SIDEB) {
      gpio_expander_gpio_table = gpio_expander_gpio_table_dvt_b;
    } else {
      gpio_expander_gpio_table = gpio_expander_gpio_table_dvt_a;
    }
  }

  gpio_expander_gpio_table_size = MAX_GPIO_EXPANDER_GPIO_PINS;
  return 0;
}

static inline void ensure_expander_table_selected(void) {
  if (gpio_expander_gpio_table == NULL) {
    (void)fbgc_gpio_init();
  }
}
#endif /* CONFIG_GRANDCANYON2 */

const char *fbgc_get_gpio_name(uint8_t gpio) {
#ifdef CONFIG_GRANDCANYON2
  if (gpio < MAX_GPIO_EXPANDER_GPIO_PINS) {
    ensure_expander_table_selected();
    if (gpio < gpio_expander_gpio_table_size) {
      const char *name = gpio_expander_gpio_table[gpio].shadow_name;
      if (name) return name;
      syslog(LOG_WARNING, "%s() expander gpio %u not mapped on this side/stage",
             __func__, gpio);
      return "";
    }
    syslog(LOG_WARNING, "%s() expander index out of range: %u", __func__, gpio);
    return "";
  } else if (gpio < MAX_GPIO_PINS) {
    return bmc_gpio_table[gpio].shadow_name;
  } else {
    syslog(LOG_WARNING, "%s() Invalid gpio number: %u\n", __func__, gpio);
    return "";
  }
#else
  if (gpio < MAX_GPIO_EXPANDER_GPIO_PINS) {
    return gpio_expander_gpio_table[gpio].shadow_name;
  } else if (gpio < MAX_GPIO_PINS) {
    return bmc_gpio_table[gpio].shadow_name;
  } else {
    syslog(LOG_WARNING, "%s() Invalid gpio number: %u\n", __func__, gpio);
    return "";
  }
#endif /* CONFIG_GRANDCANYON2 */
}

uint8_t
fbgc_get_bic_gpio_list_size(void) {

  if (fbgc_is_grandcanyon2()) {
        return bic_gpio_pin_size_es;
  }
    return bic_gpio_pin_size_ti;
}

const char *
fbgc_get_bic_gpio_name(uint8_t gpio) {
  if (gpio > fbgc_get_bic_gpio_list_size()) {
    syslog(LOG_WARNING, "%s(): Wrong gpio pin %u", __func__, gpio);
    return "";
  }

  if (fbgc_is_grandcanyon2()) {
      return bic_gpio_pin_name_es[gpio];
  }

  return bic_gpio_pin_name_ti[gpio];
}
