# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fb-anacapa-layer"
BBFILE_PATTERN_fb-anacapa-layer := "^${LAYERDIR}/"

LAYERSERIES_COMPAT_fb-anacapa-layer := "whinlatter walnascar styhead scarthgap nanbield kirkstone"
