# Until the device tree is merged into the upstream kernel, we need to
# override what is in the upstream lfdarwin.conf with the patched DTS reference.
KERNEL_DEVICETREE = "aspeed/aspeed-bmc-facebook-darwin.dtb"

MACHINE_FEATURES += "emmc emmc-ext4"
