#!/bin/bash

# Count errors and don't exit early
errors=0
CountErrorsHandler () {
  (( errors++ ))
}

trap CountErrorsHandler ERR

# Try to use the black executable, it it does not
# exist, try the python module.
BLACK=$(command -v black)
if [ ! -x "$BLACK" ]; then
  BLACK="python3 -m black"
fi

do_lint_py() {
  echo "PY: $1"
  $BLACK --diff --check "$1"
}

do_lint_sh() {
  echo "SH: $1"
  shellcheck -x "$1"
}

do_lint_cppcheck() {
  echo "CPPC: $1"
  options=( "-j2"
      "--force"
      "--inconclusive"
      "--error-exitcode=1"
      "--enable=performance,style,portability,information"
      "--suppress=unmatchedSuppression"
      "--library=tools/circle-ci/lint-config/cppcheck.cfg"
      "--suppressions-list=tools/circle-ci/lint-config/cppcheck-suppressions.txt" )
      cppcheck "${options[@]}" "$1"
}

is_c_family_file() {
  if [[ "$1" =~ .*\.c$ ]]   || \
     [[ "$1" =~ .*\.cc$ ]]  || \
     [[ "$1" =~ .*\.cu$ ]]  || \
     [[ "$1" =~ .*\.cxx$ ]] || \
     [[ "$1" =~ .*\.cpp$ ]] || \
     [[ "$1" =~ .*\.h$ ]]   || \
     [[ "$1" =~ .*\.hh$ ]]  || \
     [[ "$1" =~ .*\.hpp$ ]] || \
     [[ "$1" =~ .*\.hxx$ ]] || \
     [[ "$1" =~ .*\.tcc$ ]]
  then
    return 0
  else
    return 1
  fi
}

ORIGIN_COMMIT="$(git merge-base HEAD origin/helium 2>/dev/null || git merge-base HEAD origin/main)"

MODIFIED_FILES="$(git diff --diff-filter=d --name-only "$ORIGIN_COMMIT" --)"

for f in $MODIFIED_FILES; do
  if [[ "$f" =~ .*\.sh$ ]]; then
    do_lint_sh "$f"
  # any of cpp|c|cc|cu|cxx|h|hh|hpp|hxx|tcc
  elif is_c_family_file "$f"; then
    do_lint_cppcheck "$f"
 elif [[ "$f" =~ .*\.py$ ]]; then
   do_lint_py "$f"
  else
    first=$(head -1 "$f")
    if [[ "$first" =~ \#!/.*/sh  || "$first" =~ \#!/.*/bash ]]; then
      do_lint_sh "$f"
    elif [[ "$first" =~ \#!/.*python  || "$first" =~ \#!/.*python3 ]]; then
      do_lint_py "$f"
    else
      echo "IGNORE: $f"
    fi
  fi
done

if [ "$errors" -ne 0 ]; then
  echo "FAIL : $errors files failed linting."
  exit 1
else
  echo "PASS"
fi
