swagger: '2.0'
info:
  description: Swagger doc for /api/e1s_iocm/sensors
  title: Swagger doc for /api/e1s_iocm/sensors
  version: 1.0.0
paths:
  /api/e1s_iocm/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  E1S_B0_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  E1S_B1_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  E1S_B0_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  E1S_B1_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  E1S_B0_P12V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  E1S_B1_P12V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  E1S_B0_P3V3:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  E1S_B1_P3V3:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  IOCM_P3V3_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  IOCM_P1V8:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  IOCM_P1V5:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  IOCM_P0V865:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  IOCM_CUR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  IOCM_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  IOCM_IOC_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
