#!/bin/bash
#
# Copyright 2020-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#
. /usr/local/bin/openbmc-utils.sh

usage() {
    echo "Usage $0 [2..9]"
}

show_pim_fruid() {
    weutil PIM"$1"
    exit $?
}

if [ "$#" -ne 1 ]; then
    usage
    exit 1
fi

num="${1}"
if [ "${num}" -ge 2 ] && [ "${num}" -le 9 ];then
    show_pim_fruid "${num}"
else
    usage
    exit 1
fi
